package com.example.domain;

import com.akkaserverless.javasdk.valueentity.ValueEntityBase;
import com.example.CounterApi;
import com.google.protobuf.Empty;

// This class would be generated by codegen

/** A value entity. */
public abstract class CounterInterface2 extends ValueEntityBase<CounterDomain.CounterState> {

    public abstract Effect<Empty> increase(
            CounterDomain.CounterState currentState,
            CounterApi.IncreaseValue command);

    public abstract Effect<Empty> decrease(
            CounterDomain.CounterState currentState,
            CounterApi.DecreaseValue command);

    public abstract Effect<Empty> reset(
            CounterDomain.CounterState currentState,
            CounterApi.ResetValue command);

    public abstract Effect<CounterApi.CurrentCounter> getCurrentCounter(
            CounterDomain.CounterState currentState,
            CounterApi.GetCounter command);

}
