/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package customer.view;

import com.akkaserverless.javasdk.view.ViewContext;
import customer.domain.CustomerDomain;

public class CustomerByEmailView extends AbstractCustomerByEmailView {

  public CustomerByEmailView(ViewContext context) {}

  
}
