include::ROOT:partial$include.adoc[]

= Publishing and Subscribing with Actions
:page-supergroup-java-scala: Language

A very common use case when building Microservices is to publish and subscribe to a stream of events. The source of events can be the journal of an event sourced entity, the value entity state changes, a https://cloud.google.com/pubsub/docs/overview[Google Cloud Pub/Sub] or Apache Kafka topic for asynchronous messaging between services.

With Actions you can:

- subscribe to events emitted by an event sourced entity within the same service.
- subscribe to state changes emitted by a value entity within the same service.
- subscribe to events from Event Sourced Entities published as xref:service-to-service.adoc[service to service eventing]
- subscribe to external events from https://cloud.google.com/pubsub/docs/overview[Google Cloud Pub/Sub] or Apache Kafka.
- publish events to a Google Cloud Pub/Sub or Apache Kafka topic.

Messages are guaranteed to be delivered at least once. This means that receivers must be able to handle duplicate messages.

== Publishing Entity events to a Topic

To illustrate how to publish entity events, we will assume the existence of an xref:event-sourced-entities.adoc[Event Sourced] Counter entity that emits events of types: `ValueIncreased` and `ValueDecreased`. We will get the events delivered to an Action, apply some transformation and let them be published to a topic.

include::partial$pubsub-note.adoc[]

[.tabset]
Java::
+
[source,protobuf,indent=0]
.src/main/proto/com/example/actions/counter_topic.proto
----
include::example$java-protobuf-eventsourced-counter/src/main/proto/com/example/actions/counter_topic.proto[tag=counter-topic]
----
<1> Import the Counter Domain file containing the definitions of the events. This is typically a proto definition within the same service.
<2> The protobuf option (kalix.codegen) is specific to code-generation as provided by the Kalix Maven plugin. This annotation indicates to the code-generation that an Action must be generated.
<3> The `Increase` method receives the event `ValueIncreased` and returns the transformed type `Increased`.
<4> The `(kalix.method).eventing.in` annotation indicates that events from the entity type `counter` should be delivered to this method (when the type is `ValueIncreased`).
<5> The `(kalix.method).eventing.out` annotation indicates that the returned value from this method should be published to the topic called `counter-events`.

Scala::
+
[source,proto,indent=0]
.src/main/proto/customer/domain/customer_domain.proto
----
include::example$scala-protobuf-eventsourced-counter/src/main/proto/com/example/actions/counter_topic.proto[tag=counter-topic]
----
<1> Import the Counter Domain file containing the definitions of the events. This is typically a proto definition within the same service.
<2> The protobuf option (kalix.codegen) is specific to code-generation as provided by the Kalix sbt plugin. This annotation indicates to the code-generation that an Action must be generated.
<3> The `Increase` method receives the event `ValueIncreased` and returns the transformed type `Increased`.
<4> The `(kalix.method).eventing.in` annotation indicates that events from the entity type `counter` should be delivered to this method (when the type is `ValueIncreased`).
<5> The `(kalix.method).eventing.out` annotation indicates that the returned value from this method should be published to the topic called `counter-events`.

The class `CounterJournalToTopicAction` gets generated for us based on the proto file defined above.

[.tabset]
Java::
+
[source,java,indent=0]
.src/main/java/com/example/actions/CounterJournalToTopicAction.java
----
include::example$java-protobuf-eventsourced-counter/src/main/java/com/example/actions/CounterJournalToTopicAction.java[tag=counter-topic]
----
<1> We convert the incoming domain event `CounterDomain.ValueIncreased` to the outgoing topic API `CounterTopicApi.Increased`.
<2> We use the converted object to build a reply. The `CounterTopicApi.Increased` message will be published to the topic.

Scala::
+
[source,scala,indent=0]
.src/main/scala/com/example/actions/CounterJournalToTopicAction.scala
----
include::example$scala-protobuf-eventsourced-counter/src/main/scala/com/example/actions/CounterJournalToTopicAction.scala[tag=counter-topic]
----
<1> We convert the incoming domain event `ValueIncreased` to the outgoing topic API `Increased` and return that as a reply.

In this example we have published Protobuf messages to the topic which is convenient if the consuming end is also a Kalix service. For an external consumer Protobuf may not be a supported format, for details on publishing other formats see xref:java-protobuf:serialization.adoc[Handling Serialization].

== Subscribing to state changes from a Value Entity

Similar to subscribing to events from an Event Sourced Entity, you can also subscribe to state changes from a Value Entity.

[.tabset]
Java::
+
[source,proto,indent=0]
.src/main/proto/com/example/actions/counter_states_sub.proto
----
include::example$java-protobuf-valueentity-counter/src/main/proto/com/example/actions/counter_states_sub.proto[tag=state-subscription]
----
<1> Import the Counter Domain from the Value Entity example (see xref:java-protobuf:value-entity.adoc[Implementing Value Entities]).
<2> The protobuf option (kalix.codegen) is specific to code-generation as provided by the Kalix Maven plugin. This annotation indicates to the code-generation that an Action must be generated.
<3> The `(kalix.method).eventing.in` annotation indicates that state changes from the value entity type `counter` should be delivered to this method.
<4> The second `(kalix.method).eventing.in` annotation with `handle_deletes: true` and (required) `google.protobuf.Empty` as a parameter defines that this method is used for handling value entity deletes.

Scala::
+
[source,proto,indent=0]
.src/main/proto/com/example/actions/counter_states_sub.proto
----
include::example$scala-protobuf-valueentity-counter/src/main/proto/com/example/actions/counter_states_sub.proto[tag=state-subscription]
----
<1> Import the Counter Domain from the Value Entity example (see xref:java-protobuf:value-entity.adoc[Implementing Value Entities]).
<2> The protobuf option (kalix.codegen) is specific to code-generation as provided by the Kalix sbt plugin. This annotation indicates to the code-generation that an Action must be generated.
<3> The `(kalix.method).eventing.in` annotation indicates that state changes from the value entity type `counter` should be delivered to this method.
<4> The second `(kalix.method).eventing.in` annotation with `handle_deletes: true` and (required) `google.protobuf.Empty` as a parameter defines that this method is used for handling value entity deletes.

== Subscribing to a Topic

It's also possible to subscribe to a Pub/Sub topic. To receive messages from a Pub/Sub topic, annotate a service method in the Protobuf service definition with the `option (kalix.method).eventing.in` annotation and specify the topic name in the `topic` section of the annotation.

include::partial$pubsub-note.adoc[]

For illustration purpose, we can add a second Action that consumes from the Pub Sub topic `counter-events` from the previous example.

[.tabset]
Java::
+
[source,java,indent=0]
.src/main/proto/com/example/actions/counter_topic_sub.proto
----
include::example$java-protobuf-eventsourced-counter/src/main/proto/com/example/actions/counter_topic_sub.proto[tag=counter-topic-sub]
----
<1> Import the Counter Topic types from previous example.
<2> The protobuf option (kalix.codegen) is specific to code-generation as provided by the Kalix Maven plugin. This annotation indicates to the code-generation that an Action must be generated.
<3> Define methods for each of the possible incoming messages and annotate them with `(kalix.method).eventing.in` indicating that the source of events is the topic `counter-events`.

Scala::
+
[source,scala,indent=0]
.src/main/proto/customer/domain/customer_domain.proto
----
include::example$scala-protobuf-eventsourced-counter/src/main/proto/com/example/actions/counter_topic_sub.proto[tag=counter-topic-sub]
----
<1> Import the Counter Topic types from previous example.
<2> The protobuf option (kalix.codegen) is specific to code-generation as provided by the Kalix sbt plugin. This annotation indicates to the code-generation that an Action must be generated.
<3> Define methods for each of the possible incoming messages and annotate them with `(kalix.method).eventing.in` indicating that the source of events is the topic `counter-events`.

The class `CounterTopicSubscriptionAction` gets generated for us based on the proto file defined above.

[.tabset]
Java::
+
[source,java,indent=0]
.src/main/java/com/example/actions/CounterTopicSubscriptionAction.java
----
include::example$java-protobuf-eventsourced-counter/src/main/java/com/example/actions/CounterTopicSubscriptionAction.java[tag=counter-topic-sub]
----

Scala::
+
[source,scala,indent=0]
.src/main/java/com/example/actions/CounterTopicSubscriptionAction.java
----
include::example$scala-protobuf-eventsourced-counter/src/main/scala/com/example/actions/CounterTopicSubscriptionAction.scala[tag=counter-topic-sub]
----

The events from the topic are delivered to the new Action. The implementation may vary, for this simplified example we are just logging it,
but it could a forward to some other component or external service.

== Receiving messages from an external Topic

In the example above, we consumed Protobuf messages from a topic that we control ourselves. When consuming an external topic, it's very likely that the message format is not under your control and is not known by Kalix.

In such case, the Action definition should receive a type depending on the type of the message payload. See xref:java-protobuf:serialization.adoc[Handling Serialization] for more information on how to deal with data formats.

== Subscribing and acting upon

Another possible usage for Actions is to consume events and act upon.

For example, you may consume events from one entity or from a topic, transform to commands and send to an another entity or an external system. This is similar to the usage explained in xref:actions-as-controller.adoc[Actions as Controller], except that the Action is driven by the flow of incoming events instead of external user requests.

For that purpose, it's enough to add the `(kalix.method).eventing.in` and omit the `(kalix.method).eventing.out`.

== Accessing the Entity ID

[.tabset]
Java::
+
For many use cases, a subscriber to an event log will trigger other services and needs to pass the entity ID to the receiver. The events of an Event Sourced entity, by design, do not include the entity ID, but it is made available to the subscriber via the metadata field `subject`, accessible through `eventSubject` in the  link:{attachmentsdir}/api/io/kalix/javasdk/action/ActionContext.html[`ActionContext`{tab-icon}, window="new"].
+
You can access the link:{attachmentsdir}/api/kalix/javasdk/action/ActionContext.html[`ActionContext`{tab-icon}, window="new"] through method `actionContext()`.
+
[source,java,indent=0]
.src/main/java/com/example/actions/CounterJournalToTopicAction.java
----
include::example$java-protobuf-eventsourced-counter/src/main/java/com/example/actions/CounterJournalToTopicAction.java[tag=counter-topic-event-subject]
----

Scala::
+
For many use cases, a subscriber to an event log will trigger other services and needs to pass the entity ID to the receiver. The events of an Event Sourced entity, by design, do not include the entity ID, but it is made available to the subscriber via the metadata field `subject`, accessible through `eventSubject` in the  link:{attachmentsdir}/scala-api/kalix/scalasdk/action/ActionContext.html[`ActionContext`{tab-icon}, window="new"].
+
You can access the link:{attachmentsdir}/scala-api/kalix/scalasdk/action/ActionContext.html[`ActionContext`{tab-icon}, window="new"] through method `actionContext`.
+
[source,scala,indent=0]
.src/main/proto/customer/domain/customer_domain.proto
----
include::example$scala-protobuf-eventsourced-counter/src/main/scala/com/example/actions/CounterJournalToTopicAction.scala[tag=counter-topic-event-subject]
----

== Ignoring events

When consuming events, each event must be matched by a Protobuf service method. In case your component is only interested in certain events, you may declare a method to receive all events that are not received by the other methods. If an event type is not handled, the Action will fail. Actions are designed to restart, but since the handler is missing, it will fail again. Therefore, it's important to define methods for all events or define a catch-all method in case you want to discard some events.


[.tabset]
Java::
+
[source,protobuf,indent=0]
.src/main/proto/com/example/actions/counter_topic.proto
----
include::example$java-protobuf-eventsourced-counter/src/main/proto/com/example/actions/counter_topic.proto[tag=counter-ignore]
----
<1> We must annotate it with a `(kalix.method).eventing.in`.
<2> Set `ignore: true` option.

Scala::
+
[source,proto,indent=0]
.src/main/proto/customer/domain/customer_domain.proto
----
include::example$scala-protobuf-eventsourced-counter/src/main/proto/com/example/actions/counter_topic.proto[tag=counter-ignore]
----
<1> We must annotate it with a `(kalix.method).eventing.in`.
<2> Set `ignore: true` option.

The `Ignore` method here is defined as a catch-all because it has input type `Any`. Instead of using a catch-all it can be better to define concrete methods for all known event types that should be ignored because then there is no risk of accidentally ignoring events that are added in later evolution of the service.

When adding the `ignore: true` annotation the corresponding implementation is not needed in the component. It is more efficient to use `ignore: true` than implementing the method with an immediate reply.

== Deployment dependent topic names

It is possible to use environment variables to control the name of the topic that is used for consuming from or producing events to, this is useful for example for using the same image in staging and production deployments but having them interact with separate topics.

Referencing environment variables is done with the syntax `$\{VAR_NAME}` in the `topic` string in `eventing.in.topic` or `eventing.out.topic` blocks.

Note that if changing the `topic` name after it has once been deployed for an event consumer means the consumer will start over from the beginning of the topic.

See https://docs.kalix.io/kalix/kalix_services_deploy.html[kalix service deploy] for details on how to set environment variables when deploying a service.


== Testing the Integration

When a Kalix service relies on a broker, it might be useful to use integration tests to assert that those boundaries work as intended. For such scenarios, you can either:

* Use TestKit's mocked topic:
** this offers a general API to inject messages into topics or read the messages written to another topic, regardless of the specific broker integration you have configured.
* Run an external broker instance:
** if you're interested in running your integration tests against a real instance, you need to provide the broker instance yourself by running it in a separate process in your local setup and make sure to disable the use of TestKit's test broker. Currently, **the only external broker supported in integration tests is Google PubSub Emulator.**

=== TestKit Mocked Topic

Following up on the counter entity example used above, let's consider an example (composed by 2 Actions and 1 Event Sourced entity) in which:

* commands are consumed from an external topic `event-commands` and forwarded to a Counter entity
* the Counter entity is an Event Sourced Entity and has its events published to another topic `counter-events`

To test this flow, we will take advantage of the TestKit to be able to push commands into the `event-commands` topic and check on what messages are produced to topic `counter-events`.

[.tabset]
Java::
+
[source,java]
.src/it/java/com/example/CounterTopicIntegrationTest.java
----
include::example$java-protobuf-eventsourced-counter/src/it/java/com/example/CounterTopicIntegrationTest.java[tag=test-topic]
----
<1> Start the TestKit, booting up both the service and its proxy.
<2> Get a mocked topic named `counter-commands` from the TestKit.
<3> Get a mocked topic named `counter-events` from the TestKit.
<4> Build 2 commands and publish both to the topic. Note the `counterId` is passed as the subject id of the message.
<5> Read 2 messages, one at a time. Note we pass in the expected class type for the next message.
<6> Assert the received messages have the same value as the commands sent.

Scala::
+
[source,scala]
.src/test/scala/com/example/CounterServiceIntegrationSpec.scala
----
include::example$scala-protobuf-eventsourced-counter/src/test/scala/com/example/CounterServiceIntegrationSpec.scala[tag=test-topic]
----
<1> Start the TestKit, booting up both the service and its proxy.
<2> Get a mocked topic named `counter-commands` from the TestKit.
<3> Get a mocked topic named `counter-events` from the TestKit.
<4> Build 2 commands and publish both to the topic. Note the `counterId` is passed as the subject id of the message.
<5> Read 2 messages, one at a time and assert the received messages values. Note we pass in the expected class type for the next message.

TIP: In the example above we take advantage of the TestKit to serialize / deserialize the messages and pass all the required metadata automatically for us. However, the API also offers the possibility to read and write raw bytes, construct your metadata or read multiple messages at once.

==== Metadata

Typically, messages are published with associated metadata. If you want to construct your own `Metadata` or make sure the messages published out of your service have a specific header, you can also do so using the TestKit, as shown below.

[.tabset]
Java::
+
[source,java,indent=0]
.src/it/java/com/example/CounterTopicIntegrationTest.java
----
include::example$java-protobuf-eventsourced-counter/src/it/java/com/example/CounterTopicIntegrationTest.java[tag=test-topic-metadata]
----
<1> Build a `CloudEvent` object with the 3 required attributes, respectively: `id`, `source` and `type`.
<2> Add the subject to which the message is related, that is the `counterId`.
<3> Set the mandatory header "Content-Type" accordingly.
<4> Publish the message along with its metadata to topic `commandsTopic`.
<5> Upon receiving the message, access the metadata.
<6> Assert the headers `Content-Type` and `ce-subject` (every CloudEvent header is prefixed with "ce-") have the expected values.

Scala::
+
[source,scala,indent=0]
.src/test/scala/com/example/CounterServiceIntegrationSpec.scala
----
include::example$scala-protobuf-eventsourced-counter/src/test/scala/com/example/CounterServiceIntegrationSpec.scala[tag=test-topic-metadata]
----
<1> Build a `CloudEvent` object with the 3 required attributes, respectively: `id`, `source` and `type`.
<2> Add the subject to which the message is related, that is the `counterId`.
<3> Set the mandatory header "Content-Type" accordingly.
<4> Publish the message along with its metadata to topic `commandsTopic`.
<5> Receive the message of correct type and extract `Metadata`.
<6> Assert the headers `Content-Type` and `ce-subject` (every CloudEvent header is prefixed with "ce-") have the expected values.


==== One Suite, Multiple Tests

When running multiple test cases under the same test suite and thus using a common TestKit instance, be careful to clear the contents of the topics in use so unconsumed messages from previous tests do not mess up with the current one:

[.tabset]
Java::
+
[source,java,indent=0]
.src/it/java/com/example/CounterTopicIntegrationTest.java
----
include::example$java-protobuf-eventsourced-counter/src/it/java/com/example/CounterTopicIntegrationTest.java[tag=clear-topics]
----
<1> Run this before each test.
<2> Clear the topic ignoring any unread messages.

Scala::
+
[source,scala,indent=0]
.src/test/scala/com/example/CounterServiceIntegrationSpec.scala
----
include::example$scala-protobuf-eventsourced-counter/src/test/scala/com/example/CounterServiceIntegrationSpec.scala[tag=clear-topics]
----
<1> Override method from trait `BeforeAndAfterEach`.
<2> Clear the topic ignoring any unread messages.

NOTE: Despite the example, you are neither forced to clear all topics nor to do it before each test. You can do it selectively, or you might not even need it depending on your tests and the flows they test.