= Serving Web Resources
:page-supergroup-java-scala: Language

This guide provides a simple example of how to serve arbitrary web resources like `.html` files.

[.group-java]#To use proto files from artifacts in your schema, you need to adjust your maven build definition (as done in this full link:https://github.com/lightbend/kalix-jvm-sdk/tree/main/samples/java-protobuf-web-resources/pom.xml[example]):#
[.tabset]
Java::
+
--
[source,pom.xml]
----
<includeDependenciesInDescriptorSet>true</includeDependenciesInDescriptorSet>
----
--
Scala::
+
Sbt builds work out-of-the-box with loading proto files from artifacts.

Next, import `HttpBody` and build your Kalix service to return that:

[.tabset]
Java::
+
[source,proto]
----
include::example$java-protobuf-web-resources/src/main/proto/com/example/web_resources.proto[tag=file-service-api]
----
<1> Use `import` to use proto files from dependencies.
<2> Choose `google.api.HttpBody` as the return type.
<3> Enable http-endpoints using `google.api.http`.
<4> Serve files in like `web/index.html`.
<5> Optional: serve files in directories, e.g. `web/img/favicon.png`.
Scala::
+
[source,proto]
----
include::example$scala-protobuf-web-resources/src/main/proto/com/example/web_resources.proto[tag=file-service-api]
----
<1> Use `import` to use proto files from dependencies.
<2> Choose `google.api.HttpBody` as the return type.
<3> Enable http-endpoints using `google.api.http`.
<4> Serve files in like `web/index.html`.
<5> Optional: serve files in directories, e.g. `web/img/favicon.png`.

Use [.group-java]#`effects().reply`# [.group-scala]#`effects.reply`# to serve content (e.g. by loading a file from disk with) a `200` http response:
[.tabset]
Java::
+
[source,java]
----
include::example$java-protobuf-web-resources/src/main/java/com/example/FileServiceAction.java[tag=200-ok]
----
Scala::
+
[source,scala]
----
include::example$scala-protobuf-web-resources/src/main/scala/com/example/FileServiceAction.scala[tag=200-ok]
----
The example also shows how to return additional http-headers.

Use [.group-java]#`effects().ignore`# [.group-scala]#`effects.ignore`# to serve a `404` http response:
[.tabset]
Java::
+
[source,java]
----
include::example$java-protobuf-web-resources/src/main/java/com/example/FileServiceAction.java[tag=404-not-found]
----
Scala::
+
[source,scala]
----
include::example$scala-protobuf-web-resources/src/main/scala/com/example/FileServiceAction.scala[tag=404-not-found]
----

Use [.group-java]#`effects().error`# [.group-scala]#`effects.error`# to serve a `500` http response:
[.tabset]
Java::
+
----
include::example$java-protobuf-web-resources/src/main/java/com/example/FileServiceAction.java[tag=500-error]
----
Scala::
+
[source,scala]
----
include::example$scala-protobuf-web-resources/src/main/scala/com/example/FileServiceAction.scala[tag=500-error]
----


[.tabset]
Java::
+
The code from this page is taken from the link:https://github.com/lightbend/kalix-jvm-sdk/tree/main/samples/java-protobuf-web-resources[full example].

Scala::
+
The code from this page is taken from the link:https://github.com/lightbend/kalix-jvm-sdk/tree/main/samples/scala-protobuf-web-resources[full example].

