# Config for https://github.com/release-drafter/release-drafter
name-template: 'Kalix Java and Scala SDKs $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Java SDK'
    labels:
      - 'java-sdk'
  - title: 'Scala SDK'
    labels:
      - 'scala-sdk'
  - title: 'Spring SDK'
    labels:
      - 'spring-sdk'
  - title: 'Documentation'
    labels:
      - 'Documentation'

change-template: '- $TITLE #$NUMBER by @$AUTHOR'
template: |
  # :mega: Kalix Java and Scala SDKs $NEXT_PATCH_VERSION

  ## Changes

  $CHANGES

  ## :bow: Credits
  Special thanks to the following contributors who helped with this release: $CONTRIBUTORS
