= Customer Registry in Java/Protobuf

include::ROOT:partial$include.adoc[]
include::java-protobuf:partial$attributes.adoc[]

Learn how to create a customer registry in Java, package it into a container, and run it on Kalix.

== Before you begin

* If you're new to Kalix, {console}[create an account, window="console"] so you can try out Kalix for free.
* You'll need to install the https://docs.kalix.io/kalix/install-kalix.html[Kalix CLI, window="new-doc"] to deploy from a terminal window.
* You'll also need
** https://docs.docker.com/engine/install[Docker {minimum_docker_version} or higher, window="new"]
** Java {java-pb-version} or higher
** https://maven.apache.org/download.cgi[Maven {minimum_maven_version} or higher, window="new"]
** https://github.com/fullstorydev/grpcurl#installation[`grpcurl`, window="new"]

[NOTE]
====
If you want to bypass writing code and jump straight to the deployment:

. Download the source code using the Kalix CLI:
`kalix quickstart download customer-registry-java-protobuf`

. Skip to <<Package and deploy your service>>.
====

== Writing the Customer Registry

. From the command line, create a directory for your project.
+
[source,command line]
----
mkdir customerregistry
----

. Change into the project directory.
+
[source,command line]
----
cd customerregistry
----

. Download the `pom.xml` file
+
[source,command line]
----
curl -OL https://raw.githubusercontent.com/lightbend/kalix-jvm-sdk/main/samples/java-protobuf-customer-registry-quickstart/pom.xml
----

. Update the `dockerImage` property (line 13 of the `pom.xml` file) with your container registry name.

== Define the external API

The Customer Registry service will create or retrieve a customer, including their email, phone number and mailing address. The `customer_api.proto` will contain the external API your clients will invoke.

. In your project, create two directories for your protobuf files, `src/main/proto/customer/domain` and `src/main/proto/customer/api`.
[.tabset]
Linux or macOS::
+
--
[source,command line]
----
mkdir -p ./src/main/proto/customer/api
mkdir -p ./src/main/proto/customer/domain
----
--
Windows 10+::
+
--
[source,command line]
----
mkdir src/main/proto/customer/api
mkdir src/main/proto/customer/domain
----
--

. Create a `customer_api.proto` file and save it in the `src/main/proto/customer/api` directory.

. Add declarations for:
+
* The protobuf syntax version, `proto3`.
* The package name, `customer.api`.
* The required Java outer classname, `CustomerAPI`. Messages defined in this file will be generated as inner classes.
* Import `google/protobuf/empty.proto` and Kalix `kalix/annotations.proto`.
+
[source,proto,indent=0]
.src/main/proto/customer/api/customer_api.proto
----
include::example$java-protobuf-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto[tag=declarations]
----

. Add the service endpoint. The service endpoint is annotated with `kalix.codegen` indicating we want to generate a Value Entity for this service.
+
[source,proto,indent=0]
.src/main/proto/customer/api/customer_api.proto
----
include::example$java-protobuf-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto[tag=service]
----

. Add messages to define the fields that comprise a `Customer` object (and its compound `Address`)
+
[source,proto,indent=0]
.src/main/proto/customer/api/customer_api.proto
----
include::example$java-protobuf-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto[tag=messages]
----

. Add the message that will identify which customer to retrieve for the `GetCustomer` message:
+
[source,proto,indent=0]
.src/main/proto/customer/api/customer_api.proto
----
include::example$java-protobuf-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto[tag=method-messages]
----

== Define the domain model

The `customer_domain.proto` contains all the internal data objects (https://docs.kalix.io/reference/glossary.html#entity[Entities, window="new"]). The https://docs.kalix.io/reference/glossary.html#value_entity[Value Entity, window="new"] in this sample is a Key/Value store that stores only the latest updates.

. Create a `customer_domain.proto` file and save it in the `src/main/proto/customer/domain` directory.

. Add declarations for the proto syntax and domain package.
+
* The package name, `customer.domain`.
* The Java outer classname, `CustomerDomain`.
+
[source,proto,indent=0]
.src/main/proto/customer/domain/customer_domain.proto
----
include::example$java-protobuf-customer-registry-quickstart/src/main/proto/customer/domain/customer_domain.proto[tag=declarations]
----

. Add the `CustomerState` message with fields for entity data, and the `Address` message that defines the compound address:
+
[source,proto,indent=0]
.src/main/proto/customer/domain/customer_domain.proto
----
include::example$java-protobuf-customer-registry-quickstart/src/main/proto/customer/domain/customer_domain.proto[tag=domain]
----

. Run `mvn compile` from the project root directory to generate source classes in which you add business logic.
+
[source,command line]
----
mvn compile
----

== Create command handlers

Command handlers, as the name suggests, handle incoming requests before persisting them.

. If it's not open already, open `src/main/java/customer/domain/Customer.java` for editing.

. Modify the `create` method by adding the logic to handle the command. The complete method should include the following:
+
[source, java]
.src/main/java/customer/domain/Customer.java
----
include::example$java-protobuf-customer-registry-quickstart/src/main/java/customer/domain/Customer.java[tag=create]
----
+
* The incoming message contains the request data from your client and the command handler updates the state of the customer.
* The `convertToDomain` methods convert the incoming request to your domain model.

. Modify the `getCustomer` method as follows to handle the `GetCustomerRequest` command:
+
[source, java, indent=0]
.src/main/java/customer/domain/Customer.java
----
include::example$java-protobuf-customer-registry-quickstart/src/main/java/customer/domain/Customer.java[tag=getCustomer]
----
+
* If that customer doesn't exist, processing the command fails.
* If the customer exists, the reply message contains the customer's information.
* The `convertToApi` method converts the state of the customer to a response message for your external API.
+

[NOTE]
====
The `src/main/java/customer/Main.java` file already contains the required code to start your service and register it with Kalix.
====

== Define the initial entity state

To give the domain model a starting point, the initial state for the entity needs to be defined.

. Implement the `emptyState` method by returning a default instance of the `CustomerState` class:
+
[source, java]
.src/main/java/customer/domain/Customer.java
----
include::example$java-protobuf-customer-registry-quickstart/src/main/java/customer/domain/Customer.java[tag=emptyState]
----

== Package and deploy your service

To build and publish the container image and then deploy the service, follow these steps:

. If you haven't done so yet, sign in to your Kalix account. If this is your first time using Kalix, this will let you register an account, https://docs.kalix.io/projects/create-project.html[create your first project], and set this project as the default.
+
[source,command line]
----
kalix auth login
----

. Use the `deploy` target to build the container image, publish it to the container registry as configured in the `pom.xml` file, and use the target `kalix:deploy` to automatically deploy the service to Kalix:
+
[source,command line]
----
mvn deploy kalix:deploy
----
include::partial$important-mvn-kalixdeploy.adoc[]

. You can https://docs.kalix.io/services/deploy-service.html#_verify_service_status[verify the status of the deployed service] using:
+
[source,command line]
----
kalix service list
----

== Invoke your service

Once the service has started successfully, you can https://docs.kalix.io/services/invoke-service.html#_testing_and_development[start a proxy locally] to access the service:

[source,command line]
----
kalix service proxy <service name> --grpcui
----

The `--grpcui` option also starts and opens a https://docs.kalix.io/services/invoke-service.html#_using_the_built_in_graphical_client[gRPC web UI] for exploring and invoking the service (available at http://127.0.0.1:8080/ui/).

Or you can use command line gRPC or HTTP clients, such as `grpcurl` or `curl`, to invoke the service through the proxy at `localhost:8080`, using plaintext connections.

A customer can be created using the `Create` method on `CustomerService`, in the gRPC web UI, or with `grpcurl`:

[source,command line]
----
grpcurl \
  -d '{
    "customer_id": "abc123",
    "email": "someone@example.com",
    "name": "Someone",
    "address": {
      "street": "123 Some Street",
      "city": "Somewhere"
    }
  }' \
  --plaintext localhost:8080 \
  customer.api.CustomerService/Create
----

The `GetCustomer` method can be used to retrieve this customer, in the gRPC web UI, or with `grpcurl`:

[source,command line]
----
grpcurl \
  -d '{"customer_id": "abc123"}' \
  --plaintext localhost:8080 \
  customer.api.CustomerService/GetCustomer
----

You can https://docs.kalix.io/services/invoke-service.html#_exposing_services_to_the_internet[expose the service to the internet]. A generated hostname will be returned from the expose command:

[source,command line]
----
kalix service expose <service name>
----

Try to call the exposed service with `grpcurl`:

[source,command line]
----
grpcurl \
  -d '{"customer_id": "abc123"}' \
  <generated hostname>:443 \
  customer.api.CustomerService/GetCustomer
----

== Next steps

* You can learn more about xref:java-protobuf:value-entity.adoc[Value Entities].
* Continue this example by xref:java-protobuf:quickstart/cr-value-entity-views-java.adoc[adding Views], which makes it possible to query the customer registry.
