When a Kalix service relies on a broker, it might be useful to use integration tests to assert that those boundaries work as intended. For such scenarios, you can either:

* Use TestKit's mocked topic:
** this offers a general API to inject messages into topics or read the messages written to another topic, regardless of the specific broker integration you have configured.
* Run an external broker instance:
** if you're interested in running your integration tests against a real instance, you need to provide the broker instance yourself by running it in a separate process in your local setup and make sure to disable the use of TestKit's test broker. Currently, **the only external broker supported in integration tests is Google PubSub Emulator.**

== TestKit Mocked Incoming Messages

Following up on the counter entity example used above, let's consider an example (composed by 2 Actions and 1 Event Sourced entity) as pictured below:

ifdef::todo[TODO: convert this diagram once we have a standard language for this]

image::java:eventing-testkit-sample.svg[]

In this example:

* commands are consumed from an external topic `event-commands` and forwarded to a Counter entity;
* the Counter entity is an Event Sourced Entity and has its events published to another topic `counter-events`.

To test this flow, we will take advantage of the TestKit to be able to push commands into the `event-commands` topic and check what messages are produced to topic `counter-events`.