include::ROOT:partial$include.adoc[]

A command can only act on one https://developer.lightbend.com/docs/akka-serverless/reference/glossary.html#component[_component_] at a time--the component that received the command. For certain use cases, you might want a different component to handle the command.  Rather than sending an immediate reply to a command, the receiving component can _forward_ the command to another component. In cases where you want other components to be aware that a component processed a command, you can emit an _effect_.

Handle forwarding and emit effects by wrapping the return value into a reply. The reply holds a regular return message or a forward to another component. Both can carry effects that notify other components.

The forwarding or effect can target any component within the service--whether it is an instance of the same or different type of component.

[IMPORTANT]
.Transactional limitations
====
It's important to note that forwarded commands, and commands emitted as side effects, are **non**-atomic--there is no guarantee that any one sent transactions will succeeded. If the service, or the data store, fails, while a forwarded command is executing, the triggering command responds with an error (so the client can retry), but there is no automatic rollback.

If partial updates will cause problems, do not use forwarding and effects to update multiple entities at once. In this case emit an event that is (eventually) processed by all subscribers. 

TIP: See the documentation on xref:topic-eventing.adoc[Publishing and subscribing].

====

== Forwarding control to another component

To forward a command return a forward reply that includes the call to invoke, and the message to invoke it with. The command is not forwarded until any state actions requested by the https://developer.lightbend.com/docs/akka-serverless/reference/glossary.html#command_handler[_command handler_] are successfully completed. It is the responsibility of the component receiving the forward to return a reply that matches the type of the original command. Forwards can be chained arbitrarily long.

.Use case: processing messages and triggering commands
****
An https://developer.lightbend.com/docs/akka-serverless/reference/glossary.html#action[_action_] might listen to a journal or an external topic and trigger commands on entities based on the incoming messages.
****
