include::ROOT:partial$include.adoc[]

Akka Serverless integrates with https://cloud.google.com/pubsub/docs/overview[Google Cloud Pub/Sub] to enable asynchronous messaging. Consumers of published messages are guaranteed to receive them at least once. This means that receivers must be able to handle duplicate messages. If you are new to the world of Pub/Sub, many online resources provide tips on handling duplicate messages.

This page describes how to subscribe to published events, but you also need to configure Google Cloud Pub/Sub access for your Akka Serverless project as explained in https://developer.lightbend.com/docs/akka-serverless/how-to/message-broker.html[How to configure a broker].

NOTE: It is your responsibility to create the topics in Google Cloud Pub/Sub before configuring publishers or subscribers.

== Subscribing to a topic's messages

To receive messages from a Pub/Sub topic, annotate a service method in the Protobuf service definition with the `(akkaserverless.method).eventing` annotation. Specify the topic name in the `in` section of the annotation:

[source,protobuf,indent=0]
----
include::java:example$java-eventing-shopping-cart/src/main/proto/cart/shopping_cart_analytics.proto[tag=subscribing]
----
<1> annotate the Protobuf rpc method with `(akkaserverless.method).eventing`
<2> use `in` and `topic` to subscribe to a topic

There is nothing specific required in the implementation of `ProcessAdded`. The implementation will in most cases be an Action and forward a converted message to a different component (eg. an Event Sourced Entity).

== Receiving JSON messages

Your Akka Serverless service may subscribe to topics that use messages in JSON format. The messages must have the `Content-Type` attribute stating `application/json`.

The Protobuf rpc method receiving these JSON messages must be set up to receive `Any`.

[source,protobuf,indent=0]
----
include::java:example$java-eventing-shopping-cart/src/main/proto/cart/shopping_cart_topic.proto[tag=receiving-json-messages]
----


The Java implementation of the method will follow the protobuf definintion and will receive `Any`. In the method implementation. You can then decode the message to the expected typed (eg: `TopicMessage`) using `JsonSupport.decodeJson`.

[source,java,indent=0]
----
include::java:example$java-eventing-shopping-cart/src/main/java/shopping/cart/api/ShoppingCartTopicServiceAction.java[tag=receiving-json-messages]
----

The parameter class needs to be annotated with Jackson Json annotations as usual. 

[source,java,indent=0]
----
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

public class TopicMessage {
  public final String operation;

  @JsonCreator
  public TopicMessage(@JsonProperty("operation") String operation) {
    this.operation = operation;
  }
}
----

For more detailed information on Json Serialization support in Akka Serverless, see xref:java:serialization.adoc[Handling Serialization].