/*
 * Copyright 2021 Lightbend Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.akkaserverless.javasdk.testkit.junit;

import akka.actor.ActorSystem;
import akka.grpc.GrpcClientSettings;
import akka.stream.Materializer;
import com.akkaserverless.javasdk.AkkaServerless;
import com.akkaserverless.javasdk.testkit.AkkaServerlessTestKit;
import org.junit.rules.ExternalResource;

/**
 * A JUnit external resource for {@link AkkaServerlessTestKit}, which automatically manages the
 * lifecycle of the testkit. The testkit will be automatically stopped when the test completes or
 * fails.
 *
 * <p><b>Note</b>: JUnit is not provided as a transitive dependency of the Java SDK testkit module
 * but must be added explicitly to your project.
 */
public final class AkkaServerlessTestKitResource extends ExternalResource {

  private final AkkaServerlessTestKit testkit;

  public AkkaServerlessTestKitResource(AkkaServerless akkaServerless) {
    this(akkaServerless, AkkaServerlessTestKit.Settings.DEFAULT);
  }

  public AkkaServerlessTestKitResource(
      AkkaServerless akkaServerless, AkkaServerlessTestKit.Settings settings) {
    this.testkit = new AkkaServerlessTestKit(akkaServerless, settings);
  }

  @Override
  protected void before() {
    testkit.start();
  }

  /**
   * Get the host name/IP address where the Akka Serverless service is available. This is relevant
   * in certain Continuous Integration environments.
   *
   * @return Akka Serverless host
   */
  public String getHost() {
    return testkit.getHost();
  }

  /**
   * Get the local port where the Akka Serverless service is available.
   *
   * @return local Akka Serverless port
   */
  public int getPort() {
    return testkit.getPort();
  }

  /**
   * Get an Akka gRPC client for the given service name. The same client instance is shared for the
   * test. The lifecycle of the client is managed by the SDK and it should not be stopped by user
   * code.
   *
   * @param <T> The "service" interface generated for the service by Akka gRPC
   * @param clientClass The class of a gRPC service generated by Akka gRPC
   * @param service The name of the service to connect to, either a name of another Akka Serverless
   *     service or an external service where connection details are configured under
   *     `akka.grpc.client.[service-name]` in `application.conf`.
   */
  public <T> T getGrpcClient(Class<T> clientClass, String service) {
    return testkit.getGrpcClient(clientClass, service);
  }

  /**
   * An Akka Stream materializer to use for running streams. Needed for example in a command handler
   * which accepts streaming elements but returns a single async reply once all streamed elements
   * has been consumed.
   */
  public Materializer getMaterializer() {
    return testkit.getMaterializer();
  }

  /**
   * Get an {@link ActorSystem} for creating Akka HTTP clients.
   *
   * @return test actor system
   */
  public ActorSystem getActorSystem() {
    return testkit.getActorSystem();
  }

  /**
   * Get {@link GrpcClientSettings} for creating Akka gRPC clients.
   *
   * @return test gRPC client settings
   * @deprecated Use <code>getGrpcClient</code> instead.
   */
  @Deprecated(since = "0.8.1", forRemoval = true)
  public GrpcClientSettings getGrpcClientSettings() {
    return testkit.getGrpcClientSettings();
  }

  @Override
  protected void after() {
    testkit.stop();
  }
}
