/* This code was generated by Kalix tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package customer.view

import kalix.scalasdk.view.View.UpdateEffect
import kalix.scalasdk.view.ViewContext
import customer.domain.CustomerState

class CustomerByNameView(context: ViewContext) extends AbstractCustomerByNameView {



}
