= Quickstart: Customer Registry in Scala

include::ROOT:partial$include.adoc[]
include::java:partial$attributes.adoc[]

Learn how to create a customer registry in Scala, package it into a container, and run it on Akka Serverless.

== Before you begin

* Install the https://developer.lightbend.com/docs/akka-serverless/akkasls/install-akkasls.html[Akka Serverless CLI, window="new-doc"] if you want to deploy from a terminal window.
* For this quickstart, you'll also need
** https://docs.docker.com/engine/install[Docker {minimum_docker_version} or higher, window="new"]
** Java {java-version} or higher
** https://www.scala-sbt.org/download.html[sbt 1.4 or higher, window="new"]
** https://github.com/fullstorydev/grpcurl#installation[`grpcurl`, window="new"]

[NOTE]
====
If you want to bypass writing code and jump straight to the deployment:

. Download the source code using the Akka Serverless CLI: 
`akkasls quickstart download customer-registry-scala`

. Skip to <<Package and deploy your service>>.
====

== Writing the Customer Registry

. From the command line, create a directory for your project.
+
[source,command line]
----
mkdir customerregistry
----

. Change into the project directory.
+
[source,command line]
----
cd customerregistry
----

. Download the `build.sbt` file
+
[source,command line]
----
curl -OL https://raw.githubusercontent.com/lightbend/akkaserverless-java-sdk/main/samples/scala-customer-registry-quickstart/build.sbt
----

. Create the sbt `project` directory
+
[source,command line]
----
mkdir project
----

. Download the `plugins.sbt`
[source,command line]
----
curl -L https://raw.githubusercontent.com/lightbend/akkaserverless-java-sdk/main/samples/scala-customer-registry-quickstart/project/plugins.sbt -o project/plugins.sbt
----


== Define the external API

The Customer Registry service will create or retrieve a customer, including their email, phone number and mailing address. The `customer_api.proto` will contain the external API your clients will invoke.

. In your project, create two directories for you protobuf files, `src/main/proto/customer/domain` and `src/main/proto/customer/api`.
[.tabset]
Linux or macOS::
+
--
[source,command line]
----
mkdir -p ./src/main/proto/customer/api
mkdir -p ./src/main/proto/customer/domain
----
--
Windows 10+::
+
--
[source,command line]
----
mkdir src/main/proto/customer/api
mkdir src/main/proto/customer/domain
----
--

. Create a `customer_api.proto` file and save it in the `src/main/proto/customer/api` directory.

. Add declarations for:
+
* The protobuf syntax version, `proto3`.
* The package name, `customer.api`.
* Import `google/protobuf/empty.proto`.
+
[source,proto,indent=0]
.src/main/proto/customer/api/customer_api.proto
----
include::example$scala-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto[tag=declarations]
----

. Add the service endpoint. The service endpoint is annotated with `akkaserverless.codegen` indicating we want to generate a Value Entity for this service.
+
[source,proto,indent=0]
.src/main/proto/customer/api/customer_api.proto
----
include::example$scala-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto[tag=service]
----

. Add messages to define the fields that comprise a `Customer` object (and its compound `Address`)
+
[source,proto,indent=0]
.src/main/proto/customer/api/customer_api.proto
----
include::example$scala-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto[tag=messages]
----

. Add the message that will identify which customer to retrieve for the `GetCustomer` message:
+
[source,proto,indent=0]
.src/main/proto/customer/api/customer_api.proto
----
include::example$scala-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto[tag=method-messages]
----


== Define the domain model

The `customer_domain.proto` contains all the internal data objects (https://developer.lightbend.com/docs/akka-serverless/reference/glossary.html#entity[Entities, window="new"]). The https://developer.lightbend.com/docs/akka-serverless/reference/glossary.html#value_entity[Value Entity, window="new"]  in this quickstart is a Key/Value store that stores only the latest updates.

. Create a `customer_domain.proto` file and save it in the `src/main/proto/customer/domain` directory.

. Add declarations for the proto syntax and domain package.
+
[source,proto,indent=0]
.src/main/proto/customer/domain/customer_domain.proto
----
include::example$scala-customer-registry-quickstart/src/main/proto/customer/domain/customer_domain.proto[tag=declarations]
----

. Add the `CustomerState` message with fields for entity data, and the `Address` message that defines the compound address:
+
[source,proto,indent=0]
.src/main/proto/customer/domain/customer_domain.proto
----
include::example$scala-customer-registry-quickstart/src/main/proto/customer/domain/customer_domain.proto[tag=domain]
----

. Run `sbt compile` from the project root directory to generate source classes in which you add business logic.
+
----
sbt compile
----

== Create command handlers

Command handlers, as the name suggests, handle incoming requests before persisting them.

. If it's not open already, open `src/main/scala/customer/domain/Customer.scala` for editing.

. Modify the `create` method by adding the logic to handle the command. The complete method should include the following:
+
[source, scala]
.src/main/scala/customer/domain/Customer.scala
----
include::example$scala-customer-registry-quickstart/src/main/scala/customer/domain/Customer.scala[tag=create]
----
+
* The incoming message contains the request data from your client and the command handler updates the state of the customer.
* The `convertToDomain` and `convertAddressToDomain` methods convert the incoming request to your domain model.

. Modify the `getCustomer` method as follows to handle the `GetCustomerRequest` command:
+
[source, scala, indent=0]
.src/main/scala/customer/domain/Customer.scala
----
include::example$scala-customer-registry-quickstart/src/main/scala/customer/domain/Customer.scala[tag=getCustomer]
----
+
* If that customer doesn't exist, processing the command fails.
* If the customer exists, the reply message contains the customer's information.
* The `convertToApi` method converts the state of the customer to a response message for your external API.
+

[NOTE]
====
The `src/main/scala/customer/Main.scala` file already contains the required code to start your service and register it with Akka Serverless.
====

== Package and deploy your service

To compile, build the container image, and publish it to your container registry, follow these steps

. From the root project directory, compile the source code using sbt:
+
[source, command line]
----
sbt compile
----

. Use the `docker:publish` task to build the container image and publish it to your container registry. At the end of this command sbt will show you the container image URL you'll need in the next part of this quickstart.
+
[source, command line]
----
sbt docker:publish -Ddocker.username=[your-docker-hub-username]
----

. If you haven't yet, sign in to akkasls with `akkasls auth login`. If this is your first time using Akka Serverless, this will let you register an account, create your first project and set it as the default.
. Deploy your project with `akkasls services deploy MY-SERVICE MY-IMAGE`

== Invoke your service

Once the service has been successfully started (this may take a while),
you can create an ad-hoc proxy to call it from your local machine:

```
$ akkasls services proxy my-service
Listening on 127.0.0.1:8080
```

You can now invoke it, for example with `grpcurl`:

```
$ grpcurl --plaintext \
    -d "{\"cart_id\":\"42\"}" \
    localhost:8080 \
    com.example.shoppingcart.ShoppingCartService/GetCart
{

}
$ grpcurl --plaintext \
    -d "{\"cart_id\":\"42\",\"product_id\":\"37\",\"name\":\"apples\",\"quantity\":\"5\"}" \
    localhost:8080 \
    com.example.shoppingcart.ShoppingCartService/AddItem
$ grpcurl --plaintext \
    -d "{\"cart_id\":\"42\"}" \
    localhost:8080 \
    com.example.shoppingcart.ShoppingCartService/GetCart
{
    "items": [
    {
      "productId": "37",
      "name": "apples",
      "quantity": 5
    }
  ]
}
```

Or expose it to the Internet:

```
$ akkasls service expose my-service
Service 'samples-js-value-entity-shopping-cart' was successfully exposed at: delicate-union-3021.us-east1.akkaserverless.app
```
