= Customer Registry with Views in Java

include::ROOT:partial$include.adoc[]
include::java:partial$attributes.adoc[]

In this section, you will learn how to create a customer registry with the Java SDK, package it into a container, and run it on Kalix.

include::page$quickstart/before-you-begin.adoc[]

[NOTE]
====
If you want to bypass writing code and jump straight to the deployment:

. Download the source code using the Kalix CLI:
`kalix quickstart download customer-registry-views-java`

. Skip to <<Package and deploy your service>>.
====

== Start from the Customer Registry Entity

Start by downloading the  xref:java:quickstart/cr-value-entity-java.adoc[Customer Registry sample] source code using the Kalix CLI:

[source,command line]
----
kalix quickstart download customer-registry-java
----

You can access the `Customer` https://docs.kalix.io/reference/glossary.html#entity[Entity] with its https://docs.kalix.io/reference/glossary.html#component_id[id]. In this guide we will describe how to retrieve customers by email or name instead.

== Define the CustomerByEmail View

Create a class named `CustomerByEmailView` in package `customer.view`.

You implement a View by extending `kalix.javasdk.view.View` and subscribing to changes from an entity. You specify how to query it by providing a method annotated with `@Query`, which is then made accessible via REST annotations.

.src/main/java/customer/view/CustomerByEmailView.java
[source,java]
----
include::example$java-spring-customer-registry-views-quickstart/src/main/java/customer/view/CustomerByEmailView.java[tags=class]
----
<1> Defining view ID.
<2> Defining table name.
<3> Subscribing to `CustomerEntity`.
<4> Extending from `View`.
<5> Defining endpoint.
<6> Defining the query.
<7> Note that no return is needed. This method is used to declare in Kalix how the query index should be configured. The query execution is carried by Kalix and therefore the method can simply return `null`.

NOTE: In this sample, we use the internal `domain.Customer` as the state of the view. This is convenient since it allows automatic updates of the view without any logic but has the drawback that it implicitly makes the `domain.Customer` type a part of the public service API. Transforming the state to another type than the incoming update will be illustrated in the `CustomersByName` example.

include::page$quickstart/package-and-deploy.adoc[]

include::page$quickstart/create-customer.adoc[]

The customer can also be found through the `CustomerByEmail` view service.

[source,command line]
----
curl localhost:8080/customer/by_email/someone@example.com
----

include::page$quickstart/expose-service.adoc[]

Try to call the exposed service with `curl`:

[source,command line]
----
curl https://<generated hostname>/customer/abc123
----

== Define the CustomerByName View


Create a class named `CustomersByNameView` in package `customer.view`.

This time, we won't use `domain.Customer` as the state of the view. Instead, we introduce a new class record named `CustomerSummary` and we will transform the incoming `Customer` state change to `CustomerSummary`

.src/main/java/customer/view/CustomersByNameView.java
[source,java]
----
include::example$java-spring-customer-registry-views-quickstart/src/main/java/customer/view/CustomersByNameView.java[tags=class]
----
<1> View state type is defined as `CustomerSummary`.
<2> For convenience, `CustomerSummary` is defined as an inner class record.
<3> The Query method return a `Flux<CustomerSummary>`, meaning that the results will be streamed to the client.
<4> The `onUpdate` method will receive state changes from the `CustomerEntity` and transform it to `CustomerSummary`. Note that the `@Subscribe.ValueEntity` is now added at method level performing the transformation. In the previous example, we didn't transform the type and therefore the subscription was at the class level.

== Deploy the updated service

. Deploy the updated service by repeating the steps in <<deploy>>.

== Invoke the CustomerByName

. Similar to the steps in <<invoke>>.
. Create several customers with same name.
. Use the new `/customers/by_name/\{customer_name}` endpoint instead of `/customer/by_email/\{email}` and then you should see multiple results from `CustomerSummary` for customers with the same.

== Next steps

* You can read more about xref:java:views.adoc[Views].
