= Quickstart: Customer Registry in Java

include::java:partial$attributes.adoc[]

Learn how to create a customer registry in Java, package it into a container, and run it on Akka Serverless.

== Before you begin

* If you're new to Akka Serverless, {console}[create an account, window="console"] so you can try out Akka Serverless for free.
* You'll also need to install the xref:akkasls:install-akkasls.adoc[Akka Serverless CLI, window="new-doc"] if you want to deploy from a terminal window.
* For this quickstart, you'll also need
** https://docs.docker.com/engine/install[Docker {minimum_docker_version} or higher, window="new"]
** Java {java-version} or higher
** https://maven.apache.org/download.cgi[Maven 3.x or higher, window="new"]
** https://github.com/fullstorydev/grpcurl#installation[`grpcurl`, window="new"]

[NOTE]
====
If you want to bypass writing code and jump straight to the deployment:

. Download the source code using the Akka Serverless CLI: 
`akkasls quickstart download customer-registry-java`

. Skip to <<Package and deploy your service>>.
====

== Writing the Customer Registry

. From the command line, create a directory for your project.
+
[source,command line]
----
mkdir customerregistry
----

. Change into the project directory.
+
[source,command line]
----
cd customerregistry
----

. Download the `pom.xml` file
+
[source,command line]
----
curl -OL https://raw.githubusercontent.com/lightbend/akkaserverless-java-sdk/main/samples/java-customer-registry-quickstart/pom.xml
----

. Update the `dockerImage` property (line 13 of the `pom.xml` file) with your container registry name.

== Define the external API

The Customer Registry service will create or retrieve a customer, including their email, phone number and mailing address. The `customer_api.proto` will contain the external API your clients will invoke.

. In your project, create two directories for you protobuf files, `src/main/proto/customer/domain` and `src/main/proto/customer/api`.
[.tabset]
Linux or macOS::
+
--
[source,command line]
----
mkdir -p ./src/main/proto/customer/api
mkdir -p ./src/main/proto/customer/domain
----
--
Windows 10+::
+
--
[source,command line]
----
mkdir src/main/proto/customer/api
mkdir src/main/proto/customer/domain
----
--

. Create a `customer_api.proto` file and save it in the `src/main/proto/customer/api` directory.

. Add declarations for:
+
* The protobuf syntax version, `proto3`.
* The package name, `customer.api`.
* The required Java outer classname, `CustomerAPI`. Messages defined in this file will be generated as inner classes.
* Import `google/protobuf/empty.proto` and Akka Serverless `akkaserverless/annotations.proto`.
+
[source,proto,indent=0]
.src/main/proto/customer/api/customer_api.proto
----
include::java:example$java-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto[tag=declarations]
----

. Add the service endpoint
+
[source,proto,indent=0]
.src/main/proto/customer/api/customer_api.proto
----
include::java:example$java-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto[tag=service]
----

. Add messages to define the fields that comprise a `Customer` object (and its compound `Address`)
+
[source,proto,indent=0]
.src/main/proto/customer/api/customer_api.proto
----
include::java:example$java-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto[tag=messages]
----

. Add the message that will identify which customer to retrieve for the `GetCustomer` message:
+
[source,proto,indent=0]
.src/main/proto/customer/api/customer_api.proto
----
include::java:example$java-customer-registry-quickstart/src/main/proto/customer/api/customer_api.proto[tag=method-messages]
----

== Define the domain model

The `customer_domain.proto` contains all the internal data objects (xref:reference:glossary.adoc#entity[Entities, window="new"]). The xref:reference:glossary.adoc#value_entity[Value Entity, window="new"] in this quickstart is a Key/Value store that stores only the latest updates.

. Create a `customer_domain.proto` file and save it in the `src/main/proto/customer/domain` directory.

. Add declarations for the proto syntax, Akka Serverless annotations, and domain model:attribute: value
+
* The package name, `customer.domain`.
* The Java outer classname, `CustomerDomain`.
+
[source,proto,indent=0]
.src/main/proto/customer/domain/customer_domain.proto
----
include::java:example$java-customer-registry-quickstart/src/main/proto/customer/domain/customer_domain.proto[tag=declarations]
----

. Add the option that the Maven plugin will use to generate the `Customer` Value entity, which will be of type `customers` and whose state will be defined in a `CustomerState` message:
+
[source,proto,indent=0]
.src/main/proto/customer/domain/customer_domain.proto
----
include::java:example$java-customer-registry-quickstart/src/main/proto/customer/domain/customer_domain.proto[tag=entity]
----

. Add the `CustomerState` message with fields for entity data, and the `Address` message that defines the compound address:
+
[source,proto,indent=0]
.src/main/proto/customer/domain/customer_domain.proto
----
include::java:example$java-customer-registry-quickstart/src/main/proto/customer/domain/customer_domain.proto[tag=domain]
----

. Run `mvn compile` from the project root directory to generate source classes in which you add business logic.
+
----
mvn compile
----

== Create command handlers

Command handlers, as the name suggests, handle incoming requests before persisting them.

. If it's not open already, open `src/main/java/customer/domain/Customer.java` for editing.

. Modify the `create` method by adding the logic to handle the command. The complete method should include the following:
+
[source, java]
.src/main/java/customer/domain/Customer.java
----
include::java:example$java-customer-registry-quickstart/src/main/java/customer/domain/Customer.java[tag=create]
----
+
* The incoming message contains the request data from your client and the command handler updates the state of the customer.
* The `convertToDomain` and `convertAddressToDomain` methods convert the incoming request to your domain model.

. Modify the `getCustomer` method as follows to handle the `GetCustomerRequest` command:
+
[source, java, indent=0]
.src/main/java/customer/domain/Customer.java
----
include::java:example$java-customer-registry-quickstart/src/main/java/customer/domain/Customer.java[tag=getCustomer]
----
+
* If that customer doesn't exist, processing the command fails.
* If the customer exists, the reply message contains the customer's information.
* The `convertToApi` method converts the state of the customer to a response message for your external API.
+

[NOTE]
====
The `src/main/java/customer/Main.java` file already contains the required code to start your service and register it with Akka Serverless.
====

== Package and deploy your service

To compile, build the container image, and publish it to your container registry, follow these steps

. From the root project directory, compile the source code using Maven:
+
[source, command line]
----
mvn compile
----

. Use the `deploy` target to build the container image and publish it to your container registry. At the end of this command Maven will show you the container image URL you'll need in the next part of this quickstart.
+
[source, command line]
----
mvn deploy
----

. Sign in to your Akka Serverless account at: {console}
. If you do not have a project, click *Add Project* to create one, otherwise choose the project you want to deploy your service to.
. On the project dashboard click the "+" next to *services* to start the deployment wizard
. Choose a name for your service and click *Next*
. Enter the container image URL from the above step and click *Next*
. Click *Next* (no environment variables are needed for these samples)
. Check both _Add a route to this service_ and _Enable CORS_ and click *Next*
. Click *Finish* to start the deployment
. Click *Go to Service* to see your newly deployed service

== Invoke your service

Now that you have deployed your service, the next step is to invoke it using gRPCurl

. From the "_Service Explorer_" click on the method you want to invoke
. Click on "_gRPCurl_"
. In the bottom section of the dialog, fill in the values you want to send to your service
. In the top section of the dialog, click the "_Copy to clipboard_" button
. Open a new command line and paste the content you just copied

== Next steps

* You can learn more about Value Entities in the xref:java:value-entity.adoc[reference documentation].
* Continue this example by xref:cr-value-entity-views-java.adoc[adding Views], which makes it possible to query the customer registry.
