= Customer Registry in Java
:page-aliases: spring:quickstart/cr-value-entity-spring.adoc

include::ROOT:partial$include.adoc[]
include::java:partial$attributes.adoc[]

In this sample, you will learn how to create a customer registry with the Java SDK, package it into a container, and run it on Kalix.

== In this sample you will learn:

* How to add additional functionality, allowing customers to be queried by name and email.
* How to package the customer registry into a container.
* How to deploy and run the customer registry on Kalix.

include::page$quickstart/before-you-begin.adoc[]

[NOTE]
====
If you want to bypass writing code and jump straight to the deployment:

. Download the source code using the Kalix CLI:
`kalix quickstart download customer-registry-java`

. Skip to <<Package and deploy your service>>.
====

include::partial$maven-archetype.adoc[]

== Customer Registry Service

The service contains only one Value Entity that exposes the operation to mutate a Customer model. The entity itself exposes service endpoints and eventually encapsulates some basic validation. The incoming commands/request are then applied to the model and the entity instructs Kalix, through the `Effect` API what needs to be done next.

=== Define the domain model

First, define the domain classes in package `customer.domain`.

[source,java,indent=0]
.src/main/java/customer/domain/Customer.java
----
include::example$java-spring-customer-registry-quickstart/src/main/java/customer/domain/Customer.java[]
----
<1> Define a Java record `email`, `name` and `Address`.
<2> Defined methods implementing the mutations. Note that both methods return a new version of the Customer record and only modify one field.

Finally, the `Address` record.

[source,java,indent=0]
.src/main/java/customer/domain/Address.java
----
include::example$java-spring-customer-registry-quickstart/src/main/java/customer/domain/Address.java[]
----

=== Define the external API

The `Customer` API is defined by the `CustomerEntity`.

Create a class named `CustomerEntity` in package `customer.api`.

[source,java,indent=0]
.src/main/java/customer/api/CustomerEntity.java
----
include::example$java-spring-customer-registry-quickstart/src/main/java/customer/api/CustomerEntity.java[tag=customer]
----
<1> Each Entity needs a unique logical type name. This must be unique per Kalix service.
<2> The entity needs to be address by a unique identifier. The `@Id` declares the name of the path variable that Kalix should use as unique identifier.
<3> The `@RequestMapping` defines the base path to access the entity. Note that the `\{customer_id\}` matches the value of `@Id`.
<4> `CustomerEntity` must inherit from `kalix.javasdk.valueentity.ValueEntity`.
<5> Each API method must be exposed as a REST endpoint using Spring's REST annotations.
<6> The implementation instructs Kalix to persist the state `customer`.
<7> After persisting, Kalix is instructed to return the String 'Ok'.

include::page$quickstart/package-and-deploy.adoc[]
include::page$quickstart/create-customer.adoc[]
include::page$quickstart/expose-service.adoc[]

Try to call the exposed service with `curl`:

[source,command line]
----
curl https://<generated hostname>/customer/abc123
----

== Next steps

* You can learn more about xref:java:value-entity.adoc[Value Entities].
* Continue this example by xref:java:quickstart/cr-value-entity-views-java.adoc[adding Views], which makes it possible to query the customer registry.
