
== Package and deploy your service

To build and publish the container image and then deploy the service, follow these steps:

. If you haven't done so yet, sign in to your Kalix account. If this is your first time using Kalix, this will let you register an account, https://docs.kalix.io/projects/create-project.html[create your first project], and set this project as the default.
+
[source,command line]
----
kalix auth login
----

. Use the `deploy` target to build the container image, publish it to the container registry as configured in the `pom.xml` file, and the target `kalix:deploy` to automatically deploy the service to Kalix:
+
[source,command line]
----
mvn deploy kalix:deploy
----
include::partial$important-mvn-kalixdeploy.adoc[]

. You can https://docs.kalix.io/services/deploy-service.html#_verify_service_status[verify the status of the deployed service] using:
+
[source,command line]
----
kalix service list
----

[#invoke]
== Invoke your service

Once the service has started successfully, you can https://docs.kalix.io/services/invoke-service.html#_testing_and_development[start a proxy locally] to access the service:

[source,command line]
----
kalix service proxy <service name>
----

You can use command line HTTP clients, such as `curl` or `httpie`, to invoke the service through the proxy at `localhost:8080`, using plaintext connections.
