= Shopping Cart in Java

include::ROOT:partial$include.adoc[]
include::java:partial$attributes.adoc[]

Learn how to create a shopping cart in Java, package it into a container, and run it on Kalix.

include::page$quickstart/before-you-begin.adoc[]

[NOTE]
====
If you want to bypass writing code and jump straight to the deployment:

. Download the source code using the Kalix CLI:
`kalix quickstart download shopping-cart-java`

. Skip to <<Package and deploy your service>>.
====


include::partial$maven-archetype.adoc[]

== Shopping Cart Service

Through our "Shopping Cart" Event Sourced Entity we expect to manage our cart, adding and removing items as we please. Being event-sourced means it will represent changes to state as a series of domain events. So let’s have a look at what kind of model we expect to store and the events our entity might generate.

=== Define the domain model

First, define the domain class `ShoppingCart`, its domain events  in package `shoppingcart.domain` and some basic business logic.

[source,java,indent=0]
.src/main/java/shoppingcart/domain/ShoppingCart.java
----
include::example$java-spring-shopping-cart-quickstart/src/main/java/shoppingcart/domain/ShoppingCart.java[]
----

=== Define the external API

The `Shopping Cart` API is defined by the `ShoppingCartEntity`.

Create a class named `ShoppingCartEntity` in package `shoppingcart.api`.


[source,java,indent=0]
.src/main/java/shoppingcart/api/ShoppingCartEntity.java
----
include::example$java-spring-shopping-cart-quickstart/src/main/java/shoppingcart/api/ShoppingCartEntity.java[tag=class]
----
<1> Each Entity needs a unique logical type name. This must be unique per Kalix service.
<2> The entity needs to be addressed by a unique identifier. The `@Id` declares the name of the path variable that Kalix should use as unique identifier.
<3> The `@RequestMapping` defines the base path to access the entity. Note that the `\{cartId\}` matches the value of `@Id`.
<4> `ShoppingCartEntity` must inherit from `kalix.javasdk.eventsourcedentity.EventSourcedEntity`.
<5> The `emptyState` method returns the initial state of the shopping cart.
<6> External API methods are be exposed as a REST endpoint using Spring's REST annotations.
<7> API methods receive input and validate it. When applicable, an event is emitted.
<8> Each emitted event must have a corresponding `@EventHandler` to update the state of the shopping cart.


include::page$quickstart/package-and-deploy.adoc[]


Items can be added to a shopping cart using the `/cart/\{cartId}/add` endpoint on the ShoppingCart service:

[source,command line]
----
curl localhost:8080/cart/123/add \
  --header "Content-Type: application/json" \
  -XPOST \
  --data '{
    "productId": "kalix-tshirt",
    "name": "Kalix Tshirt",
    "quantity": 5
  }'
----

The state of the cart can be retrieved with `/cart/\{cartId}`.

[source, command line]
----
curl localhost:8080/cart/123
----

And finally, you can check out the cart with `/cart/\{cartId}/checkout`.

[source, command line]
----
curl -XPOST localhost:8080/cart/123/checkout
----

include::page$quickstart/expose-service.adoc[]

== Next steps

* You can learn more about xref:java-protobuf:event-sourced-entities.adoc[Event Sourced Entities].
