/*
 * Copyright 2021 Lightbend Inc.
 */

package com.akkaserverless.javasdk.replicatedentity;

import com.akkaserverless.javasdk.ClientActionContext;
import com.akkaserverless.javasdk.EffectContext;
import com.akkaserverless.javasdk.MetadataContext;

/**
 * Context for handling a command.
 *
 * <p>This may be passed to any {@link CommandHandler} annotated element.
 */
public interface CommandContext
    extends ReplicatedEntityContext,
        ReplicatedDataFactory,
        EffectContext,
        ClientActionContext,
        MetadataContext {
  /**
   * The id of the command. This is an internal ID generated by the proxy, and is unique to a given
   * entity stream. It may be used for debugging purposes.
   *
   * @return The ID of the command.
   */
  long commandId();

  /**
   * The name of the command.
   *
   * <p>Corresponds to the name of the rpc call in the protobuf definition.
   *
   * @return The name of the command.
   */
  String commandName();

  /**
   * Delete the replicated entity.
   *
   * <p>When a replicated entity is deleted, it may not be created again. Additionally, replicated
   * entity deletion results in tombstones that get accumulated for the life of the cluster. If you
   * expect to delete replicated entities frequently, it's recommended that you store them in a
   * single or sharded {@link ORMap}, rather than individual replicated entities.
   */
  void delete();
}
