/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */

package com.example.actions;

import com.akkaserverless.javasdk.action.ActionCreationContext;
import com.example.domain.CounterDomain;
import com.google.protobuf.Empty;

/** An action. */
public class CounterStateSubscriptionAction extends AbstractCounterStateSubscriptionAction {

  public CounterStateSubscriptionAction(ActionCreationContext creationContext) {}

  /** Handler for "OnUpdateState". */
  @Override
  public Effect<Empty> onUpdateState(CounterDomain.CounterState counterState) {
    return effects().noReply();
  }
}