/*
 * Copyright (C) 2021-2024 Lightbend Inc. <https://www.lightbend.com>
 */

package kalix.javasdk.replicatedentity;

import kalix.javasdk.MetadataContext;

/** Command context for Replicated Entity. */
public interface CommandContext extends ReplicatedEntityContext, MetadataContext {
  /**
   * The id of the command. This is an internal ID generated by the proxy, and is unique to a given
   * entity stream. It may be used for debugging purposes.
   *
   * @return The ID of the command.
   */
  long commandId();

  /**
   * The name of the command.
   *
   * <p>Corresponds to the name of the rpc call in the protobuf definition.
   *
   * @return The name of the command.
   */
  String commandName();
}
