addSbtPlugin("com.dwijnand"      % "sbt-dynver"          % "4.1.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.6.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("org.wartremover"   % "sbt-wartremover"     % "2.4.13")
addSbtPlugin("com.codecommit"    % "sbt-github-packages" % "0.5.2")
addSbtPlugin("au.com.onegeek"    % "sbt-dotenv"          % "2.1.204")
