/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */

package com.example;

import kalix.javasdk.AkkaServerless;
import kalix.javasdk.valueentity.ReflectiveValueEntityProvider;
import com.example.domain.Counter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public final class Main {

  private static final Logger LOG = LoggerFactory.getLogger(Main.class);

  public static AkkaServerless createAkkaServerless() {
    AkkaServerless akkaServerless = new AkkaServerless();
    akkaServerless
        .register(ReflectiveValueEntityProvider.of("counter", Counter.class, __ ->  new Counter()));

    return akkaServerless;
  }

  public static void main(String[] args) throws Exception {
    LOG.info("starting the Akka Serverless service");
    createAkkaServerless().start();
  }
}
