name: Setup Akka resolver
description: Adds Akka resolver globally for sbt and Maven
runs:
  using: "composite"
  steps:
    - name: Add Akka resolver for sbt
      shell: bash
      run: |
        mkdir -p ~/.sbt/1.0
        echo 'resolvers += "Akka library repository".at("https://repo.akka.io/maven/github_actions")' >> ~/.sbt/1.0/resolvers.sbt

    - name: Add Akka Resolver to Scripted Tests
      shell: bash
      run: |
        TESTS_DIR="$GITHUB_WORKSPACE/sbt-plugin/src/sbt-test/sbt-kalix"
        RESOLVER_LINE='resolvers += "Akka library repository" at "https://repo.akka.io/maven/github_actions"'
        echo "Current Working Directory (CWD): $(pwd)"
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "--- Files at Root ($GITHUB_WORKSPACE) ---"
        # This will list the top-level files/folders
        ls -F $GITHUB_WORKSPACE
        echo "----------------------------------------"
        # Check if the main directory exists
        if [ ! -d "$TESTS_DIR" ]; then
          echo "Tests directory not found: $TESTS_DIR"
          exit 1
        fi
    
        # Iterate over all subdirectories (individual test cases)
        for TEST_CASE in "$TESTS_DIR"/*/; do
          if [ -d "$TEST_CASE" ]; then
            echo "Processing test case: ${TEST_CASE}"
    
            # 1. Define the target directory path
            TARGET_DIR="${TEST_CASE}global"
    
            # 2. Create the target directory structure if it doesn't exist
            mkdir -p "$TARGET_DIR"
    
            # 3. Define the full path to the resolvers file
            RESOLVERS_FILE="${TARGET_DIR}/resolvers.sbt"
    
            # 4. Write the resolver configuration to the file
            echo "$RESOLVER_LINE" > "$RESOLVERS_FILE"
            echo "Created ${RESOLVERS_FILE}"
          fi
        done

    - name: Add Akka resolver for Maven
      shell: bash
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<'EOF'
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <mirrors>
            <mirror>
              <id>akka-repo-redirect</id>
              <mirrorOf>akka-repository</mirrorOf> 
              <url>https://repo.akka.io/maven/github_actions</url>
            </mirror>
            <mirror>
              <mirrorOf>external:http:*</mirrorOf>
              <name>Pseudo repository to mirror external repositories initially using HTTP.</name>
              <url>http://0.0.0.0/</url>
              <blocked>true</blocked>
              <id>maven-default-http-blocker</id>
            </mirror>
          </mirrors>
          
          <profiles>
            <profile>
              <id>akka-repo</id>
              <repositories>
                <repository>
                  <id>akka-repository</id>
                  <url>https://repo.akka.io/maven/github_actions</url>
                </repository>
              </repositories>
            </profile>
          </profiles>

          <activeProfiles>
            <activeProfile>akka-repo</activeProfile>
          </activeProfiles>
        </settings>
        EOF
