/* This code was generated by Kalix tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package customer.action

import kalix.scalasdk.action.Action
import kalix.scalasdk.action.ActionCreationContext
import com.google.protobuf.empty.Empty
import customer.api.Customer

class CustomerActionImpl(creationContext: ActionCreationContext) extends AbstractCustomerAction {

  override def create(customer: Customer): Action.Effect[Empty] = {
    effects.forward(components.customerValueEntity.create(customer))
  }
}