/*
 * Copyright 2021 Lightbend Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package shopping.cart;

import com.akkaserverless.javasdk.view.UpdateHandler;
import com.akkaserverless.javasdk.view.View;
import com.akkaserverless.javasdk.view.ViewBase;
import shopping.cart.domain.ShoppingCartDomain;
import shopping.cart.view.ShoppingCartViewModel;

// FIXME to be generated by codegen
// FIXME to be called directly rather than through annotation+reflection
@View
public abstract class AbstractShoppingCartView extends ViewBase<ShoppingCartViewModel.CartViewState> {

  @UpdateHandler
  public abstract ViewBase.UpdateEffect<ShoppingCartViewModel.CartViewState> processItemAdded(
      ShoppingCartViewModel.CartViewState state,
      ShoppingCartDomain.ItemAdded itemAdded);

  @UpdateHandler
  public abstract UpdateEffect<ShoppingCartViewModel.CartViewState> processItemRemoved(
      ShoppingCartViewModel.CartViewState state,
      ShoppingCartDomain.ItemRemoved itemRemoved);

  @UpdateHandler
  public abstract UpdateEffect<ShoppingCartViewModel.CartViewState> processCheckedOut(
      ShoppingCartViewModel.CartViewState state, ShoppingCartDomain.CheckedOut checkedOut);
}
