== Query syntax reference

Define View queries in a language that is similar to SQL. The following examples illustrate the syntax. To retrieve:

* All customers without any filtering conditions (no WHERE clause):
+
[source,proto,indent=0]
----
SELECT * FROM customers
----

* Customers with a name matching the `customer_name` property of the request message:
+
[source,proto,indent=0]
----
SELECT * FROM customers WHERE name = :customer_name
----

* Customers matching the `customer_name` AND `city` properties of the request message:
+
[source,proto,indent=0]
----
SELECT * FROM customers WHERE name = :customer_name AND address.city = :city
----

* Customers in a city matching a literal value:
+
[source,proto,indent=0]
----
SELECT * FROM customers WHERE address.city = 'New York'
----

=== Filter predicates

Use filter predicates in `WHERE` conditions to further refine results.

==== Comparison operators

The following comparison operators are supported:

* `=` equals
* `!=` not equals
* `>` greater than
* `>=` greater than or equals
* `<` less than
* `\<=` less than or equals

==== Logical operators

////
Combine filter conditions with the `AND` and `OR` operators, and negate using the `NOT` operator. Group conditions using parentheses. Note that `AND` has precedence over `OR`.

[source,proto,indent=0]
----
SELECT * FROM customers WHERE
  name = :customer_name AND address.city = 'New York' OR
  NOT (name = :customer_name AND address.city = 'San Francisco')
----
////

Combine filter conditions with the `AND` operator, and negate using the `NOT` operator. Group conditions using parentheses.

NOTE: `OR` support is currently disabled, until it can be more efficiently indexed.

----
SELECT * FROM customers WHERE
  name = :customer_name AND NOT (address.city = 'New York' AND age > 65)
----

==== Array operators

Use `IN` or `= ANY` to check whether a value is contained in a group of values or in an array column or parameter (a `repeated` field in the Protobuf message).

Use `IN` with a list of values or parameters:

----
SELECT * FROM customers WHERE email IN ('bob@example.com', :some_email)
----

Use `= ANY` to check against an array column (a `repeated` field in the Protobuf message):

----
SELECT * FROM customers WHERE :some_email = ANY(emails)
----

Or use `= ANY` with a repeated field in the request parameters:

----
SELECT * FROM customers WHERE email = ANY(:some_emails)
----

==== Pattern matching

Use `LIKE` to pattern match on strings. The standard SQL `LIKE` patterns are supported, with `_` (underscore) matching a single character, and `%` (percent sign) matching any sequence of zero or more characters.

----
SELECT * FROM customers WHERE name LIKE 'Bob%'
----

NOTE: For index efficiency, the pattern must have a non-wildcard prefix or suffix. A pattern like `'%foo%'` is not supported. Given this limitation, only constant patterns with literal strings are supported; patterns in request parameters are not allowed.

==== Text search

Use the `text_search` function to search text values for words, with automatic tokenization and normalization based on language-specific configuration. The `text_search` function takes the text column to search, the query (as a parameter or literal string), and an optional language configuration.

----
text_search(<column>, <query parameter or string>, [<configuration>])
----

If the query contains multiple words, the text search will find values that contain all of these words (logically combined with AND), with tokenization and normalization automatically applied.

The following text search language configurations are supported: `'danish'`, `'dutch'`, `'english'`, `'finnish'`, `'french'`, `'german'`, `'hungarian'`, `'italian'`, `'norwegian'`, `'portuguese'`, `'romanian'`, `'russian'`, `'simple'`, `'spanish'`, `'swedish'`, `'turkish'`. By default, a `'simple'` configuration will be used, without language-specific features.

----
SELECT * FROM customers WHERE text_search(profile, :search_words, 'english')
----

NOTE: Text search is currently only available for deployed services, and can't be used in local testing.

==== Data types

The following data types are supported, for their corresponding Protobuf types. Arrays are created for a repeated field in a Protobuf message. Timestamps can be stored and compared using the `google.protobuf.Timestamp` message type.

[cols="1,1"]
|===
| Data type | Protobuf type

| Text
| `string`

| Integer
| `int32`

| Long (Big Integer)
| `int64`

| Float (Real)
| `float`

| Double
| `double`

| Boolean
| `bool`

| Byte String
| `bytes`

| Array
| repeated fields

| Timestamp
| `google.protobuf.Timestamp`

|===

==== Optional fields

Fields in a Protobuf message that were not given a value are handled as [the default value](https://developers.google.com/protocol-buffers/docs/proto3#default) of the field data type.

In some use cases it is important to explicitly express that a value is missing, doing that in a view column can be done in three ways:

 * mark the message field as `optional`
 * use one of the Protobuf "wrapper" types for the field (messages in the package `google.protobuf` ending with `Value`)
 * make the field a part of a nested message and omit that whole nested message, for example `address.street` where the lack of an `address` message implies there is no `street` field.

Optional fields with values present can be queried just like regular view fields:

----
SELECT * FROM customers WHERE phone_number = :number
----

Finding results with missing values can be done using `IS NULL`:

----
SELECT * FROM customers WHERE phone_number IS NULL
----

Finding entries with any value present can be queried using `IS NOT NULL`:

----
SELECT * FROM customers WHERE phone_number IS NOT NULL
----

Optional fields in query requests messages are handled like normal fields if they have a value, however missing optional request parameters are seen as an invalid request and lead to a bad request response.

=== Sorting

Results for a view query can be sorted. Use `ORDER BY` with view columns to sort results in ascending (`ASC`, by default) or descending (`DESC`) order.

If no explicit ordering is specified in a view query, results will be returned in the natural index order, which is based on the filter predicates in the query.

----
SELECT * FROM customers WHERE name = :name AND age > :min_age ORDER BY age DESC
----

NOTE: Some orderings may be rejected, if the view index cannot be efficiently ordered. Generally, to order by a column it should also appear in the `WHERE` conditions.

=== Paging

Splitting a query result into one "page" at a time rather than returning the entire result at once is possible in two ways:

* with a count based offset or
* a token based offset.

In both cases `OFFSET` and `LIMIT` are used.

`OFFSET` specifies at which offset in the result to start

`LIMIT` specifies a maximum number of results to return

==== Count based offset ====

The values can either be static, defined up front in the query:

[source,proto,indent=0]
----
SELECT * FROM customers LIMIT 10
----

Or come from fields in the request message:
[source,proto,indent=0]
----
SELECT * FROM customers OFFSET :start_from LIMIT :max_customers
----

Note: Using numeric offsets can lead to missing or duplicated entries in the result if entries are added to or removed from the view between requests for the pages.

==== Token based offset ====

The count based offset requires that you keep track of how far you got by adding the page size to the offset for each query.

An alternative to this is to use a string token emitted by Kalix identifying how far into the result set the paging has reached using the functions `next_page_token()` and `page_token_offset()`.

When reading the first page, an empty token is provided to `page_token_offset`. For each returned result page a new token that can be used to read the next page is returned by `next_page_token()`, once the last page has been read, an empty token is returned (see also xref:has-more[has_more] for determining if the last page was reached).

The size of each page can optionally be specified using `LIMIT`, if it is not present a default page size of 100 is used.

With a request and response message for the view like this:
[source,proto,indent=0]
----
message Request {
    string page_token = 1;
}

message Response {
    repeated Customer customers = 1;
    string next_page_token = 2;
}
----

A query like this will allow for reading through the view in pages, each containing 10 customers:
[source,proto,indent=0]
----
SELECT * AS customers, next_page_token() AS next_page_token
FROM customers
OFFSET page_token_offset(:page_token)
LIMIT 10
----

The token value is not meant to be parseable into any meaningful information other than being a token for reading the next page.

==== Total count of results

To get the total number of results that will be returned over all pages, use `COUNT(*)` in a query that projects its results into a field. The total count will be returned in the aliased field (using `AS`) or otherwise into a field named `count`.

----
SELECT * AS customers, COUNT(*) AS total, has_more() AS more FROM customers LIMIT 10
----

[#has-more]
==== Check if there are more pages ====

To check if there are more pages left, you can use the function `has_more()` providing a boolean value for the result. This works both for the count and token based offset paging, and also when only using `LIMIT` without any `OFFSET`:

[source,proto,indent=0]
----
SELECT * AS customers, has_more() AS more_customers FROM customers LIMIT 10
----

This query will return `more_customers = true` when the view contains more than 10 customers.