/* This code was generated by Kalix tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */

package com.example.actions;

import kalix.javasdk.action.ActionCreationContext;
import com.example.domain.CounterDomain;
import com.google.protobuf.Empty;
import com.google.protobuf.Any;

import java.util.Optional;

// tag::counter-topic[]
public class CounterJournalToTopicAction extends AbstractCounterJournalToTopicAction {
  public CounterJournalToTopicAction(ActionCreationContext creationContext) {}

  // tag::counter-topic-event-subject[]
  @Override
  public Effect<CounterTopicApi.Increased> onIncreased(CounterDomain.ValueIncreased valueIncreased) {
    // end::counter-topic[]
    Optional<String> counterId = actionContext().eventSubject(); //<1>
    // end::counter-topic-event-subject[]
    /*
    // tag::counter-topic-event-subject[]
    ...
    // end::counter-topic-event-subject[]
    */
    // tag::counter-topic[]
    CounterTopicApi.Increased increased = // <1>
        CounterTopicApi.Increased.newBuilder()
            .setValue(valueIncreased.getValue())
            .build();

    return effects().reply(increased); // <2>
    // tag::counter-topic-event-subject[]
  }
  // end::counter-topic-event-subject[]
  // end::counter-topic[]

  @Override
  public Effect<CounterTopicApi.Decreased> onDecreased(CounterDomain.ValueDecreased valueDecreased) {
    CounterTopicApi.Decreased decreased =
        CounterTopicApi.Decreased.newBuilder()
            .setValue(valueDecreased.getValue())
            .build();

    return effects().reply(decreased);
  }

  // tag::counter-snapshot[]
  @Override
  public Effect<CounterTopicApi.CurrentValue> onSnapshot(CounterDomain.CounterState counterState) {
    // Snapshot handler processes entity state before any events
    CounterTopicApi.CurrentValue currentValue =
        CounterTopicApi.CurrentValue.newBuilder()
            .setValue(counterState.getValue())
            .build();
    return effects().reply(currentValue);
  }
  // end::counter-snapshot[]
  // tag::counter-topic[]
}
// end::counter-topic[]
