// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/double-counter.proto

package com.example.actions;

public final class DoubleCounterApi {
  private DoubleCounterApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034actions/double-counter.proto\022\023com.exam" +
      "ple.actions\032 akkaserverless/annotations." +
      "proto\032 value-entities/counter_api.proto\032" +
      "\033google/protobuf/empty.proto2V\n\rDoubleCo" +
      "unter\022>\n\010Increase\022\032.com.example.Increase" +
      "Value\032\026.google.protobuf.Empty\032\005\302C\002\010\001B\022B\020" +
      "DoubleCounterApib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.akkaserverless.Annotations.getDescriptor(),
          com.example.CounterApi.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.akkaserverless.Annotations.service);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.akkaserverless.Annotations.getDescriptor();
    com.example.CounterApi.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
