/*
 * Copyright 2021 Lightbend Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package customer;

import com.akkaserverless.javasdk.impl.AnySupport;
import com.akkaserverless.javasdk.impl.EntityExceptions;
import com.akkaserverless.javasdk.impl.valueentity.AdaptedCommandContextWithState;
import com.akkaserverless.javasdk.lowlevel.ValueEntityHandler;
import com.akkaserverless.javasdk.valueentity.CommandContext;
import com.akkaserverless.javasdk.valueentity.ValueEntityBase;
import com.google.protobuf.Any;
import com.google.protobuf.Descriptors;
import com.google.protobuf.GeneratedMessageV3;
import com.google.protobuf.InvalidProtocolBufferException;
import customer.api.CustomerApi;
import customer.domain.CustomerDomain;
import scalapb.UnknownFieldSet;
import java.util.Optional;

/**
 * This class would be generated by codegen and should be treated mostly as an implementation detail
 * by the user.
 */
public class CustomerValueEntityHandler implements ValueEntityHandler {

  final CustomerValueEntity entity;

  public static final Descriptors.ServiceDescriptor serviceDescriptor =
      CustomerApi.getDescriptor().findServiceByName("CustomerService");
  public static final String entityType = "customers";

  CustomerValueEntityHandler(CustomerValueEntity entity) {
    this.entity = entity;
  }

  @Override
  public ValueEntityBase.Effect<? extends Object> handleCommand(
      Any command, Any state, CommandContext<Any> context) throws Throwable {

    CustomerDomain.CustomerState parsedState =
        CustomerDomain.CustomerState.parseFrom(state.getValue());

    CommandContext<CustomerDomain.CustomerState> adaptedContext =
        new AdaptedCommandContextWithState(context, parsedState);

    entity.setCommandContext(Optional.of(adaptedContext));

    try {
      switch (context.commandName()) {
        case "Create":
          return entity.create(parsedState, CustomerApi.Customer.parseFrom(command.getValue()));
        case "ChangeName":
          return entity.changeName(
              parsedState, CustomerApi.ChangeNameRequest.parseFrom(command.getValue()));
        case "GetCustomer":
          return entity.getCustomer(
              parsedState, CustomerApi.GetCustomerRequest.parseFrom(command.getValue()));
        default:
          throw new EntityExceptions.EntityException(
              context.entityId(),
              context.commandId(),
              context.commandName(),
              "No command handler found for command ["
                  + context.commandName()
                  + "] on "
                  + entity.getClass().toString());
      }
    } finally {
      entity.setCommandContext(Optional.empty());
    }
  }

  @Override
  public com.google.protobuf.any.Any emptyState() {
    return com.google.protobuf.any.Any.apply(
        AnySupport.DefaultTypeUrlPrefix()
            + "/"
            + CustomerDomain.CustomerState.getDescriptor().getFullName(),
        entity.emptyState().toByteString(),
        UnknownFieldSet.empty());
  }
}
