/* This code was generated by Akka Serverless tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */

package com.example.replicated;

import kalix.javasdk.AkkaServerless;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.example.replicated.counter.domain.SomeCounter;
import com.example.replicated.countermap.domain.SomeCounterMap;
import com.example.replicated.map.domain.SomeMap;
import com.example.replicated.multimap.domain.SomeMultiMap;
import com.example.replicated.register.domain.SomeRegister;
import com.example.replicated.registermap.domain.SomeRegisterMap;
import com.example.replicated.set.domain.SomeSet;

public final class Main {

  private static final Logger LOG = LoggerFactory.getLogger(Main.class);

  public static AkkaServerless createAkkaServerless() {
    // The AkkaServerlessFactory automatically registers any generated Actions, Views or Entities,
    // and is kept up-to-date with any changes in your protobuf definitions.
    // If you prefer, you may remove this and manually register these components in a
    // `new AkkaServerless()` instance.
    return AkkaServerlessFactory.withComponents(
      SomeCounter::new,
      SomeCounterMap::new,
      SomeMap::new,
      SomeMultiMap::new,
      SomeRegister::new,
      SomeRegisterMap::new,
      SomeSet::new);
  }

  public static void main(String[] args) throws Exception {
    LOG.info("starting the Akka Serverless service");
    createAkkaServerless().start();
  }
}
