= Access Control Lists (ACLs)

This section describes functionality in the Java/Scala SDK related to ACLs (Access Control Lists), for information about how the ACLs are defined and control access see xref:spring:using-acls.adoc[Using ACLs]

== Default ACL in project templates

If no ACLs is defined at all in a Kalix service Kalix will allow requests from both other services and the internet to all components of a Kalix service.

The Kalix quickstarts and [.group-java]#Maven archetypes# [.group-scala]#the sbt g8-template# all include a less permissive ACL for the entire service, to not accidentally make services available to the public internet, just like the one described in the next section.

== Defining an ACL for the entire Kalix Service

A default ACL for the entire Kalix Service can be defined by placing a on the Main of your service:

```java
@Acl(allow = @Acl.Matcher(service = "*"))
public class Main { ... } 
```

This is the default ACL included in the quickstarts and project templates, it allows calls from any other Kalix service deployed in the same Kalix project, but denies access from the internet.

== Inspecting the principal inside a service

Checking the ACLs are in general done for you by Kalix, however in some cases programmatic access to the principal of a call can be useful.

Accessing the principal of a call inside a service is possible through the request metadata `Metadata.principals()`. The `Metadata` for a call is available through the context (`actionContext`, `commandContext`) of the component.

== ACLs when running unit tests

In the generated unit test testkits, the ACLs are ignored.

== ACLs when running integration tests

When running integration tests, ACLs are disabled by default but can be explicitly enabled per test by running the test with `Settings.withAclEnabled`.

For integration tests that call other services that have ACLs limiting access to specific service names `Settings.withServiceName` allows specifying what the service identifies itself as to other services.