= Publishing and Subscribing with Actions

include::ROOT:partial$include.adoc[]

A very common use case when building Microservices is to publish and subscribe to a stream of events. The source of events can be the journal of an event sourced entity, the value entity state changes, a https://cloud.google.com/pubsub/docs/overview[Google Cloud Pub/Sub] or Apache Kafka topic for asynchronous messaging between services.

With Actions you can:

- subscribe to events emitted by an event sourced entity within the same service.
- subscribe to state changes emitted by a value entity within the same service.
- subscribe to events from Event Sourced Entities published as xref:service-to-service.adoc[service to service eventing]
- subscribe to external events from https://cloud.google.com/pubsub/docs/overview[Google Cloud Pub/Sub] or https://kafka.apache.org/[Apache Kafka].
- publish events to a Google Cloud Pub/Sub or Apache Kafka topic.

Messages are guaranteed to be delivered at least once. This means that receivers must be able to handle duplicate messages.

== Subscribing to an Event Sourced Entity

You can subscribe an Action to events from an Event Source Entity. To receive messages from the entity, you can annotate a method with `@Subscribe.EventSourcedEntity` and specify the class of the entity. The input type of the method must be the same of the events generated by the entity.

The following example assumes the existence of an xref:eventsourced.adoc[Event Sourced Entity] counter that emits events of type `CounterEvent` with subtypes `ValueIncreased` and `ValueDecreased`.

[source,java,indent=0]
.src/main/java/com/example/actions/CounterJournalToTopicAction.java
----
include::example$spring-eventsourced-counter/src/main/java/com/example/actions/CounterJournalToTopicAction.java[tag=sub-ESE-action]
----
<1> subscribing to the events from the Counter.
<2> setting the method input type to the events produced by the counter.
<3> any return is valid. See NOTE.

The events from the entity are delivered to the Action. The implementation may vary, for this simplified example you are just logging it, but it could a forward to some other component or external service.

[NOTE]
====
The return value of the method is an `Action.Effect` with message `0`, but can be any other of type `Action.Effect<Integer>` as the return type of the method indicates. The Kalix framework needs the response to ensure that the event was successfully processed. If no exception is thrown and the method returns a value, the framework assumes that the event was successfully processed and marks it as such. This allows the next event to be sent to the subscribing method.  However, if an exception is raised and not handled, this action will not process any more events until the necessary handling is added. It will raise the same error over and over again until the application is fixed and restarted.
====


== Subscribing to a Value Entity

You can subscribe an Action to events from an Value Entity. To receive messages from the entity, annotate a service method `@Subscribe.ValueEntiy` and specify the class of the entity. The same applies as for subscribing to an Event Sourced Entity.


== Subscribing to a Topic

To receive messages from a from Google Cloud Pub/Sub or Apache Kafka topic, annotate the service method `@Subscribe.Topic` and specify the topic name.

The events from the topic are delivered to the Action and in this simplified example they are only logged.

[source,java,indent=0]
.src/main/java/com/example/actions/CounterJournalToTopicAction.java
----
include::example$spring-eventsourced-counter/src/main/java/com/example/actions/CounterJournalToTopicAction.java[tag=sub-topic-action]
----
<1> subscribing to the events from topic 'counter-events'. 
<2> setting the method input type to the events produced by the counter.
<3> any return is valid. See NOTE in Subscribing to an Event Sourced Entity.


Note that by default, Kalix assumes the message in the topic was serialized as JSON and as such deserialize it into a `CounterEvent`. You can find more about serialization in Kalix here xref:spring:serialization.adoc[]

== Receiving messages from an external Topic

In the above example, you consumed JSON messages from a topic that you control. If you are consuming an external topic, the message format may not be under your control and may not be JSON.

In such case, the Action definition should receive an array of bytes and deserialization must be handled within the method. See xref:spring:serialization.adoc[Handling Serialization] for more information on how to deal with data formats.

== Subscribing and acting upon

Another possible usage for Actions is to consume events and act upon.

For example, you may consume events from one entity or from a topic, transform to commands and send to an another entity or an external system. This is similar to the usage explained in xref:actions-as-controller.adoc[Actions as Controller], except that the Action is driven by the flow of incoming events instead of external user requests.

== Publishing events to a Topic

To publish events in a topic you need also subscribe to an entity or a topic. Let's assume that you have the counter entity mentioned above. Then you can subscribe to the events of this counter, transform them and then publish them in a topic. 

To publish the events you need to add the annotation `@Publish.Topic` to the method subscribed to the events and add the name of the topic. 

[source,java,indent=0]
.src/main/java/com/example/actions/CounterJournalToTopicAction.java
----
include::example$spring-eventsourced-counter/src/main/java/com/example/actions/CounterJournalToTopicAction.java[tag=sub-ESE-pub-topic-action]
----
<1> subscribing to the events from the Counter.
<2> publishing to a topic name 'counter-events'.
<3> setting the method input type to the events produced by the counter.
<4> any return is valid. See NOTE in Subscribing to an Event Sourced Entity.

Note that the messages stored in the topic are serialized as JSON. You cannot change this serialization.

== Accessing the Entity ID

For many use cases, a subscriber to an event log will trigger other services and needs to pass the entity ID to the receiver. The events of an Event Sourced entity, by design, do not include the entity ID, but it is made available to the subscriber via the metadata field `subject`, accessible through `eventSubject` in the  link:{attachmentsdir}/api/io/kalix/javasdk/action/ActionContext.html[`ActionContext`{tab-icon}, window="new"].

You can access the link:{attachmentsdir}/api/kalix/javasdk/action/ActionContext.html[`ActionContext`{tab-icon}, window="new"] through method `actionContext()`.


TODO: add type level and ignore annotations when Spring SDK with them gets released
