= Calling other services


== Kalix services

Calling other Kalix services in the same project from an Action is done by invoking them using a https://docs.spring.io/spring-framework/docs/5.0.13.RELEASE/spring-framework-reference/web-reactive.html#webflux-client[`Spring WebFlux WebClient`]. The service is identified by the name it has been deployed. Kalix takes care of routing requests to the service and keeping the data safe by encrypting the connection for you.

In this sample we will make an action that does a call to the xref:value-entity.adoc[Value Entity Counter] service, deployed with the service name "counter."

The Kalix Java SDK provides a utility class `WebClientProvider` that can provide previously configured `WebClient`s to reach other Kalix services deployed on the same Kalix project.

In our delegating service implementation:

[source,java,indent=0]
.src/main/java/com/example/callanotherservice/DelegatingServiceAction.java
----
include::spring:example$spring-doc-snippets/src/main/java/com/example/callanotherservice/DelegatingServiceAction.java[tag=delegating-action]
----


<1> Let the `WebClientProvider` be injected into the Action with constructor injection.
<2> Use the `WebClientProvider` to build a `WebClient` for the *counter* service.
<3> Use the `WebClient` to make a REST call to the *counter* service.
<4> Use the remote call result to create a reply.

== External services

Calling Kalix services deployed on *different* projects or any other external service, is done by configuring specific `WebClients`.

See the https://docs.spring.io/spring-framework/docs/5.0.13.RELEASE/spring-framework-reference/web-reactive.html#webflux-client[`Spring WebFlux WebClient`]
documentation for details on configuring the `WebClients`.
