= Process overview
include::ROOT:partial$include.adoc[]

The main steps in developing a service include:

. <<_implement_components>>
. <<_create_unit_tests>>
. <<_package_service>>
. <<_run_locally>>
. <<_deploy_to_kalix>>


[#_specify_service_interface_and_domain_model]
== Specify service interface and domain model

The main components of a Kalix service are:

* Stateful https://docs.kalix.io/reference/glossary.html#entity[Entities]
* Stateless https://docs.kalix.io/reference/glossary.html#action[Actions]
* https://docs.kalix.io/reference/glossary.html#view[Views], which return the state of multiple instances of a stateful entity.

We recommend that you separate the service API and Entity domain data model. Separating the service interface and data model in different classes allows you to evolve them independently.

TIP: Kickstart a project using the xref:spring:getting-started.adoc[Getting started] guide.


[#_implement_components]
== Implement components

Stateful services can implement https://docs.kalix.io/reference/glossary.html#value_entity[Value Entity] or https://docs.kalix.io/reference/glossary.html#event_sourced_entity[Event Sourced Entity] and https://docs.kalix.io/reference/glossary.html#view[View] components. Stateless services implement https://docs.kalix.io/reference/glossary.html#action[Actions]. Typically, a stateful service should only have one Entity type, but can also include Actions and Views.

=== Actions

Actions are stateless functions that can be triggered by HTTP calls. They can also subscribe to published events, and they can send commands to other services based on the events they receive. For more information about writing actions see xref:spring:actions.adoc[Implementing Actions].

=== Entities
Stateful services encapsulate business logic in Value Entities or Event Sourced Entities. At runtime, command messages invoke operations on Entities. A command may only act on one Entity at a time.


TIP: To learn more about Kalix entities see xref:spring:value-entity.adoc[Implementing Value Entities] and xref:spring:eventsourced.adoc[Implementing Event Sourced Entities].

If you would like to update multiple Entities from a single command, you can use forwarding and side effects.

TIP: For more information see xref:spring:actions-as-controller.adoc[Actions as Controllers] and xref:spring:side-effects.adoc[Running Side Effects].

Services can interact asynchronously with other services and with external systems. Event Sourced Entities emit events to a journal, to which other services can subscribe. By configuring your own publish/subscribe (pub/sub) mechanism, any service can publish their own events and subscribe to events published by other services or external systems.

=== Views

A View provides a way to retrieve state from multiple Entities based on a query. You can query non-key data items. You can create views from Value Entity state, Event Sourced Entity events, and by subscribing to topics. For more information about writing views see xref:spring:views.adoc[Implementing Views].


[#_create_unit_tests]
== Testing your application

It is good practice to write unit tests and integration tests as you implement your services.

Kalix Spring SDK provides a test kit dependency that you can use to write unit tests for Actions and Entities as well as
integration tests. Please consult the component specific pages to learn more about writing unit tests and integration tests for your application.


[#_package_service]
== Package service

Use Docker to package your service and any of its dependencies. See the following pages for more information:

* https://docs.kalix.io/setting-up/#_containers[Setting up containers]
* https://docs.kalix.io/projects/container-registries.html[Configuring registries]

[#_run_locally]
== Run locally

You can test and debug your services by
https://docs.kalix.io/services/running-locally.html[running them locally] before deploying to Kalix.

[#_deploy_to_kalix]
== Deploy to Kalix

After testing locally, deploy your service to Kalix using the CLI or the Console. The following pages provide information about deployment:

* https://docs.kalix.io/projects/index.html[Working with Kalix projects]
* https://docs.kalix.io/services/deploy-service.html#_deploy[Deploying a packaged service]
* https://docs.kalix.io/quickstart/index.html[Quickstart examples]
