= Implementing Actions
:page-aliases: spring:actions.adoc, spring:actions-as-controller.adoc, spring:side-effects.adoc, java:actions-as-controller.adoc, java:side-effects.adoc

include::ROOT:partial$include.adoc[]
include::java-protobuf:partial$actions.adoc[]

include::java-protobuf:partial$effects-action.adoc[]

See also xref:java:development-process.adoc#_effects_api[Understanding what an Effect is]

== Actions as Pure Functions

In this first example, you will learn how to implement an Action as a pure stateless function. You will create a `FibonacciAction` that takes a number and returns the
next number in the Fibonacci series.

To implement this action you need the following:

- Extend our class from `kalix.javasdk.action.Action`. This is generic. No matter what action you want to create you always need to extend from link:{attachmentsdir}/testkit/kalix/javasdk/action/Action.html[`Action` {tab-icon}, window="new"].
- Add the Spring annotation @RequestMapping to provide a REST endpoint for the function. Here the stateless function should be reachable via HTTP.
- Add the Spring annotations @GetMapping and @PostMapping to provide paths for GET and POST to calculate the Fibonacci of a number. Both functions do the same thing and implementation-wise the function exposed with GET calls the function exposed with POST.  


[source,java,indent=0]
.src/main/java/com/example/fibonacci/FibonacciAction.java
----
include::example$java-spring-fibonacci-action/src/main/java/com/example/fibonacci/FibonacciAction.java[tag=implementing-action]
----
<1> `isFibonacci` checks if a number is a Fibonacci number.
<2> `nextFib` calculates the next number.
<3> This `nextNumber` implementation calls the `nextNumber` implementation below.
<4> The `nextNumber` implementation first checks if the input number belongs to the Fibonacci series. If so, it calculates the next number and builds a reply using `effects().reply()`.
<5> Otherwise, if the input number doesn't belong to the Fibonacci series, it builds an `Effect` reply error.

Actions return effects (i.e. `Action.Effect`) and there are different types of effects: a reply, an error, a forward call to another component, and to all of those you can add side effects. Here you want only the result of the calculation or an error. Therefore, you are using `.reply` and `.error`.

=== Multiple replies / reply streaming

An Action may return a stream of integers. To do this you need to define the return type as `reactor.core.publisher.Flux<Effect<Integer>>`. 

The stream may publish an arbitrary number of replies.

ifdef::todo[TODO: add a streamed Fib series calculation]


== Actions as Controllers

Actions can be used to implement link:https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller[MVC Controllers] by
acting as the external interface of a service, receiving requests, operating over the requests values and forwarding the call
to other components in the same service.

To illustrate how you can use an Action as a Controller, we will build on top of a Value Entity used to implement a Shopping Cart example, adding a new Action to the existing shopping cart service.

TIP: If you are hearing about `ValueEntity` for the first time, be sure to visit xref:value-entity.adoc[] before continuing.

Below you can find a summary of the shopping cart value entity we will use in this chapter: it contains only the signatures of the available endpoints for brevity:

.src/main/java/com/example/api/ShoppingCartEntity.java
[source,java]
----
include::example$java-spring-valueentity-shopping-cart/src/main/java/com/example/api/ShoppingCartEntity.java[tag=summary]
----
<1> Common path being used: `/cart/` suffixed with a `cartId`.
<2> `POST` endpoint exposed at `(...)/create` used to create a new cart with `cartId`.
<3> `POST` endpoint exposed at `(...)/items/add` allowing to add an item to an cart.
<4> `GET` endpoint for retrieving the state of a cart.

=== Forwarding Commands

The `forward` effect allows you to transform or further validate an incoming request before passing it on to another
component and have the response message directly passed back to the client making the request. The response from the
forwarded operation must have the same response type as the original request.

In this example it accepts requests with the same structure as the `create` endpoint listed above, by receiving a `LineItemDTO`, but add some additional verification of the
request and only conditionally forward the request to the entity if the verification is successful:


.src/main/java/com/example/api/ShoppingCartController.java
[source,java]
----
include::example$java-spring-valueentity-shopping-cart/src/main/java/com/example/api/ShoppingCartController.java[tag=forward]
----
<1> `ComponentClient` is injected on the constructor. It will be used to build calls to the underlining Entity.
<2> Expose the command handler as a `POST` endpoint at specified path.
<3> Check if the added item is carrots.
<4> If it is "carrots" immediately return an error, disallowing adding the item.
<5> For allowed requests, use `componentClient` to get a deferred call to the entity.
<6> The `deferredCall` is then used with `effects().forward()` to forward the request to the entity.

NOTE: You might be wondering what the `componentClient` is about. For now, think of it as a lightweight, type safe, HTTP client allowing you to reach out to other Kalix services. All details can be found at xref:component-and-service-calls.adoc[] chapter.

=== Forwarding Headers

By default, Kalix does not forward gRPC/HTTP headers to Kalix components. This can be overridden with the `@ForwardHeaders` annotation.

.src/main/java/com/example/api/ShoppingCartController.java
[source,java]
----
include::example$java-spring-valueentity-shopping-cart/src/main/java/com/example/api/ShoppingCartController.java[tag=forward-headers]
----
<1> Specify headers names that should be forwarded to this component.
<2> Access the header value with the `@RequestHeader` annotation.
<3> Alternatively, the header value can be retrieved from the `Metadata` associated with this call.
<4> Forward different headers to the next call, by using `withMetadata` method of from `DeferredCall` class.

=== Transform Request and Response to Another Component

The `asyncReply` and `asyncEffect` effects allow you to process and transform a request before calling another component and then also transform the response.

As an example, let us look at the problem of creating a new entity with an id generated by another component.

This example implements an `initializeCart` command for the controller Action which returns the generated id that can subsequently be used to interact with the cart.

.src/main/java/com/example/api/ShoppingCartController.java
[source,java]
----
include::example$java-spring-valueentity-shopping-cart/src/main/java/com/example/api/ShoppingCartController.java[tag=initialize]
----
<1> Generate a new UUID.
<2> Use the `componentClient` to create a call to endpoint `create` on the shopping cart.
<3> `execute()` on the deferred call immediately triggers a call and returns a `CompletionStage` for the response.
<4> Once the call succeeds or fails the `CompletionStage` is completed or failed, we can transform the result from `CompletionStage<Empty>`.
to `CompletionStage<Effect<String>>` using `handle`.
<5> On a successful response, create a reply effect passing back the `cartId`.
<6> If the call leads to an error, create an error effect asking the client to retry.
<7> `effects().asyncEffect()` allows us to reply with a `CompletionStage<Effect<String>>`.

The action generates a link:https://en.wikipedia.org/wiki/Universally_unique_identifier[UUID] to use as entity id for the shopping cart. UUIDs are extremely unlikely to lead to the same id
being generated, but to completely guarantee two calls can never be assigned the same shopping cart we
make use of the "boundary of consistency" provided by the entity - the entity will only process a single command at a time
and can safely make decisions based on its state - for example to only allow creation once by storing something in its state
signifying that it has been created.

In this case you mark that the entity has been created using a creation timestamp in the shopping cart state stored on first
`create` call - when the timestamp has the default value of `0`. If the cart has already been stored with a timestamp it returns an error effect:

.src/main/java/com/example/api/ShoppingCartEntity.java
[source,java]
----
include::example$java-spring-valueentity-shopping-cart/src/main/java/com/example/api/ShoppingCartEntity.java[tag=create]
----


[#_composing_calls]
=== Composing calls

The async call shown in the previous section, can also be used to chain or compose multiple calls to a single action response.

This example builds on the previous cart creation by adding an initial item in the cart once it has been created,
but before it returns the new id to the client:

.src/main/java/com/example/api/ShoppingCartController.java
[source,java]
----
include::example$java-spring-valueentity-shopping-cart/src/main/java/com/example/api/ShoppingCartController.java[tag=createPrePopulated]
----
<1> `CompletionStage#thenCompose` allow you to perform an additional async operation, returning a `CompletionStage` once the current one completes successfully.
<2> Create a request to add an initial item to the cart.
<3> Execute the `addItem` call returns a `CompletionStage<ShoppingCartDTO>` once it succeeds.
<4> Transform the successful completion of `addItem` with `ShoppingCartDTO` to the response type of this method - `String`.
<5> `effects().asyncReply()` lets us reply once the `CompletionStage<String>` completes.

In this sample it is safe to base a subsequent call to the entity on the reply of the previous one, no client will know
of the cart id until `createPrePopulated` replies.

IMPORTANT: There is no transaction or consistency boundary outside of
the entity, so for a sequence of calls from an action to an entity, the state of the entity could be updated by other
calls it receives in-between.

For example, imagine an action that for a cart id retrieves the state using `getState` to verify if too many items are
already in the cart, and once that has been verified, it adds the item to the cart.


.src/main/java/com/example/api/ShoppingCartController.java
[source,java]
----
include::example$java-spring-valueentity-shopping-cart/src/main/java/com/example/api/ShoppingCartController.java[tag=unsafeValidation]
----
<1> Between this call returning.
<2> And this next call to the same entity, the entity could accept other commands that change the total count of items in the cart.

The problem with this is that a `POST /cart/my-cart/items/add` call directly to the entity happening between the `GET /cart/my-cart`
action returning and the subsequent "addItem" call from the action would lead to more items in the cart than the allowed limit.

Such validation depending on state can only safely be done handling the command inside of the entity.

== Actions as Life-cycle Hooks

An Action method can be triggered automatically when some predefined service life-cycle event happens (currently, only on startup is available), serving as a custom hook. For such use, the method needs to be public, annotated with `@Trigger.OnStartup` and cannot receive any parameters, as shown below.

IMPORTANT: The on startup hook is called every time a service instance boots up. This can happen for very different reasons: restarting / redeploying the service, scaling up to more instances or even without any user-driven action (e.g. Kalix Runtime versions being rolled out, infrastructure-related incidents, etc.). Therefore, you should carefully consider how you use this hook and its implementation.

[source,java]
----
include::example$java-spring-doc-snippets/src/main/java/com/example/trigger/OnStartupAction.java[tag=hook]
----
<1> Only methods belonging to an Action can be configured as a hook.
<2> This hook will be triggered once the instance startup is concluded (i.e. will be called 3 times if 3 instances are running).
<3> Optionally, set the max amount of retries to 3.
<4> The method must be public and receive no parameters.

NOTE: If the call to the hook returns a failure and the `maxRetries` is set to a value greater than the default value (`0`), a number of retry calls will be executed with a fixed delay up until the configure amount is reached.


== Running Side Effects

=== Emitting effects on another component

An Entity or an Action may also emit one or more side effects. A side effect is something whose result has no impact on the result of the current command--if it fails, the current command still succeeds. The result of the side effect is therefore ignored. When used from inside an Entity, side effects are only performed after the successful completion of any state actions requested by the command handler.

There is no guarantee that a side effect will be executed successfully. If a failure occurs after the command is fully handled, effects might not be executed. Side effects are not retried in case of failures.

Side effects may be declared as synchronous or asynchronous. Asynchronous commands run in a "fire and forget" fashion. The code flow of the caller (the command handler of the entity which emitted the asynchronous command) continues while the command is being asynchronously processed. Meanwhile, synchronous commands run sequentially, that is, the commands are processed in order, one at a time. The final result of the command handler, either a reply or a forward, is not sent until all synchronous commands are completed.

==== Use case: mobile notification

You might want to run side effects to notify interested parties of a change in state. For example, after a withdrawal is made from a bank account, an account entity could send a notification to the account owner's mobile phone.


=== Emitting a side effect

To illustrate how you can emit a side effect, you can build on top of the xref:java:actions-as-controller.adoc[Action as a Controller] example. In that previous example, you  build a controller around the xref:value-entity.adoc[Value Entity Counter] and forwarded the incoming request
after modifying it.

This time, instead of using a `forward`, you will call the entity using a side effect.

=== Implementing the Action

The class `DoubleCounterAction` listens to the counter state changes. When the counter value changes this action doubles it.

[source,java,indent=0]
.src/main/java/com/example/actions/DoubleCounterAction.java
----
include::example$java-spring-valueentity-counter/src/main/java/com/example/action/DoubleCounterAction.java[tag=controller-side-effect]
----
<1> Retrieving the id of the counter.
<2> On incoming request, doubling the value of `increase`.
<3> Building a reply using `Confirmed.getDefaultInstance()`. And attaching a side effect, i.e. calling to the `Counter` to increase double the previous amount.

NOTE: the response of the side effect is ignored by the command meaning that even if the deferred call to
the `Counter` entity fails, the `Action` reply will succeed.

== Testing the Action


=== Unit tests

The following snippet shows how the `ActionTestkit` is used to test the `FibonacciAction` implementation.

With the `ActionTestkit` you can call the methods of `FibonacciAction`. Each call you pass over to the test kit returns an `ActionResult` that contains the effect produced by the underlying action method.

NOTE: Actions are unique units of computation where no local state is shared with previous or subsequent calls. The framework does not reuse an `Action` instance but creates a new one for each command handled and therefore this is also how the test kit behaves.

[.tabset]
Java::
+
.src/test/java/com/example/actions/FibonacciActionTest.java
[source,java]
----
include::example$java-spring-fibonacci-action/src/test/java/com/example/fibonacci/FibonacciActionTest.java[tag=testing-action]
----
<1> The test kit is created to allow us to test the Action's method.
<2> Calling `nextNumber` method with some value.
+
*ActionResult*
+
Calling an action method through the test kit gives us back an link:{attachmentsdir}/testkit/kalix/javasdk/testkit/ActionResult.html[`ActionResult` {tab-icon}, window="new"]. This class has methods that you can use to assert your expectations, such as:
+
* `getReply()` returns the reply message passed to `effects().reply()` or throws an exception failing the test, if the effect returned was not a reply.
* `getError()` returns the error description when `effects().error()` was returned to signal an error.
* `getForward()` returns details about what message was forwarded and where the call was forwarded (since it is a unit test the forward is not actually executed).

ifdef::todo[TODO: add links to before and after]

NOTE: The side effects of an Action can NOT be tested in isolation at the moment.

=== Integration tests

Actions (like any other Kalix component) can be verified with integration tests. The https://docs.spring.io/spring-framework/reference/web/webflux-webclient.html[Spring WebClient] utility can be used to run any HTTP call to test Kalix components.

[.tabset]
Java::
+
.src/it/java/com/example/fibonacci/FibonacciActionIntegrationTest.java
[source,java]
----
include::example$java-spring-fibonacci-action/src/it/java/com/example/fibonacci/FibonacciActionIntegrationTest.java[tag=testing-action]
----
<1> Mark the test as a Spring integration tests.
<2> Set up the Kalix infrastructure by extending `KalixIntegrationTestKitSupport`.
<3> Use `WebClient` to call the Action component endpoint.

In cases where detailed assertions on the HTTP response are not required, the Kalix xref:component-and-service-calls.adoc#_component_client[ComponentClient] can be used in integration tests.


[.tabset]
Java::
+
.src/it/java/com/example/fibonacci/FibonacciActionComponentClientIntegrationTest.java
[source,java]
----
include::example$java-spring-fibonacci-action/src/it/java/com/example/fibonacci/FibonacciActionComponentClientIntegrationTest.java[tag=testing-action]
----
<1> Use the `ComponentClient` to call the Action component endpoint.
<2> Transform the `DeferredCall` to a `CompletionStage` and wait for the response.


NOTE: The integration tests in samples are under in a specific project profile `it` and can be run using `mvn verify -Pit`.
