= Implementing Actions in Java
:page-supergroup-java-scala: Language

include::ROOT:partial$include.adoc[]
include::partial$actions.adoc[]

== Defining the `proto` file

An Action may implement any service method defined in a Protobuf definition. In this first example, we will show how to
implement an Action as a pure stateless function. We will define a `FibonacciAction` that takes a number and return the
next number in the Fibonacci series.

[.tabset]
Java::
+
[source,proto,indent=0]
.src/main/proto/com/example/fibonacci/fibonacci.proto
----
include::example$java-fibonacci-action/src/main/proto/com/example/fibonacci/fibonacci.proto[tag=actions]
----
<1> Any classes generated from this protobuf file will be in the `com.example.fibonacci` package.
<2> Import the Akka Serverless protobuf annotations or options.
<3> Let the messages declared in this protobuf file be inner classes to the Java class `FibonacciApi`.
<4> The protobuf option (akkaserverless.service) is specific to code-generation as provided by the Akka Serverless Maven plugin. This annotation indicates to the code-generation that an Action must be generated.

Scala::
+
[source,proto,indent=0]
.src/main/proto/com/example/fibonacci/fibonacci.proto
----
include::example$scala-fibonacci-action/src/main/proto/com/example/fibonacci/fibonacci.proto[tag=actions]
----
<1> Any classes generated from this protobuf file will be in the `com.example.fibonacci` package.
<2> Import the Akka Serverless protobuf annotations or options.
<3> The protobuf option (akkaserverless.service) is specific to code-generation as provided by the Akka Serverless Maven plugin. This annotation indicates to the code-generation that an Action must be generated.

== Implementing the Action

An Action implementation is a class where you define how each message is handled. The class
`FibonacciAction` gets generated for us based on the proto file defined above. Once the
[.group-java]#`FibonacciAction.java`# [.group-scala]#`FibonacciAction.scala`# file exists, it is not overwritten, so you can freely add logic to it.
`FibonacciAction` extends the generated class `AbstractFibonacciAction` which we're
not supposed to change as it gets regenerated in case we update the protobuf descriptors.

`AbstractFibonacciAction` contains all method signatures corresponding to the API of the service.
If you change the API you will see compilation errors in the `FibonacciAction` class, and you have to
implement the methods required by `AbstractFibonacciAction`.

[.tabset]
Java::
+
[source,java,indent=0]
.src/main/java/com/example/fibonacci/FibonacciAction.java
----
include::example$java-fibonacci-action/src/main/java/com/example/fibonacci/FibonacciActionGenerated.java[tag=generated-action]
----
<1> Extends the generated `AbstractFibonacciAction`, which extends link:{attachmentsdir}/api/com/akkaserverless/javasdk/action/Action.html[`Action` {tab-icon}, window="new"].
<2> A `nextNumber` method is generated. We will implement it next.

Scala::
+
[source,scala,indent=0]
.src/main/scala/com/example/fibonacci/FibonacciAction.scala
----
include::example$scala-fibonacci-action/src/main/scala/com/example/fibonacci/FibonacciActionGenerated.scala[tag=generated-action]
----
<1> Extends the generated `AbstractFibonacciAction`, which extends link:{attachmentsdir}/scala-api/com/akkaserverless/scalasdk/action/Action.html[`Action` {tab-icon}, window="new"].
<2> A `nextNumber` method is generated. We will implement it next.

Next, we can implement `nextNumber` method to complete our Action.

[.tabset]
Java::
+
[source,java,indent=0]
.src/main/java/com/example/fibonacci/FibonacciAction.java
----
include::example$java-fibonacci-action/src/main/java/com/example/fibonacci/FibonacciAction.java[tag=implemented-action]
----
<1> We add two private methods to support the computation. `isFibonacci` checks if a number is a Fibonacci number and
`nextFib` calculates the next number.
<2> The `nextNumber` implementation first checks if the input number belongs to the Fibonacci series. If so, it calculates the
next number and builds a reply using `effects().reply()`.
<3> Otherwise, if the input number doesn't belong to the Fibonacci series, it builds an `Effect` reply error.

Scala::
+
[source,scala,indent=0]
.src/main/scala/com/example/fibonacci/FibonacciAction.scala
----
include::example$scala-fibonacci-action/src/main/scala/com/example/fibonacci/FibonacciAction.scala[tag=implemented-action]
----
<1> We add two private methods to support the computation. `isFibonacci` checks if a number is a Fibonacci number and
`nextFib` calculates the next number.
<2> The `nextNumber` implementation first checks if the input number belongs to the Fibonacci series. If so, it calculates the
next number and builds a reply using `effects.reply()`.
<3> Otherwise, if the input number doesn't belong to the Fibonacci series, it builds an `Effect` reply error.

=== Multiple replies / reply streaming

An Action may return data conditionally by marking the return type as `stream` in Protobuf. The Java method implementing
that service must return an https://doc.akka.io/docs/akka/current/stream/stream-flows-and-basics.html[Akka Streams Source]
to fulfill that contract.

The Source may publish an arbitrary number of replies.

ifdef::todo[TODO: add a streamed Fib series calculation]


== Registering the Action

To make Akka Serverless aware of the Action, we need to register it with the service.

From the code-generation, the registration gets automatically inserted in the generated `AkkaServerlessFactory.withComponents` method from the `Main` class.

[.tabset]
Java::
+
[source,java]
./src/main/java/com/example/Main.java
----
include::java:example$java-fibonacci-action/src/main/java/com/example/Main.java[]
----

Scala::
+
[source,scala]
./src/main/scala/com/example/fibonacci/Main.scala
----
include::example$scala-fibonacci-action/src/main/scala/com/example/fibonacci/Main.scala[]
----

By default, the generated constructor has an `ActionCreationContext` parameter, but you can change this to accept other parameters. 
If you change the constructor of the `FibonacciAction` class you will see a compilation error here, and you have to adjust the 
factory function that is passed to `AkkaServerlessFactory.withComponents`.

When more components are added the `AkkaServerlessFactory` is regenerated, and you have to adjust the registration from the `Main` class.

== Testing the Action 


=== Unit tests

The following snippet shows how the `CounterJournalToTopicActionTestKit` is used to test the `CounterJournalToTopicAction` implementation.

AkkaServerless provides the `CounterJournalToTopicActionTestKit` that allows us to call the methods of `CounterJournalToTopicAction`. For each `Action` AkkaServerless generates an specific test kit for it, with the name `[ActionName]TestKit`. This test kit hold an instance of its `Action`. Each call we execute over to the test kit returns an `ActionResult` that holds the effect produced by the underlying `CounterJournalToTopicAction`. 

Apart from the test kit AkkaServerless generates test classes based on the Action defined in the .proto files. This is shown in the snippet below. 

Is worth noting that Actions are unique units of computation. The framework doesn't reuse an Action instance. A consequence of this is that we should create a test kit for each method we evaluate as shown in the snippet. 

.src/test/java/com/example/actions/CounterJournalToTopicActionTest.java
[source,java]
----
include::example$java-eventsourced-counter/src/test/java/com/example/actions/CounterJournalToTopicActionTest.java[tag=class] 
----
<1> creating the test kit to test `increase` Action's method.
<2> calling `increase` method with some value.
<3> retrieving the `Reply` from `increase` method.

*ActionResult*

Calling an action method through the TestKit gives us back an link:{attachmentsdir}/testkit/com/akkaserverless/javasdk/testkit/ActionResult.html[`ActionResult` {tab-icon}, window="new"]. This class has methods that we can use to assert our expectations, such as:

* `getReply` returns the value passed to the `Effect.reply`, if any.
* `getForwardServiceCall` returns the `ServiceCall` to use to forward the call, if any.



*CounterJournalToTopicActionTestKit*

This class is generated by AkkaServerless when the project is compiled and located in `target/generated-test-sources/akkaserveless/java/com/example/actions/`. The snippet `CounterJournalToTopicActionTest.java` above shows all the available methods for this specific test kit.  
