= Java API docs

include::ROOT:partial$include.adoc[]

The Java API docs can be found link:{attachmentsdir}/api/index.html[here {tab-icon}, window="new"].

== Parameter injection

Akka Serverless entities work by annotating classes and methods to be instantiated and invoked by the gRPC server. The methods and constructors invoked by the server can be injected with parameters of various types from the context of the invocation. For example, an `@CommandHandler` annotated method may take an argument for the message type for that gRPC service call, in addition it may take a `CommandContext` parameter.

Exactly which context parameters are available depend on the type of Entity and the type of handler, in subsequent pages we'll detail which parameters are available in which circumstances. The order of the parameters in the method signature can be anything, parameters are matched by type and sometimes by annotation. The following context parameters are available in every context:

|====
| Type | Annotation | Description

| link:{attachmentsdir}/api/com/akkaserverless/javasdk/Context.html[`Context`{tab-icon}, window="new"]
|
| The super type of all Akka Serverless contexts. Every invoker makes a subtype of this available for injection, and method or constructor may accept that sub type, or any super type of that subtype that is a subtype of `Context`.

| `java.lang.String`
| link:{attachmentsdir}/api/com/akkaserverless/javasdk/EntityId.html[`@EntityId`]
| The ID of the Entity.

|====
