= Process overview
:page-aliases: spring:development-process.adoc
include::ROOT:partial$include.adoc[]

The main steps in developing a service include:

. <<_effects_api>>
. <<_implement_components>>
. <<_create_unit_tests>>
. <<_package_service>>
. <<_run_locally>>
. <<_deploy_to_kalix>>


[#_specify_service_interface_and_domain_model]
== Specify service interface and domain model

The main components of a Kalix service are:

* Stateful https://docs.kalix.io/reference/glossary.html#entity[Entities]
* Stateful https://docs.kalix.io/reference/glossary.html#Workflow[Workflows]
* Stateless https://docs.kalix.io/reference/glossary.html#action[Actions]
* https://docs.kalix.io/reference/glossary.html#view[Views], which return the state of multiple instances of a stateful entity.

We recommend that you separate the service API and Entity domain data model. Separating the service interface and data model in different classes allows you to evolve them independently.

TIP: Kickstart a project using the xref:java:getting-started.adoc[Getting started] guide.

include::java-protobuf:partial$effects-api.adoc[]

[#_implement_components]
== Implement components

Stateful services can implement https://docs.kalix.io/reference/glossary.html#value_entity[Value Entity] or https://docs.kalix.io/reference/glossary.html#event_sourced_entity[Event Sourced Entity] and https://docs.kalix.io/reference/glossary.html#view[View] components. Stateless services implement https://docs.kalix.io/reference/glossary.html#action[Actions]. Typically, a stateful service should only have one Entity type, but can also include Actions and Views.


=== Actions

Actions are stateless functions that can be triggered by HTTP calls. They can also subscribe to published events, and they can send commands to other services based on the events they receive. For more information about writing actions see xref:java:actions.adoc[Implementing Actions].

=== Entities
Stateful services encapsulate business logic in Value Entities or Event Sourced Entities. At runtime, command messages invoke operations on Entities. A command may only act on one Entity at a time.


TIP: To learn more about Kalix entities see xref:java:value-entity.adoc[Implementing Value Entities] and xref:java:event-sourced-entities.adoc[Implementing Event Sourced Entities].

If you would like to update multiple Entities from a single command, you can use forwarding and side effects.

TIP: For more information see xref:java:actions-as-controller.adoc[Actions as Controllers] and xref:java:side-effects.adoc[Running Side Effects].

Services can interact asynchronously with other services and with external systems. Event Sourced Entities emit events to a journal, to which other services can subscribe. By configuring your own publish/subscribe (pub/sub) mechanism, any service can publish their own events and subscribe to events published by other services or external systems.

=== Workflows
Kalix Workflows are high-level descriptions to easily align business requirements with their implementation in code. Orchestration across multiple services with support for failure scenarios and compensating actions is simple with Kalix Workflows.

=== Views

A View provides a way to retrieve state from multiple Entities based on a query. You can create views from Value Entity state, Event Sourced Entity events, and by subscribing to topics. For more information about writing views see xref:java:views.adoc[Implementing Views].

For more details and examples take a look at the following topics:

* xref:java:value-entity.adoc[Value Entities]
* xref:java:event-sourced-entities.adoc[Event Sourced Entities]
* xref:java:workflows.adoc[Workflows]
* xref:java:actions.adoc[Actions]
* xref:java:views.adoc[Views]

[#_create_unit_tests]
== Testing your application

It is good practice to write unit tests and integration tests as you implement your services.

Kalix Java SDK provides a test kit dependency that you can use to write unit tests for Actions and Entities as well as
integration tests. Please consult the component specific pages to learn more about writing unit tests and integration tests for your application.


[#_package_service]
== Package service

Use Docker to package your service and any of its dependencies.
See https://docs.kalix.io/projects/container-registries.html[Configuring registries] for more information.

[#_run_locally]
== Run locally

You can test and debug your services by xref:running-locally.adoc[running them locally] before deploying to Kalix.

[#_deploy_to_kalix]
== Deploy to Kalix

After testing locally, deploy your service to Kalix using the CLI or the Console. The following pages provide information about deployment:

* https://docs.kalix.io/projects/index.html[Working with Kalix projects]
* https://docs.kalix.io/services/deploy-service.html#_deploy[Deploying a packaged service]
