= Developer Tools

include::ROOT:partial$include.adoc[]
include::partial$attributes.adoc[]

The Java tooling is published to https://mvnrepository.com/artifact/com.akkaserverless[Maven Central]. 

== Maven archetype

A https://maven.apache.org/guides/introduction/introduction-to-archetypes.html[Maven archetype]; _akkaserverless-maven-archetype_ provides the tooling to xref:quickstart-template.adoc[kickstart a Maven project]. You supply details such as the desired artifact and group IDs, and the archetype provides a new Maven project directory with the Akka Serverless SDK and associated development support tooling set up.

The archetype can be used via the `mvn` CLI.
[.tabset]
Linux or MacOS::
+
[source,command line,subs="attributes"]
----
mvn \
  archetype:generate \
  -DarchetypeGroupId=com.akkaserverless \
  -DarchetypeArtifactId=akkaserverless-maven-archetype \
  -DarchetypeVersion={akkaserverless-java-sdk-version}
----

Windows::
+
[source,command line,subs="attributes"]
----
mvn ^
  archetype:generate ^
  -DarchetypeGroupId=com.akkaserverless ^
  -DarchetypeArtifactId=akkaserverless-maven-archetype ^
  -DarchetypeVersion={akkaserverless-java-sdk-version}
----


== Ongoing development support
The development support tooling is provided via a single Maven plugin; _akkaserverless-maven-plugin_. This plugin provides two Maven goals to support Protobuf driven interface-first development.

=== Goals
This plugin implements the following https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html[Maven Build Lifecycle] goals:

* `generate`; generates implementation stubs for your entity/service and corresponding tests, as well as an abstract class for your implementation to extend. If you make further updates to your Protobuf specification after the initial generation, existing implementation is left unchanged but the abstract class is updated to align. This allows you to leverage native developer tooling to guide the desired changes.
* `deploy`; simply invokes the `akkasls` command line tool to deploy the service to Akka Serverless. This relies on an existing installation of the CLI and uses configuration and credentials from that installation.

NOTE: The deploy goal requires the Akka Serverless CLI to be installed on your system.

=== Configuration
The behaviour of the plugin can be adjusted by adding a `<configuration>` tag to the plugin definition in your POM with any of the following options:

* `akkaslsPath` path and name of the `akkasls` commmand line tool
* `akkaslsContext` selects the context when calling `akkasls` if set
* `dockerImage` the Docker image name (use eg. `<dockerImage>${akkasls.dockerImage}:${akkasls.dockerTag}</dockerImage>`)
