= Implementing Event Sourced Entities
:page-aliases: spring:eventsourced.adoc, spring:event-sourced-entities.adoc
:sample-url: https://github.com/lightbend/kalix-jvm-sdk/tree/main/samples/java-spring-eventsourced-shopping-cart

include::ROOT:partial$include.adoc[]
include::java-protobuf:partial$eventsourced.adoc[]

https://docs.kalix.io/reference/glossary.html#event_sourced_entity[Event Sourced Entities] persist changes as events and snapshots. Kalix needs to serialize that data to send it to the underlying data store. However, we recommend that you do not persist your service's public API messages. Persisting private API messages may introduce some overhead when converting from a public message to an internal one but it allows the logic of the service public interface to evolve independently of the data storage format, which should be private.

The steps necessary to implement an Event Sourced Entity include:

. Model the entity's state and its domain events.
. Implementing behavior in command and event handlers.
. Creating and initializing the Entity.


The following sections walk through these steps using a shopping cart service as an example (working sample available {sample-url}[here {tab-icon}, window="new"]).

== Modeling the Entity

Through our "Shopping Cart" Event Sourced Entity we expect to manage our cart, adding and removing items as we please. Being event-sourced means it will represent changes to state as a series of domain events. So let's have a look at what kind of model we expect to store and the events our entity might generate.

[source,java]
.src/main/java/com/example/shoppingcart/domain/ShoppingCart.java
----
include::example$java-spring-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/domain/ShoppingCart.java[tag=domain]
----
<1> Our `ShoppingCart` is fairly simple, being composed only by a `cartId` and a list of line items.
<2> A `LineItem` represents a single product and the quantity we intend to buy.

NOTE: Above we are taking advantage of the Java `record` to reduce the amount of boilerplate code, but you can use regular classes so long as they can be serialized to JSON (e.g. using Jackson annotations).

Another fundamental aspect of our entity will be its domain events. For now, we will have 3 different events `ItemAdded`, `ItemRemoved` and `CheckedOut`, defined as below:

[source,java]
.src/main/java/com/example/shoppingcart/domain/ShoppingCartEvent.java
----
include::example$java-spring-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/domain/ShoppingCartEvent.java[tag=events]
----
<1> The 3 types of event all derive from the same type `ShoppingCartEvent`.
<2> Includes the logical type name using `@TypeName` annotation.

IMPORTANT: The use of logical names for subtypes is essential for maintainability purposes. Our recommendation is to use logical names (i.e. `@TypeName`) that are unique per Kalix service. Check xref:serialization.adoc#_type_name[type name] documentation for more details.

include::partial$entity-ids.adoc[]

include::java-protobuf:partial$effects-event-sourced-entity.adoc[]

See also xref:java:development-process.adoc#_effects_api[Understanding what an Effect is]

== Implementing behavior

Now that we have our Entity state defined along with its events, the remaining steps can be summarized as follows:

- declare your entity and pick an entity id (it needs to be unique as it will be used for sharding purposes);
- define an access point (i.e. a route path) to your entity;
- implement how each command is handled and which event(s) it generates;
- provide a handler for each event and how it affects the entity's state.

Let's have a look at what our shopping cart entity will look like for the first 2 steps from the above list:

[source,java]
.src/main/java/com/example/shoppingcart/ShoppingCartEntity.java
----
include::example$java-spring-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/ShoppingCartEntity.java[tag=class]
----
<1> Create a class that extends `EventSourcedEntity<S, E>`, where `S` is the state type this entity will store (i.e. `ShoppingCart`) and `E` is the top type for the events it emits (i.e. `ShoppingCartEvent`).
<2> Annotate such class with `@Id` and pass the name of the id that will be used as the entity instance unique identifier.
<3> Make sure to annotate such class with `@TypeId` and pass a unique identifier for this entity type.
<4> Use Spring's RequestMapping annotation to define the route to your entity.


NOTE: The `@Id` value `cartId` must match a path parameter (i.e. `cartId`) and such value needs to be unique per entity. On the other hand, the `@TypeId` value `shopping-cart` is common for all instances of this entity but must be stable - cannot be changed after a production deploy - and unique across the different entity types.

=== Updating state

Having created the basis of our entity, we will now define how each command is handled. In the example below, we define a new endpoint that will add a new line item to a given shopping cart. It returns an `Effect` to emit an event and then sends a reply once the event is stored successfully. The state is updated by the event handler.

IMPORTANT: The **only** way for a command handler to modify the Entity's state is by emitting an event. Any modifications made directly to the state (or instance variables) from the command handler are not persisted. When the Entity is passivated and reloaded, those modifications will not be present.

[source,java,indent=0]
.src/main/java/com/example/shoppingcart/ShoppingCartEntity.java
----
include::example$java-spring-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/ShoppingCartEntity.java[tag=addItem]
----
<1> The validation ensures the quantity of items added is greater than zero and it fails for calls with illegal values by returning an `Effect` with `effects().error`.
<2> From the current incoming `LineItem` we create a new `ItemAdded` event representing the change of the cart.
<3> We store the event by returning an `Effect` with `effects().emitEvent`.
<4> The acknowledgment that the command was successfully processed is only sent if the event was successfully stored and applied, otherwise there will be an error reply. The lambda parameter `newState` gives us access to the new state returned by applying such event.
<5> Event handler needs to be marked with `@EventHandler` and receive a single parameter type matching the event type produced (i.e. `ItemAdded`).
<6> Return the new state to be stored - the logic for state transition is defined inside the `ShoppingCart` domain model.


NOTE: There needs to be one event handler declared per each type of event the ES entity emits (e.g. `itemAdded` receives a parameter of type `ItemAdded`, the same type emitted in `addItem` command handler).

As mentioned above, the business logic that allows us to transition between states was placed on the domain model as seen below:

[source,java,indent=0]
.src/main/java/com/example/shoppingcart/domain/ShoppingCart.java
----
include::example$java-spring-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/domain/ShoppingCart.java[tag=itemAdded]
----
<1> For an existing item, we will make sure to sum the existing quantity with the incoming one.
<2> Returns an update list of items without the existing item.
<3> Adds the update item to the shopping cart.
<4> Returns a new instance of the shopping cart with the updated line items.


=== Retrieving state

To have access to the current state of the entity we can use `currentState()` as you have probably noticed from the examples above. However, what if this is the first command we are receiving for this entity? The following example shows the implementation of the read-only command handler (accessed through `GET /cart/myCarId`):

[source,java,indent=0]
.src/main/java/com/example/shoppingcart/ShoppingCartEntity.java
----
include::example$java-spring-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/ShoppingCartEntity.java[tag=getCart]
----
<1> Stores the `entityId` on an internal attribute so we can use it later.
<2> Provides initial state - overriding `emptyState()` is optional but if not doing it, be careful to deal with a currentState() with a `null` value when receiving the first command or event.
<3> Marks this method as a command handler for `GET` requests.
<4> Returns the current state as reply for the request.

IMPORTANT: For simplicity purposes, we are returning the internal state directly back to the requester. In a real-world scenario, it's usually better to instead convert this internal domain model into a public model so the internal representation is free to evolve without breaking clients code.

== Snapshots

include::java-protobuf:partial$eventsourced-snapshots.adoc[]

== Deleting an Entity

Normally, Event Sourced Entities are not deleted because the history of the events typically provide business value.
For certain use cases or for regulatory reasons the entity can be deleted.

[source,java,indent=0]
.src/main/java/com/example/shoppingcart/ShoppingCartEntity.java
----
include::example$java-spring-eventsourced-shopping-cart/src/main/java/com/example/shoppingcart/ShoppingCartEntity.java[tag=checkout]
----
<1> Emit final event before deletion, which is handled as any other event.
<2> Instruction to delete the entity.

When you give the instruction to delete the entity it will still exist from some time, including its events and snapshots. The actual removal of events and snapshots will be deleted later to give downstream consumers time to process all prior events, including the final event that was emitted together with the `deleteEntity` effect. By default, the existence of the entity is completely cleaned up after a week.

It is not allowed to emit more events after the entity has been "marked" as deleted. You can still handle read requests of the entity until it has been completely removed.

It is best to not reuse the same entity id after deletion, but if that happens after the entity has been completely removed it will be instantiated as a completely new entity without any knowledge of previous state.

Note that xref:views.adoc#ve_delete[deleting View state] must be handled explicitly.

== Running Side Effects

An Entity may also emit one or more side effects. A side effect is something whose result has no impact on the result of the current command--if it fails, the current command still succeeds. The result of the side effect is therefore ignored. When used from inside an Entity, side effects are only performed after the successful completion of any state actions requested by the command handler.

See this xref:actions.adoc#_running_side_effects[dedicated section regarding Actions], for more details.

== Testing the Entity

include::partial$testing-entity.adoc[]


=== Unit tests

The following snippet shows how the `EventSourcedTestKit` is used to test the `ShoppingCartEntity` implementation. Kalix provides two main APIs for unit tests, the `EventSourcedTestKit` and the `EventSourcedResult`. The former gives us the overall state of the entity and all the events produced by all the calls to the Entity. While the latter only holds the effects produced for each individual call to the Entity.

.src/test/java/com/example/shoppingcart/domain/ShoppingCartTest.java
[source,java]
----
include::example$java-spring-eventsourced-shopping-cart/src/test/java/com/example/shoppingcart/domain/ShoppingCartTest.java[]
----
<1> Creates the TestKit passing the constructor of the Entity.
<2> Calls the method `addItem` from the Entity in the `EventSourcedTestKit` with quantity `10`.
<3> Asserts the return value is `"OK"`.
<4> Returns the next event of type `IdemAdded` and asserts on the quantity.
<5> Add a new item with quantity `5`.
<6> Asserts that the total number of events should be 2.
<7> Calls the `getCart` method and asserts that quantity should be `15`.

NOTE: The `EventSourcedTestKit` is stateful, and it holds the state of a single entity instance in memory. If you want to test more than one entity in a test, you need to create multiple instance of `EventSourcedTestKit`.

*EventSourcedResult*

Calling a command handler through the TestKit gives us back an link:{attachmentsdir}/testkit/kalix/javasdk/testkit/EventSourcedResult.html[`EventSourcedResult` {tab-icon}, window="new"]. This class has methods that we can use to assert the handling of the command, such as:

* `getReply()` - the response from the command handler if there was one, if not an, exception is thrown, failing the test.
* `getAllEvents()` - all the events emitted by handling the command.
* `getState()` - the state of the entity after applying any events the command handler emitted.
* `getNextEventOfType(ExpectedEvent.class)` - check the next of the emitted events against an event type, return it for inspection if it matches, or fail the test if it does not. The event gets consumed once is inspected and the next call will look for a subsequent event.

*EventSourcedTestKit*

For the above example, this class provides access to all the command handlers of the `ShoppingCart` entity for unit testing. In addition to that also has the following methods:

* `getState()` - the current state of the entity, it is updated on each method call emitting events.
* `getAllEvents()` - all events emitted since the creation of the testkit instance.


=== Integration tests

The skeleton of an Integration Test is generated for you if you use the archetype to start your Kalix app. Let's see what it could look like to test our `ShoppingCartEntity`:

./src/it/java/com/example/IntegrationTest.java
[source,java,indent=0]
----
include::example$java-spring-eventsourced-shopping-cart/src/it/java/com/example/IntegrationTest.java[tag=sample-it]
----
<1> Note the test class must extend `KalixIntegrationTestKitSupport`.
<2> A built-in web-client is provided to interact with the components.
<3> Request to create a new shopping cart with id `cart-abc`.
<4> Request to add an item to the cart.
<5> `GET` request to retrieve current status of the shopping cart and assert there should only be one item.

NOTE: The integration tests in samples are under in a specific project profile `it` and can be run using `mvn verify -Pit`.
