= Getting started
:page-aliases: spring:kickstart.adoc, spring:quickstart-java-maven.adoc, spring:getting-started.adoc

include::ROOT:partial$include.adoc[]
include::partial$attributes.adoc[]

The Kalix development tools help you to get started quickly. They include:

* A *Maven archetype* that generates the recommended project structure. The generated project is a regular Spring Boot project with a few configurations to integrate it seamlessly with Kalix.

* A *Maven plugin* to help you deploy your application to Kalix.

The generated project also contains configuration for packaging and deploying the service.

== Prerequisites

Before you start, make sure you have the following:

* JDK {java-version} or later
* Apache Maven {minimum_maven_version} or later
* Docker {minimum_docker_version} or higher (to run locally)

To deploy the Kalix service, you need:

* A https://console.kalix.io[Kalix account]
* A https://docs.kalix.io/projects/create-project.html[Kalix project]
* The https://docs.kalix.io/kalix/install-kalix.html[Kalix CLI (kalix)]
* A configured registry in which to publish the service container image. Refer to https://docs.kalix.io/projects/container-registries.html[Configuring registries] for more information on how to make your Docker registry available to Kalix.

:sectnums:

include::partial$maven-archetype.adoc[]

== Examine the project

The initial project contains a `Main` class for a Spring Boot application. The application is already configured to wire and register all Kalix components
it finds in the classpath. 

.src/main/java/com/example/Main.java
[source,java]
----
include::example$java-spring-valueentity-counter/src/main/java/com/example/Main.java[tag=main]
----
<1> Main class is annotated with `@SpringBootApplication`.
<2> The application is started like any other Spring Boot application.

== Implementing first component

Kalix have different kinds of components that you can use to implement your application.
The list of components are:

* xref:java:actions.adoc[Actions]
* xref:java:value-entity.adoc[Value Entities]
* xref:java:event-sourced-entities.adoc[Event Sourced Entities]
* xref:java:views.adoc[Views]

For this *Getting started* walk-through, we will implement a Counter based on a Value Entity. It's a simple counter
that receives commands to increase the counter.

.src/main/java/com/example/CounterEntity.java
[source,java]
----
include::example$java-spring-valueentity-counter/src/main/java/com/example/CounterEntity.java[tags=declarations;increase;close]
----
<1> Every Entity must be annotated with `@TypeId` with a stable identifier. This identifier should be unique among the different existing entities within a Kalix application.
<2> The `@Id` value should be unique per entity and map to some field being received on the route path, in this example it's the `counter_id`.
<3> The `CounterEntity` class should extend `kalix.javasdk.valueentity.ValueEntity`.
<4> The initial state of each counter is defined as 0.
<5> The method is accessible as a POST endpoint on `/counter/\{counter_id\}/increase`, where `counter_id` will be its unique identifier.
Note that it matches the `@Id` value.
<6> Its `increaseBy` method receives a `Number` as input and increases the counter by adding it to the current state.
<7> Finally, using the Effect API, we instruct Kalix to persist the new state, and we build a reply.

The `Number` record in this example is used as input for the `increaseBy` method and as to return the
counter's current state.

.src/main/java/com/example/Number.java
[source,java]
----
include::example$java-spring-valueentity-counter/src/main/java/com/example/Number.java[]
----

[sidebar]
A Kalix component doesn't require any other annotation. They will be registered to Kalix and be exposed automatically.
It suffices to add them on the same package or on a sub-package of your `Main` class. Please, refer to
xref:java:index.adoc#_dependency_injection[Dependency injection] page for more details on how Kalix components integrates
with Spring's application context.

The project also includes a dependency on the *Kalix Java SDK Test Kit*. Please consult the component specific pages to
learn more about writing unit tests and integration tests for your application.

== Package service

The project is configured to package your service into a Docker image which can be deployed to Kalix. The Docker image
name can be changed in the `pom.xml` file's `properties` section. Update this file to publish your image to your Docker repository.

This uses JDK {java-version} and the image is based on the link:https://adoptium.net/[Eclipse Adoptium] JDK image (formerly Adopt OpenJDK). Choose a different image in the `docker-maven-plugin` configuration  `pom.xml` file.

[source,bash]
----
mvn install
----

TIP: For more details see xref:java:development-process.adoc#_package_service[Development Process - Package service].

== Run locally

To start your service locally, run:

[source,bash]
----
mvn kalix:runAll
----

This command will start your Kalix service and a companion Kalix Runtime as configured in `docker-compose.yml` file.

If you prefer, you can also start docker-compose directly by running `docker-compose up` in one terminal and in another terminal start your Kalix service with:

[source,bash]
----
mvn kalix:run
----

With both the runtime and your service running, any defined endpoints should be available at `localhost:9000`,
the runtime local address.

[source, command window]
----
curl -XPOST -H "Content-Type: application/json" localhost:9000/counter/foo/increase -d '{ "value": 10 }'
----

== Deploy to Kalix

To deploy your service to Kalix:

First make sure you have updated the `dockerImage` property in the `pom.xml` to point at your Docker registry.
Then use the `deploy` target to build the container image, publish it to the container registry as configured in the `pom.xml` file, and the target `kalix:deploy` to automatically deploy the service to Kalix:

[source,command line]
----
mvn deploy kalix:deploy
----
include::partial$important-mvn-kalixdeploy.adoc[]

- When using the CLI, in your command window, you can set your Kalix project to be the current project:

+
[source, command window]
----
kalix config set project <project-name>
----

- Deploy your service following the instructions at xref:java:development-process.adoc#_deploy_to_kalix[Development Process - Deploy to Kalix].
