= Developing with Java

include::ROOT:partial$include.adoc[]
include::partial$attributes.adoc[]

The Akka Serverless Java SDK offers an idiomatic, annotation-based Java language SDK for writing components. This page describes prerequisites for Java development and basic requirements for a development project.

NOTE: Lightbend provides Tier 1 support for the Java SDK. See https://developer.lightbend.com/docs/akka-serverless/faq/index.html#_what_languages_are_supported[an explanation of support tiers] for more information.


Your development project needs to include the Akka Serverless Java SDK and logic to start the gRPC server. You define your components in gRPC descriptors and use `protoc` to compile them. Finally, you implement business logic for service components.

To save the work of starting from scratch, the Java xref:java:kickstart.adoc[code generation tool] creates a project, complete with descriptors and implementations. Or, you can start from one of our https://developer.lightbend.com/docs/akka-serverless/quickstart/index.html[quickstart example applications].

== Prerequisites

The following are required to develop services in Java:

Java:: Akka Serverless requires at least Java {minimum-java-version}, though we recommend using Java {recommended-java-version}, which has better support for running in containers.

Build tool:: Akka Serverless does not require any particular build tool, you can select your own.

protoc:: Since Akka Serverless is based on gRPC, you need a protoc compiler to compile gRPC protobuf descriptors. While this can be done by downloading, installing and running protoc manually, most popular build tools have a `protoc` plugin which will automatically compile protobuf descriptors during your build.

Docker:: Akka Serverless requires https://docs.docker.com/get-docker/[Docker {tab-icon}, window="new"] {minimum_docker_version} for building your service images. Most popular build tools have plugins that assist in building Docker images.


== Reference the Akka Serverless SDK

The following examples show how to install the SDK to build your services with Gradle, Maven, or sbt. The code generation tools include an Akka Serverless xref:kickstart.adoc[Maven archetype] that generates the recommended project structure, including a `.pom` file with the necessary references.

[.tabset]
Maven::
In your `.pom` file, add the following:
+
[source,xml,subs="attributes+"]
----
<dependencies>
    <dependency>
        <groupId>com.akkaserverless</groupId>
        <artifactId>akkaserverless-java-sdk</artifactId>
        <version>{akkaserverless-java-sdk-version}</version>
    </dependency>
    <dependency>
        <groupId>com.akkaserverless</groupId>
        <artifactId>akkaserverless-java-sdk-testkit</artifactId>
        <version>{akkaserverless-java-sdk-version}</version>
        <scope>test</scope>
    </dependency>
</dependencies>
----
Gradle::
In your `build.gradle` file, add the following:
+
[source,gradle,subs="attributes+"]
----
compile group: 'com.akkaserverless', name: 'akkaserverless-java-sdk', version: '{akkaserverless-java-sdk-version}'
----
sbt::
In your dependencies file, add the following:
+
[source,sbt,subs="attributes+"]
----
libraryDependencies ++= Seq(
    "com.akkaserverless" % "akkaserverless-java-sdk" % "{akkaserverless-java-sdk-version}",
    "com.akkaserverless" % "akkaserverless-java-sdk-testkit" % "{akkaserverless-java-sdk-version}" % Test
  )
----

== Configure JSON formatted logging
Akka Serverless supports JSON formatted logging to provide multi-line messages formatted in JSON syntax. Always use JSON formatted logging for your Akka Serverless projects to efficiently analyze and easily leverage logging information.

[TIP]
https://developer.lightbend.com/docs/akka-serverless/quickstart/cr-value-entity-java.html[Build and deploy the Quickstart example] to see JSON formatted logging in action.

JSON formatted logging is enabled by default in the projects created by the xref:kickstart.adoc[Akka Serverless Maven archetype]. It includes a dependency in `pom.xml` to `logback-json-classic` and a `logback.xml` file as shown here:

.src/main/resources/logback.xml
[source,java]
----
include::example$java-first-service/src/main/resources/logback.xml[]
----

In the `logback.xml` you may want to adjust the log level for different loggers (typically a package or class name).

For local development you can switch to the `STDOUT` appender to make the logs more readable, or use `<prettyPrint>true</prettyPrint>` in the `jsonFormatter`. Don't use `prettyPrint` in production since the logging infrastructure will not handle multi-line log messages.

NOTE: There is a separate `src/test/resources/logback-test.xml` that is used when running tests.

== Create a main class

Your main class will be responsible for creating the gRPC server, registering the services and components for it to serve, and starting it. The following code snippet shows an example that registers an Event Sourced Entity and starts the server:

[source,java,indent=0]
----
include::example$java-eventing-shopping-cart/src/main/java/shopping/Main.java[tag=RegisterEventSourcedEntity]
----


== What's next

This section provides details on how to accomplish common tasks in Java:

* xref:kickstart.adoc[]
* xref:proto.adoc[]
* xref:value-entity.adoc[Implementing Value Entities]
* xref:eventsourced.adoc[Implementing Event Sourced Entities]
* xref:replicated-entity.adoc[Implementing Replicated Entities]
* xref:actions.adoc[Actions (stateless functions)]
* xref:java:actions-as-controller.adoc[Actions as Controllers]
* xref:java:actions-publishing-subscribing.adoc[Publishing and Subscribing with Actions]
* xref:java:views.adoc[Implementing Views]
* xref:java:side-effects.adoc[Running Side Effects]
* xref:serialization.adoc[Serialization]
* link:{attachmentsdir}/api/index.html[Java API docs{tab-icon}, window="new"]
