= JWT in Java
:page-supergroup-java-scala: Language

include::partial$jwt-annotations.adoc[]


Kalix’s JWT support is configured by placing annotations on methods and messages in your service’s protobuf descriptor.

=== Bearer token validation

If you want to validate that a bearer token is present on a request, this can be done by annotating the gRPC method:

----
rpc MyMethod(MyRequest) returns (MyResponse) {
  option (kalix.method).jwt = {
    validate: BEARER_TOKEN
  };
};
----

Only requests that have a bearer token that can be validated by one of the configured keys for the service will be allowed, all other requests will be rejected. The bearer token must be supplied with requests using the Authorization header, like:

----
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
----

If you want to assert that only tokens from a particular issuer are allowed, that be can be done using the `bearer_token_issuer` option:

----
rpc MyMethod(MyRequest) returns (MyResponse) {
  option (kalix.method).jwt = {
    validate: BEARER_TOKEN
    bearer_token_issuer: "my-issuer"
  };
};
----

It is recommended that this be used in combination with specifying an issuer in your JWT key configuration, otherwise any of the services whose keys you trust may spoof the issuer.

Kalix will place the claims from the validated token into the request metadata, so you can access it from your service. All claims are prefixed with `_kalix-jwt-claim-`, so for example, if you want to read the subject claim, you can read the metadata header `_kalix-jwt-claim-sub`. String claims are passed unquoted. All other claim types, including arrays and objects, are passed using their JSON encoding