= Kickstart a Maven project


include::ROOT:partial$include.adoc[]
include::partial$attributes.adoc[]

The Akka Serverless code generation tools for Java help you to get started quickly. They include:

* A Maven archetype that generates the recommended project structure (including a `pom.xml`), a simple Counter service containing a Value Entity, and unit tests. A `README.md` explains what was created and how to work with the newly created service.

* A Maven plugin that runs the gRPC compiler and generates code stubs. You can modify the `.proto` and source files, and the Akka Serverless Maven plugin will not overwrite your work but will generate code stubs for the elements you changed or added.

The generated project also contains configuration for packaging and deploying the service.

== Prerequisites

Before running the code generation tools, make sure you have the following:

* JDK {minimum-java-version} or higher (JDK {recommended-java-version} is recommended)
* Apache Maven 3.6 or later
* Docker {minimum_docker_version} or higher (to run locally)

To deploy the generated service, you will need:

* An https://developer.lightbend.com/docs/akka-serverless/getting-started/lightbend-account.html[Akka Serverless account]
* An https://developer.lightbend.com/docs/akka-serverless/getting-started/projects.html#_create_a_project[Akka Serverless project]
* The https://developer.lightbend.com/docs/akka-serverless/getting-started/set-up-development-env.html#_akka_serverless_cli[akkasls] CLI
* A configured registry in which to publish the service container image. Refer to https://developer.lightbend.com/docs/akka-serverless/deploying/registries.html[Configuring registries] for more information on how to make your Docker registry available to Akka Serverless.

:sectnums:
== Configure Maven

Lightbend hosts the archetype in a Maven repository. You need to provide configuration that points to the Lightbend repository in one of the following ways:

* In a `settings.xml` file located in your home directory in a sub-directory named `.m2`. If you have an existing `settings.xml` file, either in your home directory or in `\{MAVEN_HOME}/conf`, add the `akkaserverless` profile element shown in the full example below and list it as `activeProfile` in the existing file.
* Your organization may have configured a proxy to be used to download Maven artifacts, such as Jfrog Artifactory. If you have difficulties updating `settings.xml` for a proxy, please consult your system administrator.

The following shows a complete `settings.xml` file configured to use the Lightbend repository:

[source,xml]
----
include::example$settings.xml[]
----

== Generate and build the Akka Serverless project

The Maven archetype prompts you to specify the project's group ID, name and version interactively. Run it using the commands shown for your OS.

[sidebar]
In IntelliJ, you can skip the command line. Open the IDE, select
*File > New > Project*, and click to activate *Create from archetype*. Use the UI to locate the archetype and fill in the blanks.

Follow these steps to generate and build your project:

. From a command window, run the archetype in a convenient location:
+
[.tabset]
Linux or macOS::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate \
  -DarchetypeGroupId=com.lightbend \
  -DarchetypeArtifactId=maven-archetype-akkasls \
  -DarchetypeVersion=LATEST
----
--
Windows 10+::
+
--
[source,command window, subs="attributes"]
----
mvn archetype:generate ^
  -DarchetypeGroupId=com.lightbend ^
  -DarchetypeArtifactId=maven-archetype-akkasls ^
  -DarchetypeVersion=LATEST
----
--


. Navigate to the new project directory.

. Enter `mvn compile` to generate and compile the sources.

As you develop your own logic, you can change the `.proto` file definitions and build again. The build generates classes and tests as you develop the project, but will not overwrite your work.

== Examine the Maven project

The archetype created the source files outlined in xref:developing:development-process-java.adoc[]. Take a look at the pieces it provided for you:

=== Descriptors for the service interface and domain model

Akka Serverless uses gRPC Protocol Buffers language to describe the service interface and the entity domain model. The archetype generates a `CounterService` API implemented as a https://developer.lightbend.com/docs/akka-serverless/reference/glossary.html#value_entity[Value Entity]. The entity descriptors include:

- `src/main/proto/value-entities/counter_api.proto` the service API to be used by clients
- `src/main/proto/value-entities/counter_domain.proto` the domain model of the Value Entity's state

[.tabset]
Default API protobuf file::
+
.src/main/proto/value-entities/counter_api.proto
--
[source,protobuf]
----
include::example$archetype/first-service/src/main/proto/value-entities/counter_api.proto[]
----
--
Default domain protobuf file::
+
.src/main/proto/value-entities/counter_domain.proto
--
[source,protobuf]
----
include::example$archetype/first-service/src/main/proto/value-entities/counter_domain.proto[]
----
--

For more information on descriptors, see xref:java:proto.adoc[].

=== Component implementation

For the default service description in the archetype, the plugin creates an abstract base class (eg. `CounterInterface`) which always reflects the latest service description.

IMPORTANT: Do not modify the base class as it is regenerated on each invocation of `mvn compile`

On the first build, the plugin creates a Value Entity implementation class where you implement the business logic for command handlers (eg. `CounterImpl`) .

.src/main/java/com/example/domain/CounterImpl.java
[source,java]
----
include::example$archetype/first-service/src/main/java/com/example/domain/CounterImpl.java[]
----

The Maven plugin provides the `Main` class implementation that registers service components with Akka Serverless.

.src/main/java/com/example/Main.java
[source,java]
----
include::example$archetype/first-service/src/main/java/com/example/Main.java[]
----

This class is the entry point for running Akka Serverless within the container.

For more details see xref:java:value-entity.adoc[].

=== Unit and integration tests

The Akka Serverless Maven plugin creates a unit test stub for each class. Use this stub as a starting point to test the logic in your implementation. The Akka Serverless Java SDK test kit supports both link:https://junit.org/junit4/[JUnit 4] and link:https://junit.org/junit5/[JUnit 5].

.src/test/java/com/example/domain/CounterTest.java
[source,java]
----
include::example$archetype/first-service/src/test/java/com/example/domain/CounterTest.java[]
----

Use the `verify` command to run all unit tests.

[source,bash]
----
mvn verify
----

For more details, see xref:java:value-entity.adoc#_testing_the_entity[Testing the entity].

The Maven plugin also provides you with an initial setup for integration tests based on the Akka Serverless Java SDK test kit which leverages link:https://www.testcontainers.org/[TestContainers] and link:https://junit.org/junit4/[JUnit].

.src/it/java/com/example/domain/CounterIntegrationTest.java
[source,java]
----
include::example$archetype/first-service/src/it/java/com/example/domain/CounterIntegrationTest.java[]
----

The Maven failsafe plugin runs the integration tests when the `it` profile is enabled via `-Pit`.

[source,bash]
----
mvn verify -Pit
----

== Package service

The Maven project is configured to package your service into a Docker image which can be deployed to Akka Serverless. The Docker image name can be changed in the `pom.xml` file's `properties` section. Update this file to publish your image to your Docker repository.

The recommended version is JDK {recommended-java-version} and the image is based on the link:https://adoptium.net/[Eclipse Adoptium] JDK image (formerly Adopt OpenJDK). Choose a different image in the `docker-maven-plugin` configuration  `pom.xml` file.

[source,bash]
----
mvn package
----

TIP: For more details see xref:developing:development-process-java.adoc#_package_service[Development Process - Package service].

== Run locally

You can run your service locally for manual testing via HTTP or gRPC requests. To run your application locally, you need to initiate the Akka Serverless proxy. The included `docker-compose` file contains the configuration required to run the proxy for a locally running application.

To start the proxy, run the following command from the project directory:

[.tabset]
MacOS, Windows::
+
--
[source,bash]
----
docker compose up
----
--
Linux::
+
--
NOTE: On Linux this requires Docker 20.10 or later (https://github.com/moby/moby/pull/40007), or for a `USER_FUNCTION_HOST` environment variable to be set manually.
[source,bash]
----
docker compose -f docker-compose.yml -f docker-compose.linux.yml up
----
--

Use the `exec-maven-plugin` to start the application locally with the following command:

[source,bash]
----
mvn compile exec:java
----

== Deploy to Akka Serverless

To deploy your service to Akka Serverless:

. Update the `dockerImage` property in the `pom.xml` to point at your Docker registry.

. In your command window, set your Akka Serverless project to be the current project:
+
[source, command window]
----
akkasls config set project <project-name>
----

. Run `mvn deploy`, which conveniently packages and publishes your Docker image prior to deployment.
