= Writing gRPC descriptors

include::ROOT:partial$include.adoc[]
include::partial$attributes.adoc[]

Akka Serverless SDKs support `protobuf` descriptors in the https://developers.google.com/protocol-buffers/docs/proto3[Proto3 {tab-icon}, window="new-tab"] Protocol Buffers language. You define command messages, data associated with Entities, and events in `.proto` files. From these definitions, the gRPC compiler creates client and server side code that saves work for you and enables Akka Serverless to serialize message data.

We recommend that you define your service API and events and data associated with components separately. This allows business logic to evolve independently of the public interface. This page walks you through elements in an example `shoppingcart_api.proto` file and the associated `shoppingcart_domain.proto` file.

== The service proto file

The first line of our `shoppingcart_api.proto` file defines the version of Protocol Buffer syntax:

.src/main/proto/shoppingcart/shoppingcart_api.proto
[source,proto]
----
include::example$java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_api.proto[tag=proto_syntax]
----

The following imports provide Akka Serverless and gRPC functionality:

.src/main/proto/shoppingcart/shoppingcart_api.proto
[source,proto]
----
include::example$java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_api.proto[tag=proto_imports]
----

The `package` specifies a namespace for this `proto` file and its imports--names must be unique within each namespace:

.src/main/proto/shoppingcart/shoppingcart_api.proto
[source,proto]
----
include::example$java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_api.proto[tag=proto_package]
----

=== Messages

You define messages that can be sent to or returned from the service. Each message for an Entity that is input to a RPC command, *must* contain an Entity key. In the example, this includes `AddLineItem`, `RemoveLineItem`, and `GetShoppingCart` where the `user_id` is the `(akkaserverless.field).entity_key`. Akka Serverless uses the `entity_key` to know which instance of an Entity a message is for. If more than one field is specified as an Entity key, the fields are concatenated together. Akka Serverless serializes Entity keys to strings.

.src/main/proto/shoppingcart/shoppingcart_api.proto
[source,proto]
----
include::example$java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_api.proto[tag=proto_messages]
----

=== Service

This section of the `.proto` file declares the API of the service itself, along with each function or method and their parameters and return types. When a command is received for a given Entity key, Akka Serverless will establish a gRPC streamed call to the service implementation using that Entity's type's protocol--if one isn't already established. Any commands received for the Entity key will be sent through that call.

The `AddItem` and `RemoveItem` methods have no return value (the `Empty` type).

See <<_transcoding_http>> for an explanation of the HTTP annotations.

.src/main/proto/shoppingcart/shoppingcart_api.proto
[source,proto]
----
include::example$java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_api.proto[tag=proto_service]
----
<1> See <<_transcoding_http>> below
<2> See <<_transcoding_http>> below
<3> See <<_transcoding_http>> below


== The domain proto file

The `shoppingcart_domain.proto` file specifies the state and messages for an Event Sourced Entity. It defines the gRPC version:

.src/main/proto/shoppingcart/shoppingcart_domain.proto
[source,proto]
----
include::example$java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_domain.proto[tag=proto_syntax]
----

It only needs to include the import for `akkaserverless/annotations.proto`:

.src/main/proto/shoppingcart/shoppingcart_domain.proto
[source,proto]
----
include::example$java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_domain.proto[tag=proto_imports]
----

The following defines the `ShoppingCart` Entity state:

.src/main/proto/shoppingcart/shoppingcart_domain.proto
[source,proto]
----
include::example$java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_domain.proto[tag=proto_state]
----

It includes the messages that define the entity state:

.src/main/proto/shoppingcart/shoppingcart_domain.proto
[source,proto]
----
include::example$java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_domain.proto[tag=proto_messages]
----


[#_transcoding_http]
== Transcoding HTTP

Akka Serverless supports transcoding gRPC to HTTP/JSON, using the Google transcoding annotations described https://cloud.google.com/endpoints/docs/grpc/transcoding[here]. You can use transcoding to consume your Entities' gRPC interfaces using HTTP/JSON.

In the example below, the optional transcoding of the service to bind the various endpoints to HTTP is highlighted with annotations.

[source,proto]
----
include::example$java-valueentity-shopping-cart/src/main/proto/shoppingcart/shoppingcart_api.proto[tag=proto_service]
----
<1> This extra annotation specifies that you can call this endpoint using the POST method with the URI `/cart/\{user_id}/items/add`, where `\{user_id}` is the actual user id we want the cart for.
<2> A URL that accepts a POST method to remove a line item.
<3> A more complex example where the first `get` URI retrieves the whole cart, and the second retrieves the items in the cart.
