= Serialization

Akka Serverless functions serve gRPC interfaces, and naturally the input and output messages are protobuf messages that get serialized to the protobuf wire format. However, in addition to these messages, there are a number of places where Akka Serverless needs to serialize other objects, for persistence and replication. This includes:

* Event Sourced Entity xref:eventsourcedentities.adoc#persistence-types-and-serialization[events and snapshots].
* Replicated Entity xref:replicatedentities.adoc#sets-and-maps[map keys and set elements], and xref:replicatedentities.adoc#registers[LWWRegister values].

Akka Serverless supports a number of types and serialization options for these values.

== Primitive types

Akka Serverless supports serializing the following primitive types:

[cols="a,a"]
|===
| Protobuf type | Java type

| string
| java.lang.String

| bytes
| com.google.protobuf.ByteString

| int32
| java.lang.Integer

| int64
| java.lang.Long

| float
| java.lang.Float

| double
| java.lang.Double

| bool
| java.lang.Boolean

|===

The details of how these are serialized can be found xref:contribute:serialization.adoc#primitive-values[here].

== JSON

Akka Serverless uses https://github.com/FasterXML/jackson[Jackson] to serialize JSON. Any classes that are annotated with link:{attachmentsdir}/api/com/akkaserverless/javasdk/Jsonable.html[`@Jsonable`] will be serialized to and from JSON using Jackson.

The serialization of JSON values is described in xref:contribute:serialization.adoc#json-values[Language support / Akka Serverless serialization convention].

Note that if you are using JSON values in Replicated Entity sets or maps, the serialization of these values **must** be stable. This means you must not use maps or sets in your value, and you should define an explicit ordering for the fields in your objects, using the http://fasterxml.github.io/jackson-annotations/javadoc/2.9/com/fasterxml/jackson/annotation/JsonPropertyOrder.html[`@JsonPropertyOrder`] annotation. This constraint is explained in xref:concepts:crdts.adoc[CRDTs].
