= Serialization options for Java services

include::ROOT:partial$include.adoc[]

You do not need to handle serialization for messages. Akka Serverless functions serve gRPC interfaces, and the input and output messages are `protobuf` messages that get serialized to the `protobuf` format.

The gRPC services are also exposed as HTTP endpoints with JSON messages. See xref:proto.adoc#_transcoding_http[Transcoding HTTP].

For messages consumed from or published to topics it can be needed to use another format than `protobuf`. Akka Serverless provides a utility to serialize and deserialize JSON messages.

== Primitive types

Akka Serverless supports serializing the following primitive types:

[cols="a,a"]
|===
| Protobuf type | Java type

| string
| java.lang.String

| bytes
| com.google.protobuf.ByteString

| int32
| java.lang.Integer

| int64
| java.lang.Long

| float
| java.lang.Float

| double
| java.lang.Double

| bool
| java.lang.Boolean

|===

== JSON

Akka Serverless provides the link:{attachmentsdir}/api/com/akkaserverless/javasdk/JsonSupport.html[`JsonSupport` {tab-icon}, window="new"] utility to serialize and deserialize JSON messages.

A `proto` definition of an Action that consumes JSON messages and produces JSON messages can look like this:

[source,proto,indent=0]
.src/main/proto/actions/json_api.proto
----
include::java:example$java-doc-snippets/src/main/proto/actions/json_api.proto[tag=service]
----
<1> When consuming JSON messages from a topic the input type must be `google.protobuf.Any`.
<2> When producing a JSON message to a topic the return type must be `google.protobuf.Any`.

NOTE: The `type_url` in the `google.protobuf.Any` must start with `json.akkaserverless.com/`. The suffix of the `type_url` is a type hint of the concrete message type that is encoded.

The corresponding implementation class:

[source,java,indent=0]
.src/main/java/com/example/json/MyServiceAction.java
----
include::java:example$java-doc-snippets/src/main/java/com/example/json/MyServiceAction.java[tag=action]
----
<1> Decode the JSON message to a Java class `JsonKeyValueMessage`.
<2> Convert the Protobuf message `KeyValue` to a Java class `JsonKeyValueMessage`.
<3> Encode the Java class `JsonKeyValueMessage` to JSON.

Akka Serverless uses https://github.com/FasterXML/jackson[Jackson] to serialize JSON.

include::partial$topic-eventing-cloudevent.adoc[]