= Service to Service Eventing
:page-aliases: spring:service-to-service.adoc

include::ROOT:partial$include.adoc[]


Kalix provides brokerless at-least-once event delivery across Kalix services through the Service to Service eventing.

The source of the events is an xref:event-sourced-entities.adoc[Event Sourced Entity]. Its events can be published as a stream and consumed by another Kalix service without the need to set up a message broker.

Note:: For eventing from an entity inside the same Kalix service as the consuming component, use regular
xref:actions-publishing-subscribing.adoc[Subscription to the entity] instead of Service to Service eventing.

== Event Producer

The event producer controls which entity to publish events for. Each entity published is identified by a stream `id` so
that one Kalix service can publish more than one of the entity types it contains.

[source,java,indent=0]
.src/main/java/customer/api/CustomerEventsService.java
----
include::example$java-spring-eventsourced-customer-registry/src/main/java/customer/api/CustomerEventsService.java[tag=producer]
----
<1> Identifying which event sourced entity to publish events for.
<2> Ignore any event types not handled by a method and move on with the event stream, rather than fail which is the default.
<3> Public identifier for consumers of this stream.
<4> Allowing access from other Kalix services, but not the public internet.
<5> All methods on the service are transformer methods for turning internal event message types into public API message types for other services to consume.

== Event Consumer

The consumer can be an Action or a View, annotated with `@Subscribe.Stream` with a `service` identifying the publishing service, and the `id` of the stream to subscribe to.

We then define a component subscribing to the service to service publisher. In this example we do that with a View:

[.tabset]
Java::
+
[source,java,indent=0]
.src/main/java/customer/views/CustomersByNameView.java
----
include::example$java-spring-eventsourced-customer-registry-subscriber/src/main/java/customer/views/CustomersByNameView.java[tag=view]
----
<1> Annotate the component with `@Subscribe.Stream` to subscribe to an event stream from another Kalix service.
<2> The name of the Kalix service publishing the event stream.
<3> The public identifier of the specific stream from the publisher.
<4> One update method per message type that the stream may contain.

TIP: If you're looking to test this locally, you will likely need to run the 2 services in different ports. For more details, consult https://docs.kalix.io/developing-services/running-locally.html#_running_multiple_services[Running multiple services].

=== Deployment dependent source of events

It is possible to use environment variables to control the name of the service that a consumer consumes from, this is useful for example for using the same image in staging and production deployments but having them consume from different source services.

Referencing environment variables is done with the syntax `$\{VAR_NAME}` in the `service` parameter if the `@Subscribe.Stream` annotation.

WARNING: Changing the `service` name after it has once been deployed means the consumer will start over from the beginning of the event stream.

See https://docs.kalix.io/kalix/kalix_services_deploy.html[kalix service deploy] for details on how to set environment variables when deploying a service.
