= Consuming Akka Serverless Services using Spring

Akka Serverless services are exposed using REST and gRPC interfaces.
This guide walks you through the process of consuming these services using Spring.
This guide uses sample(s) from following repository:

== Sample

Please refer to following Spring Boot sample application which has support for both REST and gRPC consumers.

`java-valueentity-counter-spring-client` module under samples link in the following repo :

* https://github.com/lightbend/akkaserverless-java-sdk/tree/main/samples[Spring Client Java Value Entity Counter,window="new"]

Following is the Akka Serverless application to which above application acts as Spring Client.

`java-valueentity-counter`  module under samples link in the following repo :

* https://github.com/lightbend/akkaserverless-java-sdk/tree/main/samples/java-valueentity-counter[Java Value Entity Counter,window="new"]

== Running Spring Client Sample Locally

Following steps guide you to run the spring client application in your local environment.

- Please make sure you have the following installed:
    * JDK 11 or later
    * Apache Maven 3.6 or later
    * Docker 20.10.8 or higher
- git clone the following repo https://github.com/lightbend/akkaserverless-java-sdk[Akka Serverless Java SDK,window="new"]
- Navigate to `akkaserverless-java-sdk/samples/java-valueentity-counter/`
- On README.md `akkaserverless-java-sdk/samples/java-valueentity-counter/README.md` file navigate to `Running Locally` section and run the project locally in a new Command line Window or IDE.
- In a separate new window on Command Line or IDE, Navigate to `akkaserverless-java-sdk/samples/java-valueentity-counter-spring-client/`
- On README.md `akkaserverless-java-sdk/samples/java-valueentity-counter-spring-client/README.md` file navigate to `Running Locally` section and run the project locally in a new Command line Window or IDE.
- On README.md `akkaserverless-java-sdk/samples/java-valueentity-counter-spring-client/README.md` file navigate to `Exercise the service` section and run few endpoints locally in a new Command line Window or IDE.


== Consuming REST endpoints

Create a separate new Spring Boot project.

For consuming the REST endpoints, we can use various REST client libraries provided via spring or others.
For instance libraries like RestTemplate, Webflux etc.

In this guide we are looking at steps using a Spring client using Webflux library.

The Spring Boot application used in this sample is consuming REST APIs and gRPC Services exposed via Akka Serverless (java-valuentity-counter) and the Spring Boot application will work as a simple proxy to an Akka Serverless application.

----
 <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-webflux</artifactId>
 </dependency>
----

Steps:

- Define a Webclient and Configure it to use Akka Serverless service's host and port.

[source,java,indent=0]
.src/main/java/com/example/client/spring/rest/config/WebClientConfig.java
----
include::example$java-valueentity-counter-spring-client/src/main/java/com/example/client/spring/rest/config/WebClientConfig.java[tag=webclientconfig]
----

- Using the above defined client call a relevant API in Akka Serverless service.
For e.g. GET, POST etc. endpoints.

[source,java,indent=0]
.src/main/java/com/example/client/spring/rest/service/CounterServiceImpl.java
----
include::example$java-valueentity-counter-spring-client/src/main/java/com/example/client/spring/rest/service/CounterServiceImpl.java[tag=getCurrentCounterCall]
----

== Consuming gRPC Services

Create a separate new Spring Boot project.

For Consuming gRPC Services of Akka Serverless service we need to generate grpc client stubs.

You could use protobuf maven plugins for stub creation.

The Spring Boot application used in this sample is consuming REST APIs and gRPC Services exposed via Akka Serverless (java-valuentity-counter) and the Spring Boot application will work as a simple proxy to an Akka Serverless application.

----
<groupId>org.xolstice.maven.plugins</groupId>
<artifactId>protobuf-maven-plugin</artifactId>
----

Following steps walks you through steps for creating

- Get all the proto files from relevant akka serverless service and copy under `src/main/proto` folder.  Remove all the akka serverless annotations from the proto files. For instance `[(akkaserverless.field).entity_key = true]` and `akkaserverless.codegen` etc.
- Generate client stubs by running `mvn compile` or `mvn protobuf:compile`
- Define a Message channel with host and port of akka serverless service

[source,java,indent=0]
.src/main/java/com/example/client/spring/rest/config/GrpcClientConfig.java
----
include::example$java-valueentity-counter-spring-client/src/main/java/com/example/client/spring/rest/config/GrpcClientConfig.java[tag=grpcclientconfig]
----

- Build client service via connecting message channel and then using relevant client stub call the desired service/method.

[source,java,indent=0]
.src/main/java/com/example/client/spring/rest/service/GrpcClientService.java
----
include::example$java-valueentity-counter-spring-client/src/main/java/com/example/client/spring/rest/service/GrpcClientService.java[tag=decreaseCounterCall]
----

