= Using Spring to consume Akka Serverless Services

This guide provides a simple example of how a Spring client can be built to interact with an Akka Serverless Service. 

== What You Will Build

You will build an Akka Serverless Service along with a Spring client to interact with that Service.

The Akka Serverless Service will create, read, update and persist simple counters.

The Spring client will expose the functionality of the Akka Serverless Service as a REST API.

== What You Need

- About 15 minutes
- A favorite text editor or IDE
- https://adoptium.net/[JDK 11] or later
- https://maven.apache.org/download.cgi[Apache Maven 3.6] or later
- https://www.docker.com/[Docker 20.10.8] or higher

== How to get started

To get started, do the following:

- https://github.com/lightbend/akkaserverless-java-sdk/archive/refs/heads/main.zip[Download] and unzip the source repository for this guide, or clone it using Git:

`git clone https://github.com/lightbend/akkaserverless-java-sdk.git`

- cd into `akkaserverless-java-sdk/samples/java-valueentity-counter`

== Build and Run the Akka Serverless Service Locally

With the source repository downloaded, you can build and run the Akka Serverless Service locally. 

Run the Akka Serverless Service using Maven:

`mvn compile exec:exec`

You should see output similar to the following:

```
[INFO] --- exec-maven-plugin:3.0.0:exec (default-cli) @ valueentity-counter ---
{"timestamp":"2022-03-02T23:38:12.174Z","thread":"main","logger":"com.example.Main","message":"starting the Akka Serverless service","context":"default","severity":"INFO"}
{"timestamp":"2022-03-02T23:38:12.829Z","thread":"akkaserverless-akka.actor.default-dispatcher-2","logger":"akka.event.slf4j.Slf4jLogger","message":"Slf4jLogger started","context":"default","severity":"INFO"}
```

== Build and Run the Akka Serverless proxy locally

In another terminal window, run the Akka Serverless proxy using Docker:

`docker compose up`

You should see output similar to the following:app-name: 

```
akka-serverless-proxy_1   | {"timestamp":"2022-03-02T23:40:40.766Z","mdc":{"akkaAddress":"akka://akkaserverless-proxy@172.21.0.2:25520","akkaSource":"akka://akkaserverless-proxy/user/discovery-manager","sourceActorSystem":"akkaserverless-proxy"},"logger":"com.akkaserverless.proxy.DiscoveryManager","message":"gRPC proxy started at 0.0.0.0:9000","severity":"INFO","thread":"akkaserverless-proxy-akka.actor.default-dispatcher-8"}
```

== Create a Spring WebClient

cd into `akkaserverless-java-sdk/samples/java-valueentity-counter-spring-client`.

Now you can create a `WebClient`. You need to configure the WebClient to use the Akka Serverless Service's host and port. The following listing (from `akkaserverless-java-sdk/samples/java-valueentity-counter-spring-client/src/main/java/com/example/client/spring/rest/config/WebClientConfig.java`) shows how to do so:

[source,java,indent=0]
.src/main/java/com/example/client/spring/rest/config/WebClientConfig.java
----
include::example$java-valueentity-counter-spring-client/src/main/java/com/example/client/spring/rest/config/WebClientConfig.java[tag=webclientconfig]
----

== Create a Spring Service

The `CounterServiceImpl` shown in the following listing (from `akkaserverless-java-sdk/samples/java-valueentity-counter-spring-client/src/main/java/com/example/client/spring/rest/service/CounterServiceImpl.java`) uses the Spring client to interact with the Akka Serverless Service and return new instances of `Mono<String>`:

[source,java,indent=0]
.src/main/java/com/example/client/spring/rest/service/CounterServiceImpl.java
----
include::example$java-valueentity-counter-spring-client/src/main/java/com/example/client/spring/rest/service/CounterServiceImpl.java[tag=getCurrentCounterCall]
----


== Consuming REST endpoints

Create a separate new Spring Boot project.

For consuming the REST endpoints, we can use various REST client libraries provided via spring or others.
For instance libraries like RestTemplate, Webflux etc.

In this guide we are looking at steps using a Spring client using Webflux library.

The Spring Boot application used in this sample is consuming REST APIs and gRPC Services exposed via Akka Serverless (java-valuentity-counter) and the Spring Boot application will work as a simple proxy to an Akka Serverless application.

----
 <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-webflux</artifactId>
 </dependency>
----

Steps:

- Define a Webclient and Configure it to use Akka Serverless service's host and port.

[source,java,indent=0]
.src/main/java/com/example/client/spring/rest/config/WebClientConfig.java
----
include::example$java-valueentity-counter-spring-client/src/main/java/com/example/client/spring/rest/config/WebClientConfig.java[tag=webclientconfig]
----

- Using the above defined client call a relevant API in Akka Serverless service.
For e.g. GET, POST etc. endpoints.

[source,java,indent=0]
.src/main/java/com/example/client/spring/rest/service/CounterServiceImpl.java
----
include::example$java-valueentity-counter-spring-client/src/main/java/com/example/client/spring/rest/service/CounterServiceImpl.java[tag=getCurrentCounterCall]
----

== Consuming gRPC Services

Create a separate new Spring Boot project.

For Consuming gRPC Services of Akka Serverless service we need to generate grpc client stubs.

You could use protobuf maven plugins for stub creation.

The Spring Boot application used in this sample is consuming REST APIs and gRPC Services exposed via Akka Serverless (java-valuentity-counter) and the Spring Boot application will work as a simple proxy to an Akka Serverless application.

----
<groupId>org.xolstice.maven.plugins</groupId>
<artifactId>protobuf-maven-plugin</artifactId>
----

Following steps walks you through steps for creating

- Get all the proto files from relevant akka serverless service and copy under `src/main/proto` folder.  Remove all the akka serverless annotations from the proto files. For instance `[(akkaserverless.field).entity_key = true]` and `akkaserverless.codegen` etc.
- Generate client stubs by running `mvn compile` or `mvn protobuf:compile`
- Define a Message channel with host and port of akka serverless service

[source,java,indent=0]
.src/main/java/com/example/client/spring/rest/config/GrpcClientConfig.java
----
include::example$java-valueentity-counter-spring-client/src/main/java/com/example/client/spring/rest/config/GrpcClientConfig.java[tag=grpcclientconfig]
----

- Build client service via connecting message channel and then using relevant client stub call the desired service/method.

[source,java,indent=0]
.src/main/java/com/example/client/spring/rest/service/GrpcClientService.java
----
include::example$java-valueentity-counter-spring-client/src/main/java/com/example/client/spring/rest/service/GrpcClientService.java[tag=decreaseCounterCall]
----

