= Implementing Value Entities
:page-aliases: spring:value-entity.adoc

include::ROOT:partial$include.adoc[]

https://docs.kalix.io/reference/glossary.html#value_entity[Value Entities] persist state on every change and thus Kalix needs to serialize that data to send it to the underlying data store. However, we recommend that you do not persist your service's public API messages. Persisting private API messages may introduce some overhead when converting from a public message to an internal one but it allows the logic of the service public interface to evolve independently of the data storage format, which should be private.

NOTE: Kalix _Value Entities_ have nothing in common with the domain-driven design concept of _Value Objects_. The _Value_ in the name refers to directly modifying a value for the entity's state - in contrast to https://docs.kalix.io/reference/glossary.html#event_sourced_entity[Event-sourced Entities] that persist events and the entity state is derived from them.

The steps necessary to implement a Value Entity include:

. Defining the API and model the entity's state.
. Implementing behavior in command handlers.
. Creating and initializing the Entity.

The following sections walk through these steps using a counter service as an example.

== Modeling the Entity

As mentioned above, to help us illustrate a Value Entity, you will be implementing a Counter service. For such service, you will want to be able to set the initial counter value but also to increase the counter modifying its state. The state will be a simple `Integer` but you will use a wrapper class `Number` for our API, as shown below:

.src/main/java/com/example/Number.java
[source,java]
----
include::example$java-spring-valueentity-counter/src/main/java/com/example/Number.java[]
----

include::partial$entity-ids.adoc[]

include::java-protobuf:partial$effects-value-entity.adoc[]

See also xref:java:development-process.adoc#_effects_api[Understanding what an Effect is]

[#entity-behavior]
== Implementing behavior

Now that you have a good idea of what we want to build and what its API looks like, you will need to:

- Declare your entity and pick an entity id (it needs to be a unique identifier).
- Define an access point (i.e. a route path) to your entity.
- Implement how each command is handled.

Let us start by showing how to create the Value Entity:

.src/main/java/com/example/CounterEntity.java
[source,java]
----
include::example$java-spring-valueentity-counter/src/main/java/com/example/CounterEntity.java[tags=declarations]
----
<1> Every Entity must be annotated with `@TypeId` with a stable identifier. This identifier should be unique among the different existing entities within a Kalix application.
<2> The `@Id` value should be unique per entity and map to some field being received on the route path, in this example it's the `counter_id`.
<3> The `CounterEntity` class should extend `kalix.javasdk.valueentity.ValueEntity`.
<4> The initial state of each counter is defined as 0.

=== Updating state

We will now show how to add the command handlers for supporting the two desired operations (`set` and `plusOne`). Command handlers are implemented as methods on the entity class but are also exposed for external interactions and always return an `Effect` of some type.

.src/main/java/com/example/CounterEntity.java
[source,java,indent=0]
----
include::example$java-spring-valueentity-counter/src/main/java/com/example/CounterEntity.java[tags=behaviour]
----
<1> Expose the `set` command handler on path `/counter/\{counter_id\}/set` as a PUT endpoint where `counter_id` will be its unique identifier.
<2> Set the new counter value to the value received as body of the command request.
<3> Reply with the new counter value wrapped within a `Number` object.
<4> The method is accessible as a POST endpoint on `/counter/\{counter_id\}/plusone`, where `counter_id` will be its unique identifier.
<5> `plusOne` increases the counter by adding 1 to the current state.
<6> Finally, using the Effect API, you instruct Kalix to persist the new state, and build a reply with the wrapper object.

NOTE: The `counter_id` parameter matches the `@Id` value. Also, for this example, we have opted to always repeat the common route `/counter/\{counter_id\}` for each command but a simpler option could be to use a `@RequestMethod("/counter/\{counter_id\}")` at class level.

[#deleting-state]
=== Deleting state

The next example shows how to delete a Value Entity state by returning special `deleteEntity()` effect.

.src/main/java/com/example/CounterEntity.java
[source,java,indent=0]
----
include::example$java-spring-valueentity-counter/src/main/java/com/example/CounterEntity.java[tags=delete]
----
<1> We delete the state by returning an `Effect` with `effects().deleteEntity()`.

When you give the instruction to delete the entity it will still exist with an empty state from some time. The actual removal happens later to give downstream consumers time to process the change. By default, the existence of the entity is completely cleaned up after a week.

It is not allowed to make further changes after the entity has been "marked" as deleted. You can still handle read requests of the entity until it has been completely removed, but be the current state will be empty.

NOTE: If you want to make changes after deleting the state you should use the `updateState` effect with an empty state instead of using `deleteEntity`.

It is best to not reuse the same entity id after deletion, but if that happens after the entity has been completely removed it will be instantiated as a completely new entity without any knowledge of previous state.

Note that xref:views.adoc#ve_delete[deleting View state] must be handled explicitly.

=== Retrieving state

The following example shows how to implement a simple endpoint to retrieve the current state of the entity, in this case the value for a specific counter.

.src/main/java/com/example/CounterEntity.java
[source,java,indent=0]
----
include::example$java-spring-valueentity-counter/src/main/java/com/example/CounterEntity.java[tags=query]
----
<1> Expose the `get` query handler on path `/counter/\{counter_id\}` as a GET endpoint where `counter_id` will be its unique identifier.
<2> Reply with the current state wrapped within a `Number`.

== Running Side Effects

An Entity may also emit one or more side effects. A side effect is something whose result has no impact on the result of the current command--if it fails, the current command still succeeds. The result of the side effect is therefore ignored. When used from inside an Entity, side effects are only performed after the successful completion of any state actions requested by the command handler.

See this xref:actions.adoc#_running_side_effects[dedicated section regarding Actions], for more details.

== Testing the Entity

include::partial$testing-entity.adoc[]


=== Unit tests

The following snippet shows how the `ValueEntityTestKit` is used to test the `CountertEntity` implementation. Kalix provides two main APIs for unit tests, the `ValueEntityTestKit` and the `ValueEntityResult`. The former gives us the overall state of the entity and the ability to call the command handlers while the latter only holds the effects produced for each individual call to the Entity.

./src/test/java/com/example/CounterTest.java
[source,java,indent=0]
----
include::example$java-spring-valueentity-counter/src/test/java/com/example/CounterTest.java[tags=example]
----
<1> Creates the TestKit passing the constructor of the Entity.
<2> Calls the method `set` from the Entity in the `ValueEntityTestKit` with value `10`.
<3> Asserts the reply value is `10`.
<4> Calls the method `plusOne` from the Entity in the `ValueEntityTestKit` and assert reply value of `11`.
<5> Asserts the state value after both operations is `11`.

NOTE: The `ValueEntityTestKit` is stateful, and it holds the state of a single entity instance in memory. If you want to test more than one entity in a test, you need to create multiple instance of `ValueEntityTestKit`.

=== Integration tests

The skeleton of an Integration Test is generated for you if you use the archetype to start your Kalix app. Let's see what it could look like to test our Counter Entity:

./src/it/java/com/example/CounterIntegrationTest.java
[source,java,indent=0]
----
include::example$java-spring-valueentity-counter/src/it/java/com/example/CounterIntegrationTest.java[tags=sample-it]
----
<1> Note the test class must extend `KalixIntegrationTestKitSupport`.
<2> A built-in web-client is provided to interact with the components.
<3> Request to get the current value of the counter named `bar`. Initial value of counter is expected to be `0`.
<4> Request to increase the value of counter `bar`. Response should have value `1`.
<5> Explicit `GET` request to retrieve value of `bar` that should be `1`.

NOTE: The integration tests in samples are under in a specific project profile `it` and can be run using `mvn verify -Pit`.
