= Implementing Views
:page-aliases: spring:views.adoc

include::ROOT:partial$include.adoc[]

You can access a single https://docs.kalix.io/reference/glossary.html#entity[Entity] with its https://docs.kalix.io/reference/glossary.html#component_id[id]. But sometimes this is not enough. You might want to retrieve multiple Entities, or retrieve them using an attribute other than the key. Kalix https://docs.kalix.io/reference/glossary.html#view[Views] allow you to achieve this. You can create one View for each, so that it is optimized for a specific query, or combine multiple queries into a single View.

Views can be defined from any of the following:

* xref:value-entity[Value Entity state changes]
* xref:event-sourced-entity[Event Sourced Entity events]
* xref:topic-view[Messages received from subscribing to topics on a broker]

The remainder of this page describes:

* <<#relational-projection>>
* <<#changing>>
* <<#query>>

IMPORTANT: Be aware that Views are not updated immediately when Entity state changes. Kalix does update Views as quickly as possible. It is not instant but eventually all changes will become visible in the query results. View updates might also take more time during failure scenarios than during normal operation.

include::java-protobuf:partial$effects-view.adoc[]

See also xref:java:development-process.adoc#_effects_api[Understanding what an Effect is]

[#value-entity]
== Creating a View from a Value Entity

Consider an example of a Customer Registry service with a `customer` Value Entity. When `customer` state changes, the entire state is emitted as a value change. Value changes update any associated Views.
To create a View that lists customers by their name, <<_define_the_view, define the view>> for a service that selects customers by name and associates a table name with the View. The table is created and used by Kalix to store the View.


This example assumes the following `Customer` exists:

[source,java,indent=0]
.src/main/java/customer/api/Customer.java
----
include::example$java-spring-customer-registry-views-quickstart/src/main/java/customer/domain/Customer.java[tags=class]
----

As well as a Value Entity service `CustomerEntity.java` that will produce the state changes consumed by the View. You can consult xref:value-entity#entity-behavior[Value Entity] documentation on how to create such an entity if in need.


=== Define the View

You implement a View by extending `kalix.javasdk.view.View` and subscribing to changes from an entity. You specify how to query it by providing one or more methods annotated with `@Query`, which is then made accessible via REST annotations.

.src/main/java/customer/view/CustomersByNameView.java
[source,java]
----
include::example$java-spring-valueentity-customer-registry/src/main/java/customer/view/CustomersByNameView.java[tags=class]
----
<1> Defining view ID.
<2> Defining table name.
<3> Subscribing to `CustomerEntity`.
<4> Extending from `View`.
<5> Defining endpoint.
<6> Defining the query.
<7> The query method returns a `Flux`, meaning that the results will be streamed to the client.
<8> Note that no return is needed.


NOTE: Note that the return value of the method is `null`. You may ask yourself, how is it that the endpoint responds with any `Customer` at all?. When you call this endpoint, it first hits the Kalix Runtime, which calls directly to the database. When the runtime receives the response, it sends it directly to you without any further intervention from the View. Therefore, `null` is valid as a return value in the endpoint of a View. The choice of `null` is our way to make clear that the response doesn't come from the return of this method. But you can choose any response you like as long as it is compatible with the return type.

IMPORTANT: Adding a view ID to your View allows you to refactor the name of the class later on without the risk of losing the view. If you don't define a view ID the class name becomes its ID. Therefore, if you change the name of your class, afterwards Kalix will not recognize this new name as the same view and will create a brand-new view. This is resource consuming for a view from an Event Sourced Entity because it will reprocess all the events of that entity to rebuild it. While for a view built from a topic, you can lose all the previous events because, depending on the topic configuration, you may only process events from the current time forwards. Last but not least, it's also a problem for Value Entities because it will need to index them again when grouping them by some value.

=== Using a transformed model

Often, you will want to transform the entity model to which the view is subscribing into a different representation. To do that, let's have a look at the example in which we store a summary of the `Customer` used in the previous section instead of the original one:

[source,java]
.src/main/java/customer/api/CustomerSummary.java
----
include::example$java-spring-valueentity-customer-registry/src/main/java/customer/api/CustomerSummary.java[tag=record]
----

In this scenario, the view state should be of type `CustomerSummary` and you will need to handle and transform the incoming state changes into it, as shown below:

[source,java]
.src/main/java/customer/api/CustomerSummaryByName.java
----
include::example$java-spring-valueentity-customer-registry/src/main/java/customer/view/CustomerSummaryByName.java[tag=class]
----
<1> View is of type `CustomerSummary`.
<2> `@Subscribe` annotation is at method level rather than at class level.
<3> Annotated method needs to handle the state changes of the entity being subscribed to.
<4> Transform `Customer` into `CustomerSummary`.
<5> Define route to this view.
<6> Define the query matching by name.
<7> Query method returns a `CustomerSummary`.

[#ve_delete]
=== Handling Value Entity deletes

The View state corresponding to an Entity is not automatically deleted when the Entity is deleted.

Value Entities can be xref:value-entity#deleting_state[deleted]. We can update our view model based on that fact with an additional flag `handleDeletes` for the subscription.

[source,java]
.src/main/java/customer/api/CustomerSummaryByName.java
----
include::example$java-spring-valueentity-customer-registry/src/main/java/customer/view/CustomerSummaryByName.java[tag=delete]
----
<1> `@Subscribe` annotation with `handleDeletes=true`.
<2> Dedicated (parameter-less) handler for deletion.
<3> An effect to delete the view state `effects().deleteState()`. It could be also an update of a special column, to mark view state as deleted.

NOTE: When using @Subscribe on a class level, `handleDeletes=true` will also work. Kalix will automatically delete the View state.

[#event-sourced-entity]
== Creating a View from an Event Sourced Entity

You can create a View from an Event Sourced Entity by using events that the Entity emits to build a state representation.

Using our Customer Registry service example, to create a View for querying customers by name,
you have to <<_define_the_view_to_consume_events, define the view to consume events>>.

This example assumes a Customer equal to the previous example and an Event Sourced Entity that uses this Customer. The Event Sourced Entity is in charge of producing the events that update the View. These events are defined as subtypes of the class `CustomerEvent` following standard https://github.com/FasterXML/jackson-annotations#handling-polymorphic-types[Jackson notation] like this:

.src/main/java/customer/domain/CustomerEvent.java
[source,java]
----
include::example$java-spring-eventsourced-customer-registry/src/main/java/customer/domain/CustomerEvent.java[tags=class]
----
<1> Includes the logical type name using `@TypeName` annotation.

IMPORTANT: It's highly recommended to add a `@TypeName` to your persisted events. Kalix needs to identify each event in order to deliver them to the right event handlers. If no logical type name is specified, Kalix uses the FQCN, check xref:serialization.adoc#_type_name[type name] documentation for more details.


=== Define the View to consume events

The definition of the view for an Event Sourced Entity is the same as for a Value Entity. However, in this example, the subscription is at the method level rather than the type level. The advantage of this approach is that you can create multiple methods to handle different events. It is recommended you add a view ID to your view. 

Every time an event is processed by the view, the state of the view can be updated. You can do this with the `.updateState` method, which is available through the `effects()` API. Here you can see how the View is updated with a new name: 

.src/main/java/customer/view/CustomerByNameView.class
[source,java]
----
include::example$java-spring-eventsourced-customer-registry/src/main/java/customer/view/CustomerByNameView.java[tags=class]
----
<1> Setting view ID.
<2> Updating the state of the view with the new name.

An Event Sourced entity can emit many types of events. You need to define a method for each event type. They return an `UpdateEffect`, which describes next processing actions, such as updating the view state.

See <<#query>> for more examples of valid query syntax.

=== Ignoring events

When consuming events, each event must be matched by a View service method. In case your View is only interested in certain events:

. You can add event handlers for all of them and return `Effect.ignore` for those you are not interested.

. You can add `ignoreUnknown = true` to your `@Subcribe` annotation but only if it is a type level annotation. This works in a View the same way as in an Action. Check out this example in xref:java:actions-publishing-subscribing.adoc#_type_level_annotations_for_subscribing[type level subscribing for an action].

If there is no handler for an incoming event and there is no `ignoreUnknown = true` at type level, the View will fail. Views are designed to restart, but since it can't process the event, the view will keep failing trying to reprocess it.

[#es_delete]
=== Handling Event Sourced Entity deletes

The View state corresponding to an Entity is not automatically deleted when the Entity is deleted.

To delete from the View you can use the `deleteState()` effect from an event transformation method.

[#topic-view]
== Creating a View from a topic

The source of a View can be a topic. It works the same way as shown in <<event-sourced-entity>> or <<value-entity>>, but you define it with `@Subscribe.Topic` instead. Note that, on your producer side you must manually pass the `ce-subject` metadata, required by the View component. See the example below for how to pass such metadata.

[source,java]
.com/example/actions/CounterJournalToTopicWithMetaAction.java
----
include::example$java-spring-eventsourced-counter/src/main/java/com/example/actions/CounterJournalToTopicWithMetaAction.java[tag=class]
----
<1> The `ce-subject` attribute is the entity id.
<2> The effect replies updated metadata together with the message payload.

[#relational-projection]
== How to transform results

When creating a View, you can transform the results as a relational projection instead of using a `SELECT *` statement.


=== Relational projection

Instead of using `SELECT *` you can define which columns will be used in the response message. So, if you want to use a `CustomerSummary` used on the previous section.

You will need to define your entity as this:

[source,java]
.src/main/java/customer/api/CustomersStreamByName.java
----
include::example$java-spring-valueentity-customer-registry/src/main/java/customer/view/CustomersStreamByName.java[tag=class]
----
<1> View state type is the original `Customer` as shown at the beginning of this section.
<2> Query is mapped to an external route as usual receiving a `customerName` as parameter.
<3> Note the renaming from `customerId` as `id` on the query, as `id` and `name` match the record `CustomerSummary`.
<4> Since this query can return multiple results, mark it as streaming updates.
<5> Return type of the query is `Flux<CustomerSummary>`.

NOTE: In the example, when not interested in having multiple results, the `streamUpdates` flag could be removed and the return type would be only `CustomerSummary`.

In a similar way, you can include values from the request in the response, for example `:requestId`:

[source,sql]
----
SELECT :requestId, customerId as id, name FROM customers
WHERE name = :customerName
----

=== Response message including the result

Instead of streamed results you can include the results in a `Collection` field in the response object:

[source,java]
.src/main/java/customer/api/CustomersResponse.java
----
include::example$java-spring-valueentity-customer-registry/src/main/java/customer/api/CustomersResponse.java[tag=record]
----

[source,java,indent=0]
.src/main/java/customer/api/CustomersResponseByName.java
----
include::example$java-spring-valueentity-customer-registry/src/main/java/customer/view/CustomersResponseByName.java[tag=class]
----
<1> View state type is the original `Customer` as shown at the beginning of this section.
<2> Query is mapped to an external route as usual receiving a `customerName` as parameter.
<3> Note the use of `* AS customers` so records are matched to the collection in `CustomersResponse`.
<4> Return type of the query is `CustomersResponse`.

[#changing]
== How to modify a View

Kalix creates indexes for the View based on the queries. For example, the following query will result in a View with an index on the `name` column:

[source,sql,indent=0]
----
SELECT * FROM customers WHERE name = :customer_name
----

You may realize after a deployment that you forgot adding some parameters to the query Parameters that aren't exposed to the endpoint of the View. After adding these parameters the query is changed and therefore Kalix needs to add indexes for these new columns. For example, changing the above query to filter to add users that are active would mean that Kalix needs to build a View with the index on the `is-active` column.

[source,sql,indent=0]
----
SELECT * FROM customers WHERE name = :customer_name AND is-active = true
----

Such changes require you to define a new View. Kalix will then rebuild it from the source event log or value changes.

WARNING: Views from topics cannot be rebuilt from the source messages, because it might not be possible to consume all events from the topic again. The new View is built from new messages published to the topic.

Rebuilding a new View may take some time if there are many events that have to be processed. The recommended way when changing a View is multi-step, with two deployments:

. Define the new View with a new `@ViewId`, and keep the old View intact. 
. Deploy the new View, and let it rebuild. Verify that the new query works as expected. The old View can still be used.
. Remove the old View but keep its `@GetMapping` path, and use it in the new View.
. Deploy the second change.

The View definitions are stored and validated when a new version is deployed. There will be an error message if the changes are not compatible.


== Streaming view updates

A query can provide a near real time stream of results for the query, emitting new entries matching the query as they are added or updated in
the view.

This will first list the complete result for the query and then keep the response stream open, emitting new or updated
entries matching the query as they are added to the view. The stream does not complete until the client closes it.

NOTE: This is not intended as transport for xref:service-to-service.adoc[service to service] propagation of updates and it does not guarantee delivery. For such use cases you
should instead publish events to a topic, see xref:actions-publishing-subscribing.adoc[Publishing and Subscribing with Actions]

[#query]
include::java-protobuf:partial$query-syntax-reference.adoc[tag=spring]

include::java-protobuf:partial$query-syntax-paging.adoc[tag=spring]

include::java-protobuf:partial$query-syntax-advanced.adoc[tag=spring]

== Testing the View

Testing Views is very similar to testing other xref:actions-publishing-subscribing.adoc#_testkit_mocked_incoming_messages[subscription integrations].

For a View definition that subscribes to changes from the `customer` Value Entity.

[source,java,indent=0]
.src/main/java/customer/view/CustomersResponseByCity.java
----
include::example$java-spring-valueentity-customer-registry/src/main/java/customer/view/CustomersResponseByCity.java[tag=view-test]
----

An integration test can be implemented as below.

[source,java,indent=0]
.src/main/java/customer/view/CustomersResponseByCity.java
----
include::example$java-spring-valueentity-customer-registry/src/it/java/customer/view/CustomersResponseByCityIntegrationTest.java[tag=view-test]
----
<1> Mocks incoming messages from the `customer` Value Entity.
<2> Gets an `IncomingMessages` from the `customer` Value Entity.
<3> Publishes test data.
<4> Queries the view and asserts the results.