name: Documentation

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

permissions:
  contents: read

jobs:
  make-docs:
    runs-on: Akka-Default
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.3
        uses: coursier/cache-action@566e01fea33492e5a89706b43fb0d3fc884154f9

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.17

      - name: Setup global resolver
        uses: ./.github/setup/global_resolver

      - name: Make docs and validate links
        run: make -C docs dev validate-links

  prose:
    runs-on: Akka-Default
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      # https://vale.sh
      - name: Vale
        # https://github.com/errata-ai/vale-action/releases
        # v2.0.1
        uses: errata-ai/vale-action@c4213d4de3d5f718b8497bd86161531c78992084
        with:
          version: 3.0.5
          files: docs
          fail_on_error: true
          filter_mode: nofilter
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
