name: Documentation

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

permissions:
  contents: read

jobs:
  make-docs:
    runs-on: Akka-Default
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        uses: coursier/cache-action@v8.1.0

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        uses: coursier/setup-action@v3.0.0
        with:
          jvm: temurin:1.17

      - name: Checkout Global Scripts
        uses: actions/checkout@v6
        with:
          repository: akka/github-actions-scripts
          path: scripts

      - name: Setup global resolver
        run: |
          chmod +x ./scripts/setup_global_resolver.sh
          ./scripts/setup_global_resolver.sh

      - name: Make docs and validate links
        run: make -C docs dev validate-links

  prose:
    runs-on: Akka-Default
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6

      # https://vale.sh
      - name: Vale
        # https://github.com/errata-ai/vale-action/releases
        uses: errata-ai/vale-action@v2.1.1
        with:
          version: 3.0.5
          files: docs
          fail_on_error: true
          filter_mode: nofilter
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
