name: Publish docs

on:
  push:
    tags: ["v*"]

permissions:
  # pushing to docs/kalix-current branch (see docs/bin/deploy.sh)
  contents: write

jobs:
  push-documentation:
    name: Push documentation to docs/kalix-current
    runs-on: Akka-Default
    if: github.event.repository.fork == false
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        uses: coursier/setup-action@v3.0.0
        with:
          jvm: temurin:1.17.0.5

      - name: Checkout Global Scripts
        uses: actions/checkout@v6
        with:
          repository: akka/github-actions-scripts
          path: scripts

      - name: Setup global resolver
        run: |
          chmod +x ./scripts/setup_global_resolver.sh
          ./scripts/setup_global_resolver.sh

      - name: Publish docs
        run: make -C docs deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
