name: Publish

on:
  push:
    branches:
      - main
      - release-*
    tags: ["v*"]

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    name: Publish (sbt & Maven)
    runs-on: Akka-Default
    if: github.event.repository.fork == false
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.5
        uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.17.0.5

      - name: Setup global resolver
        uses: ./.github/setup/global_resolver

      - name: Determine SDK version
        id: determine_sdk_version
        run: |-
          .github/determine-sdk-version.sh
          SDK_VERSION="$(cat ~/kalix-sdk-version.txt)"
          echo "SDK version: '${SDK_VERSION}'"

      - name: sbt publishSigned
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        run: sbt +publishSigned

      - name: sbt publishM2
        run: sbt +publishM2

      - name: mvn deploy
        run: |-
          export SDK_VERSION="$(cat ~/kalix-sdk-version.txt)"
          ./.github/publish-maven.sh
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.KALIX_IO_SONATYPE_USER }}
          SONATYPE_PASSWORD: ${{ secrets.KALIX_IO_SONATYPE_PASSWORD }}

  validate-tag:
    name: Validate that tag is a release and not a snapshot or a milestone
    runs-on: Akka-Default
    needs: publish
    outputs:
      release: ${{ steps.verification.outputs.release }}
    steps:

      - name: Verify the tag is a release, not snapshot or milestone
        id: verification
        run: |
          TAG_NAME=${{ github.ref_name }}
          if [[ $TAG_NAME =~ ^v[0-9]+(\.[0-9]+){1,2}$ ]]; then
             echo "release=true" >> $GITHUB_OUTPUT
          else 
             echo "Invalid version tag [$TAG_NAME]. Snapshots or milestones don't create PRs"
          fi
        shell: bash

  create-pr:
    name: Create PR to update maven plugin and samples
    runs-on: Akka-Default
    needs: validate-tag
    if: needs.validate-tag.outputs.release == 'true'
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.5
        uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

      - name: Set up JDK 21
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.21

      - name: Setup global resolver
        uses: ./.github/setup/global_resolver

      - name: Determine SDK version
        id: determine_sdk_version
        run: |-
          .github/determine-sdk-version.sh
          SDK_VERSION="$(cat ~/kalix-sdk-version.txt)"
          echo "sdk_version=${SDK_VERSION}" >> $GITHUB_OUTPUT

      - name: Create the PR
        env:
          SDK_VERSION: ${{ steps.determine_sdk_version.outputs.sdk_version }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          echo "Updating samples to version ${SDK_VERSION}"
          ./updateSdkVersions.sh all
          BRANCH=bump-sdk-versions-${SDK_VERSION}
          git checkout -b ${BRANCH}
          git config user.name "Kalix Bot"
          git config user.email "kalix.github@lightbend.com"
          git commit . -m "chore: bump SDK versions to ${SDK_VERSION}"
          git remote add origin-rw https://${GH_TOKEN}@github.com/lightbend/kalix-jvm-sdk
          git push --set-upstream origin-rw ${BRANCH}
          
          gh pr create -H ${BRANCH} -B main -t "Auto PR - Bump SDK versions to ${SDK_VERSION}" \
            -b "This PR should update all existing samples (pom.xml and plugins.sbt) and the maven-java poms. Please review, and merge if okay." \
            -r ${{ github.actor }} || echo "No changes"; exit 0
