/*
 * Copyright 2021 Lightbend Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by Akka gRPC. DO NOT EDIT.
package com.example;


import akka.grpc.javadsl.SingleResponseRequestBuilder;


public abstract class CounterServiceClientPowerApi {
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer increase(com.example.CounterApi.IncreaseValue) if possible.
     */
    
      public SingleResponseRequestBuilder<com.example.CounterApi.IncreaseValue, com.google.protobuf.Empty> increase()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer decrease(com.example.CounterApi.DecreaseValue) if possible.
     */
    
      public SingleResponseRequestBuilder<com.example.CounterApi.DecreaseValue, com.google.protobuf.Empty> decrease()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer reset(com.example.CounterApi.ResetValue) if possible.
     */
    
      public SingleResponseRequestBuilder<com.example.CounterApi.ResetValue, com.google.protobuf.Empty> reset()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer getCurrentCounter(com.example.CounterApi.GetCounter) if possible.
     */
    
      public SingleResponseRequestBuilder<com.example.CounterApi.GetCounter, com.example.CounterApi.CurrentCounter> getCurrentCounter()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
}
